import type { BarrelDefinition, DroneRole, FireMode, LineageId, TankDefinition, Tier } from '../schema';

const ESCORT = { role: 'escort' as const, damage: 4.5, hp: 30, speed: 220, leash: 250 };

type RawProjectile = {
  dmg: number; speed: number; r: number; pen: number; reload: number; ttl?: number;
  splash?: number; splashDmg?: number; knock?: number; pellets?: number; spread?: number;
  cluster?: number; clusterDmg?: number;
};
type RawTank = {
  id: string; name: string; tier: Tier; parent?: string; lineage: LineageId; desc: string; color: string; icon: string;
  barrels: readonly BarrelDefinition[]; fireMode: FireMode; bullet: RawProjectile;
  hpMult: number; moveMult: number; bodyMult: number; size: number; ability?: string; aura?: number;
  droneCount: number; droneRole?: DroneRole; droneDmg?: number; droneHp?: number; droneSpeed?: number; droneLeash?: number; droneRespawnMult?: number;
};

const b = (off: number, len: number, w: number, x = 0, y = 0): BarrelDefinition => ({ off, len, w, x, y });
const t = (value: RawTank): RawTank => value;

/**
 * Canonical balance specimen copied from the effective materialized game/classes
 * registry at main@52009c406b948a7b9a9402bb56495f20b3918ba6. Later doctrine patches add
 * behavior; they do not silently rebalance these base class literals. Descriptions
 * changed by active doctrine patches are recorded at their effective values.
 */
const RAW_TANKS: readonly RawTank[] = [
  t({id:'scout',name:'Scout',tier:0,lineage:'origin',desc:'Balanced starter tank with 1 escort drone. Evolve at level 10.',color:'#7dd3fc',icon:'✦',barrels:[b(0,26,7)],fireMode:'single',bullet:{dmg:12,speed:440,r:5,pen:1,reload:.5},hpMult:1,moveMult:1,bodyMult:1,droneCount:1,size:14}),
  t({id:'twin',name:'Twin Gun',tier:1,parent:'scout',lineage:'gunner',desc:'Dual cannons + 2 escorts. 2× fire rate, lighter shells.',color:'#4de3ff',icon:'≣',barrels:[b(-.05,26,6,-6),b(.05,26,6,6)],fireMode:'twin',bullet:{dmg:9.5,speed:470,r:4.4,pen:1,reload:.26},hpMult:.95,moveMult:1.04,bodyMult:1,droneCount:2,droneDmg:4,droneSpeed:240,size:14}),
  t({id:'minigun',name:'Minigun',tier:2,parent:'twin',lineage:'gunner',desc:'Rotary cannon + 2 escorts. Melts anything up close.',color:'#4de3ff',icon:'☄',barrels:[b(-.1,24,4,-8),b(0,26,4),b(.1,24,4,8)],fireMode:'minigun',bullet:{dmg:7,speed:480,r:3.8,pen:1,reload:.09,ttl:.8},hpMult:1.05,moveMult:1.02,bodyMult:1.1,droneCount:2,droneDmg:5,droneSpeed:240,size:15,ability:'overheat'}),
  t({id:'shotgun',name:'Shotgunner',tier:2,parent:'twin',lineage:'gunner',desc:'5-pellet spread + 2 escorts. Devastating up close.',color:'#4de3ff',icon:'≋',barrels:[b(0,24,8)],fireMode:'shotgun',bullet:{dmg:8,speed:540,r:4.2,pen:1,reload:.95,ttl:.42,pellets:5,spread:.21},hpMult:1.08,moveMult:1.02,bodyMult:1.15,droneCount:2,droneDmg:5.5,size:15,ability:'pointblank'}),
  t({id:'cannon',name:'Cannon',tier:1,parent:'scout',lineage:'cannon',desc:'Heavy splash shells + 1 heavy escort drone.',color:'#ffb45e',icon:'◉',barrels:[b(0,30,9)],fireMode:'single',bullet:{dmg:26,speed:380,r:8.5,pen:1,reload:.95,splash:72,splashDmg:.4,knock:140},hpMult:1.1,moveMult:.98,bodyMult:1.15,droneCount:1,droneDmg:6.5,droneHp:40,size:15}),
  t({id:'bomber',name:'Bomber',tier:2,parent:'cannon',lineage:'cannon',desc:'Cluster shells burst into 6 bombs. 2 heavy escorts.',color:'#ffb45e',icon:'❋',barrels:[b(0,30,9)],fireMode:'shell',bullet:{dmg:20,speed:360,r:8,pen:1,reload:1.15,ttl:1.1,cluster:6,clusterDmg:9,splash:45,splashDmg:.3},hpMult:1.15,moveMult:.96,bodyMult:1.2,droneCount:2,droneDmg:6,droneHp:40,size:15,ability:'ragnarok'}),
  t({id:'demolisher',name:'Demolisher',tier:2,parent:'cannon',lineage:'cannon',desc:'Giant shells, massive splash. 2 heavy escorts.',color:'#ffb45e',icon:'☢',barrels:[b(0,33,11)],fireMode:'single',bullet:{dmg:34,speed:350,r:9.5,pen:1,reload:1.3,splash:115,splashDmg:.55,knock:330,ttl:1.3},hpMult:1.2,moveMult:.94,bodyMult:1.3,droneCount:2,droneDmg:7,droneHp:44,size:16,ability:'ragnarok'}),
  t({id:'marksman',name:'Marksman',tier:1,parent:'scout',lineage:'sniper',desc:'Long-range piercing rounds + 1 spotter drone.',color:'#b06bff',icon:'⌖',barrels:[b(0,34,6)],fireMode:'single',bullet:{dmg:21,speed:1050,r:5.5,pen:2,reload:1,ttl:1.6},hpMult:.95,moveMult:.98,bodyMult:1,droneCount:1,droneDmg:5,droneLeash:320,size:14}),
  t({id:'railgun',name:'Railgun',tier:2,parent:'marksman',lineage:'sniper',desc:'Hyper-velocity piercing beam + 2 spotter drones.',color:'#b06bff',icon:'⚡',barrels:[b(0,38,7)],fireMode:'beam',bullet:{dmg:46,speed:2500,r:6.5,pen:10,reload:1.55,ttl:.55},hpMult:.95,moveMult:.96,bodyMult:1,droneCount:2,droneDmg:5.5,droneLeash:340,size:14,ability:'supercharge'}),
  t({id:'ghost',name:'Ghost',tier:2,parent:'marksman',lineage:'sniper',desc:'Cloaks when still. 2 fast escorts. Blink ambushes.',color:'#b06bff',icon:'☁',barrels:[b(0,32,6)],fireMode:'single',bullet:{dmg:24,speed:980,r:5.5,pen:2,reload:.92,ttl:1.4},hpMult:.9,moveMult:1.06,bodyMult:1,droneCount:2,droneDmg:5.5,droneSpeed:265,size:14,ability:'phase'}),
  t({id:'carrier',name:'Drone Carrier',tier:1,parent:'scout',lineage:'controller',desc:'3 roaming HUNTER drones — true autonomous killers.',color:'#54e38a',icon:'⋔',barrels:[b(0,22,6)],fireMode:'single',bullet:{dmg:7,speed:430,r:4,pen:1,reload:.65},hpMult:1,moveMult:1.05,bodyMult:1,droneCount:3,droneRole:'hunter',droneDmg:10,droneHp:58,droneSpeed:252,droneLeash:700,size:14}),
  t({id:'overlord',name:'Overlord',tier:2,parent:'carrier',lineage:'controller',desc:'6 lethal HUNTERS. Commands the whole battlefield.',color:'#54e38a',icon:'❖',barrels:[b(0,22,6)],fireMode:'single',bullet:{dmg:6.5,speed:430,r:4,pen:1,reload:.6},hpMult:1,moveMult:1.06,bodyMult:1.05,droneCount:6,droneRole:'hunter',droneDmg:11,droneHp:62,droneSpeed:262,droneLeash:860,size:14,ability:'swarm'}),
  t({id:'warden',name:'Warden',tier:2,parent:'carrier',lineage:'controller',desc:'4 armored hunters + aura soaking 25% of damage.',color:'#54e38a',icon:'◍',barrels:[b(0,22,6)],fireMode:'single',bullet:{dmg:8,speed:430,r:4,pen:1,reload:.6},hpMult:1.2,moveMult:1.02,bodyMult:1.1,droneCount:4,droneRole:'hunter',droneDmg:9,droneHp:86,droneSpeed:236,droneLeash:600,aura:.25,size:15,ability:'bulwark'}),
  t({id:'guard',name:'Guard',tier:1,parent:'scout',lineage:'guardian',desc:'Armored vanguard, heavy slam + 2 armored escorts.',color:'#ff6ea9',icon:'⬢',barrels:[b(0,26,8)],fireMode:'single',bullet:{dmg:11,speed:420,r:5,pen:1,reload:.5},hpMult:1.6,moveMult:.92,bodyMult:2,droneCount:2,droneDmg:5,droneHp:62,droneSpeed:205,size:16}),
  t({id:'fortress',name:'Fortress',tier:2,parent:'guard',lineage:'guardian',desc:'Walking bunker, immense HP + 3 armored escorts.',color:'#ff6ea9',icon:'⬣',barrels:[b(0,26,9)],fireMode:'single',bullet:{dmg:9,speed:400,r:5.5,pen:1,reload:.55},hpMult:2.05,moveMult:.8,bodyMult:3.4,droneCount:3,droneDmg:5.5,droneHp:80,droneSpeed:200,droneLeash:230,size:19,ability:'taunt'}),
  t({id:'juggernaut',name:'Juggernaut',tier:2,parent:'guard',lineage:'guardian',desc:'Living battering ram + 2 aggressive escorts.',color:'#ff6ea9',icon:'▲',barrels:[b(0,24,8)],fireMode:'single',bullet:{dmg:9.5,speed:450,r:5,pen:1,reload:.55},hpMult:1.45,moveMult:1.08,bodyMult:4.4,droneCount:2,droneDmg:7,droneHp:60,droneSpeed:250,droneLeash:300,size:16,ability:'stampede'}),

  t({id:'tempest',name:'Tempest',tier:3,parent:'minigun',lineage:'gunner',desc:'Redline cyclone. Hold the broad power band for unmatched pressure; overshoot it and the five barrels kick the chassis apart.',color:'#71efff',icon:'✺',barrels:[b(-.14,23,4,-12),b(-.07,25,4,-6),b(0,27,4),b(.07,25,4,6),b(.14,23,4,12)],fireMode:'minigun',bullet:{dmg:6.2,speed:500,r:3.7,pen:1,reload:.058,ttl:.82},hpMult:1.12,moveMult:1.03,bodyMult:1.15,droneCount:3,droneDmg:5.4,droneSpeed:250,size:15,ability:'overheat'}),
  t({id:'needlestorm',name:'Needle Storm',tier:3,parent:'minigun',lineage:'gunner',desc:'Precision gate rotary. Exact heat plus stable tracking hardens the needle stream for ranged penetration.',color:'#71efff',icon:'⇶',barrels:[b(-.05,30,3.8,-6),b(0,33,3.8),b(.05,30,3.8,6)],fireMode:'minigun',bullet:{dmg:8.8,speed:690,r:3.8,pen:2,reload:.1,ttl:1.08},hpMult:1.02,moveMult:1.06,bodyMult:1.05,droneCount:2,droneDmg:5.2,droneSpeed:260,size:14,ability:'overheat'}),
  t({id:'breachlord',name:'Breachlord',tier:3,parent:'shotgun',lineage:'gunner',desc:'Brace-cycle breacher. A settled volley is monstrous, but every committed blast creates a short punishable recovery.',color:'#71efff',icon:'≋',barrels:[b(0,27,11)],fireMode:'shotgun',bullet:{dmg:8.2,speed:565,r:4.3,pen:1,reload:.84,ttl:.46,pellets:9,spread:.34},hpMult:1.24,moveMult:1,bodyMult:1.35,droneCount:3,droneDmg:6.2,size:16,ability:'pointblank'}),
  t({id:'flakmaster',name:'Flakmaster',tier:3,parent:'shotgun',lineage:'gunner',desc:'Range-disciplined flak. Calm tracking turns the six-pellet cone into a long-lane precision weapon.',color:'#71efff',icon:'⋙',barrels:[b(0,31,9)],fireMode:'shotgun',bullet:{dmg:10.5,speed:760,r:4.2,pen:2,reload:1.02,ttl:.7,pellets:6,spread:.14},hpMult:1.1,moveMult:1.04,bodyMult:1.18,droneCount:2,droneDmg:6,droneSpeed:250,size:15,ability:'pointblank'}),
  t({id:'clusterking',name:'Cluster King',tier:3,parent:'bomber',lineage:'cannon',desc:'Sector programmer. Fuse depth controls both where the cluster opens and how wide its child-bomb fan spreads.',color:'#ffc779',icon:'✹',barrels:[b(0,32,10)],fireMode:'shell',bullet:{dmg:22,speed:385,r:8.4,pen:1,reload:1.02,ttl:1.15,cluster:10,clusterDmg:11,splash:58,splashDmg:.38},hpMult:1.2,moveMult:.97,bodyMult:1.28,droneCount:3,droneDmg:6.5,droneHp:44,size:16,ability:'ragnarok'}),
  t({id:'siegebomber',name:'Siege Bomber',tier:3,parent:'bomber',lineage:'cannon',desc:'True siege artillery. Deliberate shell placement applies exceptional structural pressure to Battlefield cover.',color:'#ffc779',icon:'✷',barrels:[b(0,35,11)],fireMode:'shell',bullet:{dmg:30,speed:365,r:9,pen:1,reload:1.24,ttl:1.25,cluster:5,clusterDmg:16,splash:92,splashDmg:.5,knock:120},hpMult:1.28,moveMult:.94,bodyMult:1.4,droneCount:2,droneDmg:7,droneHp:48,size:17,ability:'ragnarok'}),
  t({id:'annihilator',name:'Annihilator',tier:3,parent:'demolisher',lineage:'cannon',desc:'Maximum commitment cannon. Deep programmed shots gain blast authority at the cost of an even larger reload opening.',color:'#ffc779',icon:'☄',barrels:[b(0,38,13)],fireMode:'single',bullet:{dmg:54,speed:345,r:11.5,pen:2,reload:1.58,splash:155,splashDmg:.68,knock:470,ttl:1.45},hpMult:1.34,moveMult:.9,bodyMult:1.6,droneCount:2,droneDmg:7.6,droneHp:50,size:18,ability:'ragnarok'}),
  t({id:'quake',name:'Quake Cannon',tier:3,parent:'demolisher',lineage:'cannon',desc:'Displacement artillery. Deep fuse programs trade time and prediction for stronger lane-clearing shock.',color:'#ffc779',icon:'◉',barrels:[b(0,35,11)],fireMode:'single',bullet:{dmg:39,speed:475,r:9.5,pen:1,reload:.96,splash:108,splashDmg:.56,knock:290,ttl:1.2},hpMult:1.24,moveMult:.97,bodyMult:1.42,droneCount:3,droneDmg:7.1,droneHp:46,size:17,ability:'ragnarok'}),
  t({id:'singularity',name:'Singularity',tier:3,parent:'railgun',lineage:'sniper',desc:'Extreme rail velocity and penetration. A map-length execution beam.',color:'#c493ff',icon:'✧',barrels:[b(0,43,7)],fireMode:'beam',bullet:{dmg:70,speed:3100,r:6.8,pen:18,reload:1.82,ttl:.68},hpMult:.94,moveMult:.97,bodyMult:1,droneCount:2,droneDmg:6,droneLeash:380,size:14,ability:'supercharge'}),
  t({id:'prism',name:'Prism Rail',tier:3,parent:'railgun',lineage:'sniper',desc:'Twin parallel rail beams trade one-shot power for ruthless consistency.',color:'#c493ff',icon:'Ⅱ',barrels:[b(0,39,5.5,-6),b(0,39,5.5,6)],fireMode:'beam',bullet:{dmg:44,speed:2700,r:5.5,pen:10,reload:1.24,ttl:.62},hpMult:1,moveMult:1,bodyMult:1,droneCount:3,droneDmg:5.8,droneLeash:360,size:14,ability:'supercharge'}),
  t({id:'specter',name:'Specter',tier:3,parent:'ghost',lineage:'sniper',desc:'Fast-cycling ambusher with three interceptors and relentless blinks.',color:'#c493ff',icon:'☾',barrels:[b(0,34,6)],fireMode:'single',bullet:{dmg:31,speed:1220,r:5.2,pen:3,reload:.7,ttl:1.22},hpMult:.92,moveMult:1.12,bodyMult:1.05,droneCount:3,droneDmg:6.2,droneSpeed:285,droneLeash:350,size:14,ability:'phase'}),
  t({id:'assassin',name:'Assassin',tier:3,parent:'ghost',lineage:'sniper',desc:'Slower trigger, brutal alpha strike, deep penetration and escape mobility.',color:'#c493ff',icon:'†',barrels:[b(0,39,6.5)],fireMode:'single',bullet:{dmg:47,speed:1500,r:5.8,pen:4,reload:1.22,ttl:1.35},hpMult:.9,moveMult:1.1,bodyMult:1,droneCount:2,droneDmg:6,droneSpeed:280,droneLeash:370,size:14,ability:'phase'}),
  t({id:'hivemind',name:'Hivemind',tier:3,parent:'overlord',lineage:'controller',desc:'Nine hunters. The tank is almost incidental; the swarm is the weapon.',color:'#75f0a3',icon:'✥',barrels:[b(0,21,5)],fireMode:'single',bullet:{dmg:5.5,speed:430,r:3.8,pen:1,reload:.7},hpMult:1.04,moveMult:1.04,bodyMult:1.05,droneCount:9,droneRole:'hunter',droneDmg:10.5,droneHp:60,droneSpeed:270,droneLeash:940,droneRespawnMult:.68,size:15,ability:'swarm'}),
  t({id:'broodmother',name:'Broodmother',tier:3,parent:'overlord',lineage:'controller',desc:'Six elite hunters that respawn quickly and hit much harder.',color:'#75f0a3',icon:'✤',barrels:[b(0,22,6)],fireMode:'single',bullet:{dmg:7.5,speed:445,r:4,pen:1,reload:.58},hpMult:1.1,moveMult:1.08,bodyMult:1.08,droneCount:6,droneRole:'hunter',droneDmg:15,droneHp:78,droneSpeed:286,droneLeash:820,droneRespawnMult:.48,size:15,ability:'swarm'}),
  t({id:'citadel',name:'Citadel',tier:3,parent:'warden',lineage:'controller',desc:'Six armored hunters around a thick damage-soaking command core.',color:'#75f0a3',icon:'⬡',barrels:[b(0,23,7)],fireMode:'single',bullet:{dmg:9,speed:440,r:4.5,pen:1,reload:.62},hpMult:1.45,moveMult:.98,bodyMult:1.35,droneCount:6,droneRole:'hunter',droneDmg:10,droneHp:105,droneSpeed:240,droneLeash:650,droneRespawnMult:.78,aura:.35,size:17,ability:'bulwark'}),
  t({id:'valkyrie',name:'Valkyrie',tier:3,parent:'warden',lineage:'controller',desc:'Five lightning-fast hunters; less bunker, more airborne cavalry.',color:'#75f0a3',icon:'⌁',barrels:[b(0,24,6)],fireMode:'single',bullet:{dmg:10,speed:500,r:4.2,pen:1,reload:.54},hpMult:1.2,moveMult:1.11,bodyMult:1.18,droneCount:5,droneRole:'hunter',droneDmg:12.5,droneHp:74,droneSpeed:315,droneLeash:760,droneRespawnMult:.66,aura:.16,size:15,ability:'swarm'}),
  t({id:'bastion',name:'Bastion',tier:3,parent:'fortress',lineage:'guardian',desc:'Anchor bunker. Nearly stop, face the lane and become brutally efficient from the front; movement and flanks break the posture.',color:'#ff8bbc',icon:'▣',barrels:[b(0,27,10)],fireMode:'single',bullet:{dmg:10,speed:410,r:5.8,pen:1,reload:.58},hpMult:2.55,moveMult:.73,bodyMult:4.4,droneCount:5,droneDmg:6.5,droneHp:100,droneSpeed:205,droneLeash:240,aura:.1,size:21,ability:'taunt'}),
  t({id:'aegis',name:'Aegis',tier:3,parent:'fortress',lineage:'guardian',desc:'Mobile counter-guard. Perfect timing converts defense into a short repositioning window.',color:'#ff8bbc',icon:'◈',barrels:[b(0,28,9)],fireMode:'single',bullet:{dmg:13,speed:445,r:5.4,pen:1,reload:.5},hpMult:2.15,moveMult:.88,bodyMult:3.55,droneCount:4,droneDmg:8.5,droneHp:90,droneSpeed:230,droneLeash:300,aura:.17,size:19,ability:'bulwark'}),
  t({id:'meteor',name:'Meteor',tier:3,parent:'juggernaut',lineage:'guardian',desc:'Peak-commitment rammer. Straight lines build terrifying impact quickly; steering throws that force away.',color:'#ff8bbc',icon:'◆',barrels:[b(0,23,7)],fireMode:'single',bullet:{dmg:9,speed:470,r:4.8,pen:1,reload:.58},hpMult:1.62,moveMult:1.18,bodyMult:6,droneCount:2,droneDmg:8,droneHp:66,droneSpeed:275,droneLeash:330,size:17,ability:'stampede'}),
  t({id:'ravager',name:'Ravager',tier:3,parent:'juggernaut',lineage:'guardian',desc:'Flexible assault rammer. Carries momentum through moderate steering, sacrificing Meteor peak impact for route freedom.',color:'#ff8bbc',icon:'▲',barrels:[b(-.03,27,6,-5),b(.03,27,6,5)],fireMode:'twin',bullet:{dmg:14,speed:520,r:5,pen:1,reload:.38},hpMult:1.58,moveMult:1.09,bodyMult:4.7,droneCount:3,droneDmg:7.5,droneHp:68,droneSpeed:260,droneLeash:320,size:17,ability:'stampede'}),
];

export const TANK_DEFINITIONS: readonly TankDefinition[] = Object.freeze(RAW_TANKS.map((raw) => {
  const role = raw.droneRole ?? ESCORT.role;
  return Object.freeze({
    id: raw.id, name: raw.name, tier: raw.tier, parentId: raw.parent, lineage: raw.lineage,
    description: raw.desc, color: raw.color, icon: raw.icon, size: raw.size,
    hpMultiplier: raw.hpMult, moveMultiplier: raw.moveMult, bodyMultiplier: raw.bodyMult,
    aura: raw.aura, abilityId: raw.ability,
    weapon: Object.freeze({
      fireMode: raw.fireMode, barrels: Object.freeze([...raw.barrels]),
      projectile: Object.freeze({ damage: raw.bullet.dmg, speed: raw.bullet.speed, radius: raw.bullet.r,
        penetration: raw.bullet.pen, reloadSeconds: raw.bullet.reload, ttlSeconds: raw.bullet.ttl,
        splashRadius: raw.bullet.splash, splashDamageScale: raw.bullet.splashDmg, knockback: raw.bullet.knock,
        pellets: raw.bullet.pellets, spreadRadians: raw.bullet.spread, clusterCount: raw.bullet.cluster,
        clusterDamage: raw.bullet.clusterDmg })
    }),
    drone: Object.freeze({ role, count: raw.droneCount, damage: raw.droneDmg ?? ESCORT.damage,
      hp: raw.droneHp ?? ESCORT.hp, speed: raw.droneSpeed ?? ESCORT.speed,
      leash: raw.droneLeash ?? ESCORT.leash, respawnMultiplier: raw.droneRespawnMult })
  });
}));
