import type { Battlefield } from '../../battlefield/Battlefield';
import type { SeededRandom } from '../../simulation/SeededRandom';
import type { ProjectileState, ShapeState, TankState, Vector2State } from '../types';

export type LivingFrontShapeType='circle'|'triangle'|'square'|'pentagon'|'hexagon'|'star'|'crasher';
export type LivingFrontSignalType='bloom'|'migration'|'rogue-star';
export interface LivingFrontShapeRuntime{state:ShapeState;velocity:Vector2State;spin:number;xp:number;radius:number;}
export interface LivingFrontTankRuntime{state:TankState;velocity:Vector2State;radius:number;healthFraction:number;}
export interface LivingFrontProjectileRuntime{state:ProjectileState;radius:number;}
export interface LivingFrontSignal{readonly type:LivingFrontSignalType;readonly sector:number;readonly position:Readonly<Vector2State>;readonly direction?:Readonly<Vector2State>;readonly createdAtTick:number;readonly expiresAtTick:number;}
export interface LivingFrontSectorSnapshot{readonly index:number;readonly maturity:number;readonly pressure:number;readonly entityCount:number;readonly availableXp:number;readonly valueScore:number;readonly recentHarvest:number;readonly recentCombatPressure:number;readonly inboundMigration:number;readonly outboundMigration:number;}
export interface LivingFrontTelemetry{readonly maturityCeiling:number;readonly totalAvailableXp:number;readonly triangleEvasions:number;readonly crasherCharges:number;readonly crasherChargeHits:number;readonly crasherChargeMisses:number;readonly bountyAbsorbed:number;readonly bountyReleased:number;readonly starLifetimeTicks:number;readonly migrationsDetected:number;readonly bloomsDetected:number;readonly rogueStarsSpawned:number;readonly averageHexagonLocalPopulation:number;readonly planningWorkEmaMs:number;readonly planningWorkPeakMs:number;}
export interface LivingFrontSnapshot{readonly ageMs:number;readonly directorEnabled:boolean;readonly maturityCeiling:number;readonly signal:LivingFrontSignal|null;readonly sectors:readonly LivingFrontSectorSnapshot[];readonly telemetry:LivingFrontTelemetry;}
export interface LivingFrontStepFrame{readonly tick:number;readonly elapsedMs:number;readonly dtSeconds:number;readonly shapes:readonly LivingFrontShapeRuntime[];readonly tanks:readonly LivingFrontTankRuntime[];readonly projectiles:readonly LivingFrontProjectileRuntime[];}
export interface LivingFrontStepResult{readonly crasherPreyKills:readonly {crasherId:string;preyId:string}[];readonly crasherTankHits:readonly {crasherId:string;tankId:string;damage:number}[];readonly spawnRogueStar:boolean;}
export interface LivingFrontSystemOptions{readonly battlefield:Battlefield;readonly random:SeededRandom;readonly directorEnabled?:boolean;}

interface Sector{maturity:number;pressure:number;recentHarvest:number;recentCombat:number;entityCount:number;xp:number;value:number;centroidX:number;centroidY:number;inbound:number;outbound:number;herdSaturation:number;}
interface Behavior{sector:number;previousSector:number;nextEvadeTick:number;evadeUntilTick:number;evadeDirection:Vector2State;starHeading:Vector2State;starRetargetTick:number;crasherPhase:'track'|'telegraph'|'charge'|'overshoot'|'recover';crasherPhaseUntilTick:number;crasherTargetId?:string;chargeDirection:Vector2State;contactReadyTick:number;bounty:number;spawnedAtTick:number;}

const GRID=4,COUNT=16,SECTOR_HZ_TICKS=12,BEHAVIOR_HZ_TICKS=6,DIRECTOR_HZ_TICKS=30,NORMAL_TARGET_TOTAL=120,BOUNTY_CAP=300,CRASHER_DAMAGE=26,SIGNAL_TTL=240,BLOOM_COOLDOWN=1200,ROGUE_STAR_COOLDOWN=5400;
const XP:Readonly<Record<LivingFrontShapeType,number>>=Object.freeze({circle:10,triangle:25,square:50,pentagon:100,hexagon:200,star:500,crasher:60});
const SPEED:Readonly<Record<LivingFrontShapeType,number>>=Object.freeze({circle:10,triangle:16,square:9,pentagon:6,hexagon:4,star:78,crasher:105});
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const len=(v:Vector2State)=>Math.hypot(v.x,v.y);
const norm=(v:Vector2State):Vector2State=>{const m=len(v);return m>1e-6?{x:v.x/m,y:v.y/m}:{x:0,y:0};};
const add=(a:Vector2State,b:Vector2State):Vector2State=>({x:a.x+b.x,y:a.y+b.y});
const scale=(v:Vector2State,n:number):Vector2State=>({x:v.x*n,y:v.y*n});
const d2=(a:Vector2State,b:Vector2State)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y;};

/** Reused-cell broad phase; queries reuse one scratch array and never scan the world. */
class SpatialHash<T extends {state:{position:Vector2State}}>{
 readonly #size:number;readonly #cells=new Map<string,T[]>();readonly #scratch:T[]=[];
 constructor(size=240){this.#size=size;}
 rebuild(items:readonly T[]){this.#cells.clear();for(const item of items){const x=Math.floor(item.state.position.x/this.#size),y=Math.floor(item.state.position.y/this.#size),key=`${x}:${y}`;let bucket=this.#cells.get(key);if(!bucket){bucket=[];this.#cells.set(key,bucket);}bucket.push(item);}}
 query(p:Vector2State,r:number):readonly T[]{this.#scratch.length=0;const minX=Math.floor((p.x-r)/this.#size),maxX=Math.floor((p.x+r)/this.#size),minY=Math.floor((p.y-r)/this.#size),maxY=Math.floor((p.y+r)/this.#size),rr=r*r;for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)for(const item of this.#cells.get(`${x}:${y}`)??[])if(d2(p,item.state.position)<=rr)this.#scratch.push(item);return this.#scratch;}
}

/** Canonical v1.11.0 ecology owner. Hidden sectors never cross into AI; physical state does. */
export class LivingFrontSystem{
 readonly #battlefield:Battlefield;readonly #random:SeededRandom;readonly #directorEnabled:boolean;
 readonly #sectors:Sector[]=Array.from({length:COUNT},()=>({maturity:0,pressure:0,recentHarvest:0,recentCombat:0,entityCount:0,xp:0,value:0,centroidX:0,centroidY:0,inbound:0,outbound:0,herdSaturation:0}));
 readonly #behavior=new Map<string,Behavior>();readonly #shapeHash=new SpatialHash<LivingFrontShapeRuntime>();readonly #tankHash=new SpatialHash<LivingFrontTankRuntime>();readonly #projectileHash=new SpatialHash<LivingFrontProjectileRuntime>();
 #ageMs=0;#maturityCeiling=0;#signal:LivingFrontSignal|null=null;#lastBloomTick=Number.NEGATIVE_INFINITY;#lastRogueStarTick=Number.NEGATIVE_INFINITY;#quietMovementTicks=0;#triangleEvasions=0;#crasherCharges=0;#crasherChargeHits=0;#crasherChargeMisses=0;#bountyAbsorbed=0;#bountyReleased=0;#starLifetimeTicks=0;#migrationsDetected=0;#bloomsDetected=0;#rogueStarsSpawned=0;#averageHexagonLocalPopulation=0;#planningWorkEmaMs=0;#planningWorkPeakMs=0;
 constructor(options:LivingFrontSystemOptions){this.#battlefield=options.battlefield;this.#random=options.random;this.#directorEnabled=options.directorEnabled??true;}
 get directorEnabled(){return this.#directorEnabled;}
 reset(){for(const s of this.#sectors)Object.assign(s,{maturity:0,pressure:0,recentHarvest:0,recentCombat:0,entityCount:0,xp:0,value:0,centroidX:0,centroidY:0,inbound:0,outbound:0,herdSaturation:0});this.#behavior.clear();this.#ageMs=0;this.#maturityCeiling=0;this.#signal=null;this.#lastBloomTick=Number.NEGATIVE_INFINITY;this.#lastRogueStarTick=Number.NEGATIVE_INFINITY;this.#quietMovementTicks=0;this.#triangleEvasions=0;this.#crasherCharges=0;this.#crasherChargeHits=0;this.#crasherChargeMisses=0;this.#bountyAbsorbed=0;this.#bountyReleased=0;this.#starLifetimeTicks=0;this.#migrationsDetected=0;this.#bloomsDetected=0;this.#rogueStarsSpawned=0;this.#averageHexagonLocalPopulation=0;this.#planningWorkEmaMs=0;this.#planningWorkPeakMs=0;}
 registerShape(shape:LivingFrontShapeRuntime,tick:number){const id=String(shape.state.id),sector=this.sectorIndex(shape.state.position);if(this.#behavior.has(id))return;const angle=shape.state.rotation;this.#behavior.set(id,{sector,previousSector:sector,nextEvadeTick:tick+18,evadeUntilTick:-1,evadeDirection:{x:0,y:0},starHeading:{x:Math.cos(angle),y:Math.sin(angle)},starRetargetTick:tick+90,crasherPhase:'track',crasherPhaseUntilTick:tick+30,chargeDirection:{x:Math.cos(angle),y:Math.sin(angle)},contactReadyTick:tick,bounty:0,spawnedAtTick:tick});this.writeVisible(shape,tick);}
 unregisterShape(shape:LivingFrontShapeRuntime,tick:number){const id=String(shape.state.id),b=this.#behavior.get(id),s=this.#sectors[b?.sector??this.sectorIndex(shape.state.position)];s.recentHarvest+=Math.min(1,shape.xp/220);s.pressure=clamp(s.pressure+Math.min(.22,shape.xp/1800));s.maturity=Math.max(0,s.maturity-Math.min(.18,shape.xp/1600));if(shape.state.shapeType==='star')this.#starLifetimeTicks=Math.max(this.#starLifetimeTicks,tick-(b?.spawnedAtTick??tick));if(shape.state.shapeType==='crasher'&&b?.bounty)this.#bountyReleased+=b.bounty;this.#behavior.delete(id);}
 recordGunfire(position:Vector2State,intensity=1){const s=this.#sectors[this.sectorIndex(position)],amount=Math.min(.055,.012*Math.max(0,intensity));s.pressure=clamp(s.pressure+amount);s.recentCombat+=amount;s.maturity=Math.max(0,s.maturity-amount*.42);s.herdSaturation=clamp(s.herdSaturation+.08*Math.max(0,intensity));}
 recordImpact(position:Vector2State,intensity=1){const s=this.#sectors[this.sectorIndex(position)],amount=Math.min(.1,.022*Math.max(0,intensity));s.pressure=clamp(s.pressure+amount);s.recentCombat+=amount;s.maturity=Math.max(0,s.maturity-amount*.28);}
 recordTankDeath(position:Vector2State){const s=this.#sectors[this.sectorIndex(position)];s.pressure=clamp(s.pressure+.24);s.recentCombat+=.24;s.maturity=Math.max(0,s.maturity-.12);}
 desiredCounts(elapsedMs:number):Readonly<Record<'circle'|'triangle'|'square'|'pentagon'|'hexagon',number>>{const age=elapsedMs/1000,p=Math.round(8*clamp((age-45)/150)),h=Math.round(4*clamp((age-120)/180)),deficit=12-p-h,c=Math.round(deficit*.6);return Object.freeze({circle:62+c,triangle:30+deficit-c,square:16,pentagon:p,hexagon:h});}
 chooseSpawnPoint(type:LivingFrontShapeType,fallback:()=>Vector2State):Vector2State{const box=this.sectorBounds(this.chooseSectorForType(type)),pad=type==='hexagon'?42:type==='star'?32:28;for(let i=0;i<16;i++){const p={x:this.#random.range(box.minX+pad,box.maxX-pad),y:this.#random.range(box.minY+pad,box.maxY-pad)};if(this.#battlefield.isSpawnSafe(p,pad))return p;}return fallback();}
 creditCrasherBounty(crasher:LivingFrontShapeRuntime,preyXp:number,tick:number){const b=this.#behavior.get(String(crasher.state.id));if(!b||crasher.state.shapeType!=='crasher')return;const absorbed=Math.min(Math.max(0,preyXp)*.7,BOUNTY_CAP-b.bounty);if(absorbed<=0)return;b.bounty+=absorbed;crasher.xp=XP.crasher+Math.round(b.bounty);this.#bountyAbsorbed+=absorbed;this.writeVisible(crasher,tick);}
 step(frame:LivingFrontStepFrame):LivingFrontStepResult{this.#ageMs=frame.elapsedMs;this.#maturityCeiling=clamp(frame.elapsedMs/300000);if(this.#signal&&this.#signal.expiresAtTick<=frame.tick)this.#signal=null;for(const s of frame.shapes)this.registerShape(s,frame.tick);const live=new Set(frame.shapes.map(s=>String(s.state.id)));for(const id of this.#behavior.keys())if(!live.has(id))this.#behavior.delete(id);if(frame.tick%BEHAVIOR_HZ_TICKS===0){const t=typeof performance!=='undefined'?performance.now():0;this.#shapeHash.rebuild(frame.shapes);this.#tankHash.rebuild(frame.tanks);this.#projectileHash.rebuild(frame.projectiles);for(const s of frame.shapes)this.plan(s,frame);if(typeof performance!=='undefined'){const elapsed=Math.max(0,performance.now()-t);this.#planningWorkEmaMs=this.#planningWorkEmaMs===0?elapsed:this.#planningWorkEmaMs*.9+elapsed*.1;this.#planningWorkPeakMs=Math.max(this.#planningWorkPeakMs,elapsed);}}if(frame.tick%SECTOR_HZ_TICKS===0)this.updateSectors(frame);const contacts=this.integrate(frame);const spawnRogueStar=frame.tick%DIRECTOR_HZ_TICKS===0?this.direct(frame):false;return Object.freeze({...contacts,spawnRogueStar});}
 snapshot():LivingFrontSnapshot{const sectors=this.#sectors.map((s,index)=>Object.freeze({index,maturity:s.maturity,pressure:s.pressure,entityCount:s.entityCount,availableXp:s.xp,valueScore:s.value,recentHarvest:s.recentHarvest,recentCombatPressure:s.recentCombat,inboundMigration:s.inbound,outboundMigration:s.outbound})),total=sectors.reduce((n,s)=>n+s.availableXp,0);return Object.freeze({ageMs:this.#ageMs,directorEnabled:this.#directorEnabled,maturityCeiling:this.#maturityCeiling,signal:this.#signal?Object.freeze({...this.#signal,position:Object.freeze({...this.#signal.position}),...(this.#signal.direction?{direction:Object.freeze({...this.#signal.direction})}:{})}):null,sectors:Object.freeze(sectors),telemetry:Object.freeze({maturityCeiling:this.#maturityCeiling,totalAvailableXp:total,triangleEvasions:this.#triangleEvasions,crasherCharges:this.#crasherCharges,crasherChargeHits:this.#crasherChargeHits,crasherChargeMisses:this.#crasherChargeMisses,bountyAbsorbed:Math.round(this.#bountyAbsorbed),bountyReleased:Math.round(this.#bountyReleased),starLifetimeTicks:this.#starLifetimeTicks,migrationsDetected:this.#migrationsDetected,bloomsDetected:this.#bloomsDetected,rogueStarsSpawned:this.#rogueStarsSpawned,averageHexagonLocalPopulation:this.#averageHexagonLocalPopulation,planningWorkEmaMs:this.#planningWorkEmaMs,planningWorkPeakMs:this.#planningWorkPeakMs})});}

 private updateSectors(frame:LivingFrontStepFrame){const dt=SECTOR_HZ_TICKS/60;for(const s of this.#sectors){s.entityCount=0;s.xp=0;s.value=0;s.centroidX=0;s.centroidY=0;s.inbound*=.72;s.outbound*=.72;s.pressure=Math.max(0,s.pressure-.045*dt);s.herdSaturation=Math.max(0,s.herdSaturation-.18*dt);s.recentHarvest=Math.max(0,s.recentHarvest-.14*dt);s.recentCombat=Math.max(0,s.recentCombat-.16*dt);}let movement=0;for(const shape of frame.shapes){const index=this.sectorIndex(shape.state.position),s=this.#sectors[index],type=shape.state.shapeType as LivingFrontShapeType;s.entityCount++;s.xp+=shape.xp;s.value+=shape.xp*(type==='hexagon'?1.35:type==='star'?1.6:1);s.centroidX+=shape.state.position.x;s.centroidY+=shape.state.position.y;movement+=len(shape.velocity);const b=this.#behavior.get(String(shape.state.id));if(b&&b.sector!==index){this.#sectors[b.sector].outbound+=1;s.inbound+=1;b.previousSector=b.sector;b.sector=index;}}
  for(let i=0;i<this.#sectors.length;i++){const s=this.#sectors[i];if(s.entityCount){s.centroidX/=s.entityCount;s.centroidY/=s.entityCount;}else{const c=this.sectorCenter(i);s.centroidX=c.x;s.centroidY=c.y;}}
  for(const tank of frame.tanks)if(tank.state.lifecycle==='active')this.#sectors[this.sectorIndex(tank.state.position)].pressure=clamp(this.#sectors[this.sectorIndex(tank.state.position)].pressure+.006);
  for(const s of this.#sectors){const calm=1-clamp(s.pressure*1.35+s.recentHarvest*.38+s.recentCombat*.55),rise=.018*dt*calm,disruption=.035*dt*s.pressure;s.maturity=Math.min(this.#maturityCeiling,Math.max(0,s.maturity+rise-disruption));}
  const avg=frame.shapes.length?movement/frame.shapes.length:0;this.#quietMovementTicks=avg<14?this.#quietMovementTicks+SECTOR_HZ_TICKS:0;
  const totalInbound=this.#sectors.reduce((n,s)=>n+s.inbound,0),totalOutbound=this.#sectors.reduce((n,s)=>n+s.outbound,0),migrating=Math.min(totalInbound,totalOutbound);
  if(migrating>=8&&this.#directorEnabled&&(!this.#signal||this.#signal.type!=='migration')){const target=this.#sectors.reduce((best,s,i)=>s.inbound>this.#sectors[best].inbound?i:best,0),source=this.#sectors.reduce((best,s,i)=>s.outbound>this.#sectors[best].outbound?i:best,0),from=this.sectorCenter(source),to=this.sectorCenter(target);this.#signal=Object.freeze({type:'migration',sector:target,position:to,direction:norm({x:to.x-from.x,y:to.y-from.y}),createdAtTick:frame.tick,expiresAtTick:frame.tick+SIGNAL_TTL});this.#migrationsDetected++;}
  const hexes=frame.shapes.filter(s=>s.state.shapeType==='hexagon');this.#averageHexagonLocalPopulation=hexes.length?hexes.reduce((n,h)=>n+this.#shapeHash.query(h.state.position,280).length-1,0)/hexes.length:0;
 }
 private plan(shape:LivingFrontShapeRuntime,frame:LivingFrontStepFrame){if(shape.state.lifecycle!=='active')return;const type=shape.state.shapeType as LivingFrontShapeType,b=this.#behavior.get(String(shape.state.id));if(!b)return;if(type==='circle')this.planCircle(shape);else if(type==='triangle')this.planTriangle(shape,b,frame);else if(type==='square')this.migrate(shape,.16);else if(type==='pentagon')this.migrate(shape,.11);else if(type==='hexagon')this.limit(shape,SPEED.hexagon);else if(type==='star')this.planStar(shape,b,frame);else if(type==='crasher')this.planCrasher(shape,b,frame);if(!['hexagon','star','crasher'].includes(type))this.attractHex(shape);this.writeVisible(shape,frame.tick);}
 private planCircle(shape:LivingFrontShapeRuntime){const s=this.#sectors[this.sectorIndex(shape.state.position)],school=norm({x:s.centroidX-shape.state.position.x,y:s.centroidY-shape.state.position.y});let danger={x:0,y:0};for(const tank of this.#tankHash.query(shape.state.position,180))danger=add(danger,norm({x:shape.state.position.x-tank.state.position.x,y:shape.state.position.y-tank.state.position.y}));shape.velocity=scale(norm(add(scale(norm(shape.velocity),.62),add(scale(school,.18),scale(norm(danger),.36)))),SPEED.circle);this.migrate(shape,.22);}
 private planTriangle(shape:LivingFrontShapeRuntime,b:Behavior,frame:LivingFrontStepFrame){if(frame.tick<=b.evadeUntilTick){shape.velocity=scale(b.evadeDirection,48);return;}this.limit(shape,SPEED.triangle);this.migrate(shape,.25);if(frame.tick<b.nextEvadeTick)return;let threat:LivingFrontProjectileRuntime|undefined,best=Infinity;for(const p of this.#projectileHash.query(shape.state.position,250)){const v=p.state.velocity,rel={x:shape.state.position.x-p.state.position.x,y:shape.state.position.y-p.state.position.y},ss=v.x*v.x+v.y*v.y;if(ss<1)continue;const t=(rel.x*v.x+rel.y*v.y)/ss;if(t<.06||t>.55)continue;const closest={x:p.state.position.x+v.x*t,y:p.state.position.y+v.y*t};if(d2(closest,shape.state.position)>(shape.radius+p.radius+34)**2||t>=best)continue;best=t;threat=p;}if(!threat)return;const incoming=norm(threat.state.velocity),side=((String(shape.state.id).length+frame.tick)&1)===0?1:-1;b.evadeDirection={x:-incoming.y*side,y:incoming.x*side};b.evadeUntilTick=frame.tick+9;b.nextEvadeTick=frame.tick+42;shape.velocity=scale(b.evadeDirection,48);this.#triangleEvasions++;}
 private planStar(shape:LivingFrontShapeRuntime,b:Behavior,frame:LivingFrontStepFrame){if(frame.tick>=b.starRetargetTick||len(b.starHeading)<.5){const a=this.#random.range(0,Math.PI*2);b.starHeading={x:Math.cos(a),y:Math.sin(a)};b.starRetargetTick=frame.tick+this.#random.integer(90,181);}const probe=add(shape.state.position,scale(b.starHeading,260));if(!this.#battlefield.contains(probe,shape.radius)||this.#battlefield.firstTerrainHit(shape.state.position,probe,shape.radius)){b.starHeading={x:-b.starHeading.y,y:b.starHeading.x};b.starRetargetTick=frame.tick+45;}shape.velocity=scale(norm(b.starHeading),SPEED.star);}
 private planCrasher(shape:LivingFrontShapeRuntime,b:Behavior,frame:LivingFrontStepFrame){if(b.crasherPhase==='telegraph'&&frame.tick>=b.crasherPhaseUntilTick){b.crasherPhase='charge';b.crasherPhaseUntilTick=frame.tick+34;this.#crasherCharges++;}else if(b.crasherPhase==='charge'&&frame.tick>=b.crasherPhaseUntilTick){b.crasherPhase='overshoot';b.crasherPhaseUntilTick=frame.tick+18;this.#crasherChargeMisses++;}else if(b.crasherPhase==='overshoot'&&frame.tick>=b.crasherPhaseUntilTick){b.crasherPhase='recover';b.crasherPhaseUntilTick=frame.tick+18;}else if(b.crasherPhase==='recover'&&frame.tick>=b.crasherPhaseUntilTick){b.crasherPhase='track';b.crasherPhaseUntilTick=frame.tick+24;b.crasherTargetId=undefined;}if(b.crasherPhase==='charge'){shape.velocity=scale(b.chargeDirection,185);return;}if(b.crasherPhase==='overshoot'){shape.velocity=scale(b.chargeDirection,122);return;}if(b.crasherPhase==='recover'){shape.velocity=scale(norm(shape.velocity),42);return;}const target=this.crasherTarget(shape);if(!target){shape.velocity=scale(norm(shape.velocity),55);return;}const dir=norm({x:target.position.x-shape.state.position.x,y:target.position.y-shape.state.position.y});if(b.crasherPhase==='telegraph'){shape.velocity=scale(dir,18);return;}shape.velocity=scale(dir,SPEED.crasher*.72);b.crasherTargetId=target.id;if(d2(target.position,shape.state.position)<=430*430&&frame.tick>=b.crasherPhaseUntilTick){b.crasherPhase='telegraph';b.crasherPhaseUntilTick=frame.tick+27;b.chargeDirection=dir;}}
 private crasherTarget(shape:LivingFrontShapeRuntime){let best:{id:string;position:Vector2State;score:number}|undefined;for(const prey of this.#shapeHash.query(shape.state.position,520)){if(prey===shape||prey.state.lifecycle!=='active'||['crasher','hexagon','star'].includes(prey.state.shapeType))continue;const hf=(prey.state.health?.current??1)/Math.max(1,prey.state.health?.max??1),range=Math.sqrt(d2(shape.state.position,prey.state.position)),score=(1.25-hf)*130+Math.min(140,prey.xp)-range*.08;if(!best||score>best.score)best={id:String(prey.state.id),position:prey.state.position,score};}for(const tank of this.#tankHash.query(shape.state.position,520)){if(tank.state.lifecycle!=='active')continue;const range=Math.sqrt(d2(shape.state.position,tank.state.position)),score=(1-tank.healthFraction)*180-range*.09;if(!best||score>best.score)best={id:String(tank.state.id),position:tank.state.position,score};}return best;}
 private integrate(frame:LivingFrontStepFrame):Omit<LivingFrontStepResult,'spawnRogueStar'>{const preyKills:{crasherId:string;preyId:string}[]=[],tankHits:{crasherId:string;tankId:string;damage:number}[]=[];for(const shape of frame.shapes){if(shape.state.lifecycle!=='active')continue;const b=this.#behavior.get(String(shape.state.id));let next=add(shape.state.position,scale(shape.velocity,frame.dtSeconds)),hit=this.#battlefield.firstTerrainHit(shape.state.position,next,shape.radius);if(!this.#battlefield.contains(next,shape.radius)||hit){if(shape.state.shapeType==='crasher'&&b?.crasherPhase==='charge'){b.crasherPhase='recover';b.crasherPhaseUntilTick=frame.tick+48;shape.velocity={x:0,y:0};}else if(shape.state.shapeType==='star'&&b){b.starHeading={x:-b.starHeading.y,y:b.starHeading.x};shape.velocity=scale(b.starHeading,SPEED.star);}else shape.velocity={x:-shape.velocity.x,y:-shape.velocity.y};next=add(shape.state.position,scale(shape.velocity,frame.dtSeconds));if(!this.#battlefield.isSpawnSafe(next,shape.radius))next=shape.state.position;}shape.state={...shape.state,position:next,rotation:shape.state.rotation+shape.spin*frame.dtSeconds};if(shape.state.shapeType!=='crasher'||!b||b.crasherPhase!=='charge'||frame.tick<b.contactReadyTick)continue;const prey=this.#shapeHash.query(shape.state.position,shape.radius+30).find(p=>p!==shape&&p.state.lifecycle==='active'&&!['crasher','star','hexagon'].includes(p.state.shapeType));if(prey&&d2(shape.state.position,prey.state.position)<=(shape.radius+prey.radius)**2){preyKills.push({crasherId:String(shape.state.id),preyId:String(prey.state.id)});b.contactReadyTick=frame.tick+30;b.crasherPhase='overshoot';b.crasherPhaseUntilTick=frame.tick+18;this.#crasherChargeHits++;continue;}const tank=this.#tankHash.query(shape.state.position,shape.radius+45).find(t=>t.state.lifecycle==='active'&&d2(shape.state.position,t.state.position)<=(shape.radius+t.radius)**2);if(tank){tankHits.push({crasherId:String(shape.state.id),tankId:String(tank.state.id),damage:CRASHER_DAMAGE});b.contactReadyTick=frame.tick+45;b.crasherPhase='overshoot';b.crasherPhaseUntilTick=frame.tick+18;this.#crasherChargeHits++;}}return Object.freeze({crasherPreyKills:Object.freeze(preyKills),crasherTankHits:Object.freeze(tankHits)});}
 private direct(frame:LivingFrontStepFrame){if(!this.#directorEnabled)return false;const best=this.#sectors.reduce((b,s,i)=>s.value>this.#sectors[b].value?i:b,0),s=this.#sectors[best];if(frame.tick-this.#lastBloomTick>=BLOOM_COOLDOWN&&s.value>=900&&s.maturity>=Math.min(.6,this.#maturityCeiling)){this.#signal=Object.freeze({type:'bloom',sector:best,position:this.sectorCenter(best),createdAtTick:frame.tick,expiresAtTick:frame.tick+SIGNAL_TTL});this.#lastBloomTick=frame.tick;this.#bloomsDetected++;return false;}const star=frame.shapes.some(x=>x.state.lifecycle==='active'&&x.state.shapeType==='star'),eligible=frame.elapsedMs>=120000&&!star&&frame.tick-this.#lastRogueStarTick>=ROGUE_STAR_COOLDOWN&&this.#quietMovementTicks>=1800;if(!eligible)return false;const target=this.#sectors.reduce((b,x,i)=>x.pressure<this.#sectors[b].pressure?i:b,0);this.#signal=Object.freeze({type:'rogue-star',sector:target,position:this.sectorCenter(target),createdAtTick:frame.tick,expiresAtTick:frame.tick+SIGNAL_TTL});this.#lastRogueStarTick=frame.tick;this.#rogueStarsSpawned++;this.#quietMovementTicks=0;return true;}
 private migrate(shape:LivingFrontShapeRuntime,strength:number){const current=this.sectorIndex(shape.state.position),s=this.#sectors[current];let best=current;for(const n of this.neighbors(current))if(this.#sectors[n].pressure+.14<this.#sectors[best].pressure)best=n;if(best===current||s.pressure<.18)return;const c=this.sectorCenter(best),dir=norm({x:c.x-shape.state.position.x,y:c.y-shape.state.position.y}),mixed=norm(add(scale(norm(shape.velocity),1-strength),scale(dir,strength)));shape.velocity=scale(mixed,Math.max(1,len(shape.velocity)));}
 private attractHex(shape:LivingFrontShapeRuntime){let nearest:LivingFrontShapeRuntime|undefined,best=Infinity;for(const x of this.#shapeHash.query(shape.state.position,300)){if(x===shape||x.state.shapeType!=='hexagon'||x.state.lifecycle!=='active')continue;const r=d2(shape.state.position,x.state.position);if(r<best){best=r;nearest=x;}}if(!nearest||best<65*65)return;const toward=norm({x:nearest.state.position.x-shape.state.position.x,y:nearest.state.position.y-shape.state.position.y}),dir=norm(add(scale(norm(shape.velocity),.92),scale(toward,.08)));shape.velocity=scale(dir,Math.max(1,len(shape.velocity)));}
 private limit(shape:LivingFrontShapeRuntime,speed:number){const d=norm(shape.velocity);shape.velocity=scale(len(d)>0?d:{x:Math.cos(shape.state.rotation),y:Math.sin(shape.state.rotation)},speed);}
 private writeVisible(shape:LivingFrontShapeRuntime,tick:number){const b=this.#behavior.get(String(shape.state.id));if(!b)return;const phase=shape.state.shapeType==='crasher'?b.crasherPhase:undefined;shape.state={...shape.state,livingFront:Object.freeze({sector:b.sector,...(phase?{crasherPhase:phase}:{}),bountyFraction:shape.state.shapeType==='crasher'?clamp(b.bounty/BOUNTY_CAP):0,triangleEvading:shape.state.shapeType==='triangle'&&tick<=b.evadeUntilTick})};}
 private chooseSectorForType(type:LivingFrontShapeType){const weights=this.#sectors.map(s=>{const calm=.2+1-s.pressure;if(type==='pentagon')return calm*(.1+s.maturity*2.2);if(type==='hexagon')return calm*(.04+s.maturity*s.maturity*3.2);if(type==='star')return calm*(.3+s.maturity*.8);if(type==='circle'||type==='triangle')return calm*(1.25-s.maturity*.35);return calm;}),total=weights.reduce((a,b)=>a+b,0);let roll=this.#random.range(0,Math.max(.0001,total));for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<=0)return i;}return weights.length-1;}
 private sectorIndex(p:Vector2State){const b=this.#battlefield.bounds,w=Math.max(1,b.maxX-b.minX),h=Math.max(1,b.maxY-b.minY),x=Math.max(0,Math.min(GRID-1,Math.floor(((p.x-b.minX)/w)*GRID))),y=Math.max(0,Math.min(GRID-1,Math.floor(((p.y-b.minY)/h)*GRID)));return y*GRID+x;}
 private sectorBounds(i:number){const b=this.#battlefield.bounds,w=(b.maxX-b.minX)/GRID,h=(b.maxY-b.minY)/GRID,x=i%GRID,y=Math.floor(i/GRID);return{minX:b.minX+x*w,maxX:b.minX+(x+1)*w,minY:b.minY+y*h,maxY:b.minY+(y+1)*h};}
 private sectorCenter(i:number):Vector2State{const b=this.sectorBounds(i);return{x:(b.minX+b.maxX)/2,y:(b.minY+b.maxY)/2};}
 private neighbors(i:number){const x=i%GRID,y=Math.floor(i/GRID),out:number[]=[];if(x>0)out.push(i-1);if(x<GRID-1)out.push(i+1);if(y>0)out.push(i-GRID);if(y<GRID-1)out.push(i+GRID);return out;}
}

export const LIVING_FRONT_BASELINE_COUNTS=Object.freeze({circle:62,triangle:30,square:16,pentagon:8,hexagon:4});
export const LIVING_FRONT_NORMAL_TARGET_TOTAL=NORMAL_TARGET_TOTAL;
export const LIVING_FRONT_BOUNTY_CAP=BOUNTY_CAP;
export const LIVING_FRONT_PLANNING_CADENCE=Object.freeze({sectorHz:5,behaviorHz:10,directorHz:2});
