export interface ReleaseRecord { readonly version:string; readonly title:string; readonly date:string; readonly summary:string; readonly family:string; }

/** Canonical replacement for the v1.7.9 Living Archive runtime panel. */
export const RELEASE_HISTORY: readonly ReleaseRecord[] = Object.freeze([
  {version:'1.11.0',title:'Living Front',date:'2026-08-12',family:'1.11',summary:'Neutral ecology turns farming, migration, predators and rare opportunities into one readable battlefield loop.'},
  {version:'1.10.9',title:'Visual Language',date:'2026-08-10',family:'1.10',summary:'Canonical visual-language pass and disciplined battlefield signals.'},
  {version:'1.10.8',title:'Applied Power Parity',date:'2026-08-10',family:'1.10',summary:'Rival power follows spent upgrades rather than banked points.'},
  {version:'1.10.7',title:'Second Body / Live Vector',date:'2026-08-10',family:'1.10',summary:'Controller logistics, recovery and live command-vector behavior.'},
  {version:'1.10.6',title:'Blackglass Mirror',date:'2026-08-10',family:'1.10',summary:'Blackglass mirrors the live tank, weapon and drone model.'},
  {version:'1.10.5',title:'Shared Battlefield View',date:'2026-08-10',family:'1.10',summary:'Player and AI share legitimate battlefield-position knowledge.'},
  {version:'1.10.3',title:'Drone Field Service',date:'2026-08-09',family:'1.10',summary:'Out-of-combat drone repair and visible field-service recovery.'},
  {version:'1.10.2',title:'Terrain Intelligence',date:'2026-08-09',family:'1.10',summary:'AI pathing and tactics understand battlefield terrain and breaches.'},
  {version:'1.10.1',title:'Lobby Battlefield',date:'2026-08-09',family:'1.10',summary:'The lobby War Room runs canonical combatants instead of decoration.'},
  {version:'1.9.3',title:'Spotter Comms',date:'2026-08-09',family:'1.9',summary:'Sniper observer relays communicate contact state and authorization.'},
  {version:'1.9.2',title:'Upgrade Dwell',date:'2026-08-09',family:'1.9',summary:'Upgrade surfaces preserve deliberate readable decision time.'},
  {version:'1.9.1',title:'Impact Language',date:'2026-08-09',family:'1.9',summary:'Restrained semantic impact, damage and sensory feedback.'},
  {version:'1.9.0',title:'Visual Overhaul',date:'2026-08-09',family:'1.9',summary:'Battlefield readability and combat presentation overhaul.'},
  {version:'1.8.3',title:'Precision Contact',date:'2026-08-09',family:'1.8',summary:'Sharper precision-weapon contact and execution semantics.'},
  {version:'1.8.2',title:'Tactical Framing',date:'2026-08-09',family:'1.8',summary:'Tactical control and combat framing refinements.'},
  {version:'1.8.1',title:'Battle Sense',date:'2026-08-09',family:'1.8',summary:'AI threat awareness and tactical battlefield reasoning.'},
  {version:'1.8.0',title:'Predator Doctrine',date:'2026-08-09',family:'1.8',summary:'Fair-play tactical AI doctrine across combat lineages.'},
  {version:'1.7.9',title:'Fieldcraft / Living Archive',date:'2026-08-08',family:'1.7',summary:'Fifty tactical tips and a living release-history surface.'},
  {version:'1.7.8',title:'Performance & Pilot Console',date:'2026-08-08',family:'1.7',summary:'Performance hardening, fair-play input settings and menu diagnostics.'},
  {version:'1.7.6',title:'Drone Allegiance Glow',date:'2026-08-08',family:'1.7',summary:'Subtle blue/red IFF halos make drone allegiance legible.'},
  {version:'1.7.3',title:'Showroom Fit',date:'2026-08-08',family:'1.7',summary:'Blackglass/showroom containment and layout fit.'},
  {version:'1.7.2',title:'Combined Arms',date:'2026-08-08',family:'1.7',summary:'Battlefield, disciplines and AI become one combined-arms system.'},
  {version:'1.7.1',title:'Apex Disciplines',date:'2026-08-08',family:'1.7',summary:'Apex forms gain mastery-sidegrade doctrine.'},
  {version:'1.7.0',title:'Three Disciplines',date:'2026-08-08',family:'1.7',summary:'Gunner, Cannon and Guardian discipline mechanics formalized.'},
  {version:'1.6.0',title:'Battlefield',date:'2026-08-07',family:'1.6',summary:'Three tactical layouts, destructible cover and persistent rubble.'},
  {version:'1.5.1',title:'Drone Discipline',date:'2026-08-07',family:'1.5',summary:'Drone control, targeting, spotters, UI and lobby music refinement.'},
  {version:'1.5.0',title:'Showroom',date:'2026-08-07',family:'1.5',summary:'Interactive class and lineage showroom arrives.'},
  {version:'1.4.1',title:'Sniper Lineage',date:'2026-08-07',family:'1.4',summary:'Expanded sniper lineage and precision identity.'},
  {version:'1.4.0',title:'Stability',date:'2026-08-07',family:'1.4',summary:'Runtime and gameplay stability hardening.'},
  {version:'1.3.0',title:'Controller',date:'2026-08-07',family:'1.3',summary:'Controller lineage and drone command identity introduced.'},
  {version:'1.2.0',title:'Sniper',date:'2026-08-07',family:'1.2',summary:'Sniper lineage begins the post-prototype class expansion.'},
]);
export const LATEST_RELEASE = RELEASE_HISTORY[0];
