/* NOVA TANKS v1.10.3 — Field Service
 * Universal slow out-of-combat repair for surviving non-Controller drones.
 * Terrain Intelligence owns routing; Command Weave keeps the Controller lineage's faster repair advantage.
 */
(function(){
'use strict';
if(window.__NOVA_FIELD_SERVICE__)return;
var mods=window.__novaModules;if(!mods){console.error('[NOVA v1.10.3] module registry unavailable');return;}
var VERSION='1.10.3',CODENAME='Field Service';
var CONTROLLER={carrier:1,overlord:1,warden:1,hivemind:1,broodmother:1,citadel:1,valkyrie:1};
var REPAIR_DELAY=4.6,REPAIR_RATE=.045,THREAT_INTERVAL=.34,PROJECTILE_INTERVAL=.12,THREAT_RADIUS=310,PROJECTILE_HORIZON=.38,PROJECTILE_CLEARANCE=26;
window.__NOVA_VERSION=VERSION;
window.__NOVA_FIELD_SERVICE_RELEASE__={version:VERSION,codename:CODENAME,date:'2026-08-09',headline:'Drones that survive a fight can recover for the next one instead of carrying chip damage forever.',groups:{
 'Field Repair':['Every surviving non-Controller drone slowly repairs after 4.6 seconds without taking damage, but only after nearby visible hostility and genuinely incoming hostile fire have cleared.','Fresh damage, a committed attack phase, active weapon recovery, or a hostile projectile already on an intercept course immediately prevents repair.','Controller drones stay on Command Weave\'s faster logistics path, preserving the lineage advantage requested for dedicated swarm commanders.'],
 'Readability':['Actual healing emits sparse mint service particles and a soft ring; healthy drones never carry a permanent repair effect.','Two tactical Tips explain the repair break and the Controller recycling advantage without turning healing into another HUD panel.'],
 'Performance and Ownership':['Healthy drones exit before any threat work. Damaged repair candidates refresh nearby-unit danger on a staggered interval, while incoming-projectile danger gets a tighter bounded refresh so fresh fire interrupts healing promptly.','Projectile danger uses a bounded closest-approach check over less than half a second; friendly, departing, blocked and wide-miss shots do not suppress repair.','Terrain Intelligence remains the sole advanced routing owner; Field Service does not steer, teleport, replan, or modify drone targets.']
}};
function wrap(id,after){var old=mods[id];if(!old)return;mods[id]=function(module,exports,require){old(module,exports,require);after(module.exports,require);};}
function now(g){return g&&Number.isFinite(g.time)?g.time:0;}
function isController(t){return !!(t&&CONTROLLER[t.cls]);}
function ownerOf(g,d){if(!g||!d)return null;if(g.tankById&&g.tankById.get)return g.tankById.get(d.ownerId)||null;if(g.getTank)return g.getTank(d.ownerId)||null;return null;}
function stateFor(g,d){var hp=Math.max(0,Number(d.hp)||0),declared=Math.max(0,Number(d.maxHp)||0),s=d.__novaFieldService;if(!s)s=d.__novaFieldService={maxHp:Math.max(hp,declared),lastDamageAt:-99,nextThreatAt:0,threat:false,nextProjectileAt:0,projectileThreat:false,fxAt:0};if(declared>s.maxHp)s.maxHp=declared;if(hp>s.maxHp)s.maxHp=hp;return s;}
function relationHostile(g,owner,t,requireAlive){if(!owner||!t||t.id===owner.id||(requireAlive&&t.alive===false))return false;if(typeof g.areAllies==='function'&&g.areAllies(owner,t))return false;if(typeof g.areHostile==='function')return !!g.areHostile(owner,t);var keys=['teamId','team','factionId','faction','side'];for(var i=0;i<keys.length;i++){var k=keys[i];if(owner[k]!=null&&t[k]!=null)return owner[k]!==t[k];}return true;}
function hostile(g,owner,t){return relationHostile(g,owner,t,true);}
function projectileHostile(g,owner,t){return relationHostile(g,owner,t,false);}
function lineClear(g,ax,ay,bx,by){return !g.hasLineOfSight||g.hasLineOfSight(ax,ay,bx,by,2);}
function projectileThreat(g,d,owner){var bs=g.bullets||[],clear=Math.max(8,Number(d.r)||8)+PROJECTILE_CLEARANCE,clear2=clear*clear;for(var i=0;i<bs.length;i++){var b=bs[i];if(!b||b.dead||b.alive===false)continue;if(b.ownerId===owner.id||b.ownerId===d.id)continue;var shotOwner=ownerOf(g,b);if(!shotOwner||!projectileHostile(g,owner,shotOwner))continue;var dx=(Number(b.x)||0)-d.x,dy=(Number(b.y)||0)-d.y;if(dx*dx+dy*dy<=clear2&&lineClear(g,d.x,d.y,b.x,b.y))return true;var vx=Number(b.vx)||0,vy=Number(b.vy)||0,v2=vx*vx+vy*vy;if(v2<1)continue;var t=-(dx*vx+dy*vy)/v2;if(t<=0||t>PROJECTILE_HORIZON)continue;var cx=dx+vx*t,cy=dy+vy*t;if(cx*cx+cy*cy<=clear2&&lineClear(g,d.x,d.y,b.x,b.y))return true;}return false;}
function visibleThreat(g,d,owner){var r2=THREAT_RADIUS*THREAT_RADIUS,ts=g.tanks||[],i,t,dx,dy;for(i=0;i<ts.length;i++){t=ts[i];if(!hostile(g,owner,t))continue;dx=t.x-d.x;dy=t.y-d.y;if(dx*dx+dy*dy<=r2&&lineClear(g,d.x,d.y,t.x,t.y))return true;}var ds=g.drones||[];for(i=0;i<ds.length;i++){t=ds[i];if(!t||t===d||t.hp<=0||t.ownerId===d.ownerId)continue;var other=ownerOf(g,t);if(!other||!hostile(g,owner,other))continue;dx=t.x-d.x;dy=t.y-d.y;if(dx*dx+dy*dy<=r2&&lineClear(g,d.x,d.y,t.x,t.y))return true;}return false;}
function committed(d){return !!(d&&(d.__novaPhase==='dash'||d.__novaPhase==='windup'||d.__novaCommitted));}
function canRepair(g,d,owner,s){if(!d||d.hp<=0||!owner||owner.alive===false||isController(owner))return false;var max=Math.max(s.maxHp,Number(d.maxHp)||0);if(max<=0||d.hp>=max-.01)return false;if(committed(d)||(d.attackCd||0)>.05)return false;var tm=now(g);if(tm-s.lastDamageAt<REPAIR_DELAY)return false;if(tm>=s.nextThreatAt){s.nextThreatAt=tm+THREAT_INTERVAL+((Math.abs(Number(d.id)||0)%5)*.017);s.threat=visibleThreat(g,d,owner);}if(s.threat)return false;if(tm>=s.nextProjectileAt){s.nextProjectileAt=tm+PROJECTILE_INTERVAL+((Math.abs(Number(d.id)||0)%3)*.009);s.projectileThreat=projectileThreat(g,d,owner);}return !s.projectileThreat;}
function heal(g,d,s,dt){var max=Math.max(s.maxHp,Number(d.maxHp)||0),before=d.hp;d.hp=Math.min(max,d.hp+max*REPAIR_RATE*Math.max(0,Number(dt)||0));if(d.hp<=before+.0001)return false;var tm=now(g);if(tm>=s.fxAt){s.fxAt=tm+.38+((Math.abs(Number(d.id)||0)%3)*.025);if(g.addParticles)g.addParticles(d.x,d.y,'#8fffd0',2,22,'glow');if(g.addRing)g.addRing(d.x,d.y,'#8fffd0',8);}return true;}
function registerTips(){var api=window.NOVATips;if(!api||typeof api.registerMany!=='function'||window.__NOVA_FIELD_SERVICE_TIPS__)return;window.__NOVA_FIELD_SERVICE_TIPS__=true;api.registerMany([
 {id:'drone-field-repair',contexts:['gameplay','controller'],text:'A damaged drone self-repairs only after combat genuinely breaks. Fresh damage, nearby visible hostility, or incoming fire resets the recovery window.',reviewed:'2026-08-17'},
 {id:'controller-repair-advantage',contexts:['gameplay','controller'],text:'Controller drones recycle much faster than ordinary drones. Pull damaged hunters out before the screen collapses instead of trading every hull to zero.',reviewed:'2026-08-09'}
]);}
wrap('game/engine',function(engine){var Game=engine.Game;if(!Game||Game.prototype.__novaFieldService)return;Game.prototype.__novaFieldService=true;var oldDamage=Game.prototype.damageDrone;if(oldDamage)Game.prototype.damageDrone=function(d){var before=d?Number(d.hp)||0:0,s=d?stateFor(this,d):null,out=oldDamage.apply(this,arguments);if(d&&s&&(Number(d.hp)||0)<before-.001){s.lastDamageAt=now(this);s.threat=true;s.projectileThreat=true;s.nextThreatAt=now(this)+THREAT_INTERVAL;s.nextProjectileAt=now(this)+PROJECTILE_INTERVAL;}return out;};var oldUpdate=Game.prototype.updateDrones;if(oldUpdate)Game.prototype.updateDrones=function(dt){var out=oldUpdate.apply(this,arguments),ds=this.drones||[];for(var i=0;i<ds.length;i++){var d=ds[i];if(!d||d.hp<=0)continue;var s=stateFor(this,d),owner=ownerOf(this,d);if(canRepair(this,d,owner,s))heal(this,d,s,dt);}registerTips();return out;};});
registerTips();
window.__NOVA_FIELD_SERVICE__={version:VERSION,codename:CODENAME,repairDelay:REPAIR_DELAY,repairRate:REPAIR_RATE,controllerUsesCommandWeave:true,routingOwner:'Terrain Intelligence',projectileHorizon:PROJECTILE_HORIZON,projectileInterval:PROJECTILE_INTERVAL};
window.__NOVA_FIELD_SERVICE_TEST__={isController:isController,stateFor:stateFor,visibleThreat:visibleThreat,projectileThreat:projectileThreat,projectileHostile:projectileHostile,committed:committed,canRepair:canRepair,heal:heal,repairDelay:REPAIR_DELAY,repairRate:REPAIR_RATE,threatRadius:THREAT_RADIUS,projectileHorizon:PROJECTILE_HORIZON,projectileInterval:PROJECTILE_INTERVAL};
console.info('[NOVA TANKS] v'+VERSION+' '+CODENAME+' drone repair online');
})();
