/* NOVA TANKS v1.7.9 — Living Archive
 * Makes release history part of the lobby instead of a hidden utility action.
 * The newest release is always visible; the full archive expands into a scrollable timeline.
 */
(function(){
'use strict';
var VERSION='1.7.9',CODENAME='Living Archive';
var archiveData=[],archiveOverlay=null,menuObserver=null,applyQueued=false;
window.__NOVA_VERSION=VERSION;
window.__NOVA_LIVING_ARCHIVE_RELEASE__={
 version:VERSION,codename:CODENAME,date:'2026-08-08',
 headline:'The lobby carries its own living release lineage instead of hiding history behind a utility button.',
 groups:{
  'Living Archive':['The newest release is permanently visible in the lobby with its codename, headline and version-family accent.','Expanding the card opens a vertically scrollable archive containing every known release post, newest first.','Release colors are hierarchical: a major version owns a hue family, minor versions are tonal branches, and patch releases are distinct variations inside that branch.'],
  'Lobby Life':['Ambient signal motes, soft grid drift, status pulses and richer surface lighting give the launch bay motion without stealing attention from Deploy.','Primary navigation is simplified to Blackglass, Controls and Debug because release history now lives directly in the lobby.','The archive remains mutually exclusive with other deep menu surfaces and respects reduced-motion preferences.']
 }
};
function css(){
 if(document.getElementById('nova-living-archive-css'))return;
 var s=document.createElement('style');s.id='nova-living-archive-css';s.textContent=`
.menu-grid-bg.nv-menu{position:relative!important;background-color:#04060d!important;background-image:radial-gradient(circle at 50% 14%,rgba(43,176,255,.11),transparent 34%),radial-gradient(circle at 12% 72%,rgba(176,107,255,.07),transparent 30%),linear-gradient(rgba(70,130,220,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(70,130,220,.07) 1px,transparent 1px)!important;background-size:auto,auto,44px 44px,44px 44px!important;animation:nvlGrid 18s linear infinite}.nv-shell{z-index:2}.nv-hero h1{text-shadow:0 0 28px rgba(77,227,255,.20),0 0 70px rgba(77,227,255,.07)}.nv-hero>div:first-child{filter:drop-shadow(0 0 8px rgba(77,227,255,.22))}.nv-primary>button{border:1px solid rgba(170,244,255,.34)!important;box-shadow:0 0 32px rgba(45,205,255,.22),0 10px 28px rgba(0,0,0,.42),inset 0 1px rgba(255,255,255,.72)!important}.nv-primary>button:hover{filter:brightness(1.05)}
.nv-action-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}.nv-action{position:relative;overflow:hidden;background:linear-gradient(150deg,rgba(20,39,67,.92),rgba(5,10,22,.96))!important;border-color:rgba(127,209,255,.18)!important;box-shadow:inset 0 1px rgba(255,255,255,.035),0 8px 24px rgba(0,0,0,.12)}.nv-action:before{content:'';position:absolute;inset:0;background:linear-gradient(105deg,transparent 32%,rgba(132,231,255,.055),transparent 68%);transform:translateX(-100%);transition:transform .45s ease}.nv-action:hover:before,.nv-action.on:before{transform:translateX(100%)}.nv-action.on{border-color:rgba(125,243,255,.48)!important;box-shadow:0 0 20px rgba(77,227,255,.12),inset 0 1px rgba(255,255,255,.06)!important}
.nv-brief{position:relative;overflow:hidden!important;background:linear-gradient(110deg,rgba(12,35,58,.78),rgba(5,9,20,.88))!important;box-shadow:inset 0 1px rgba(255,255,255,.035),0 8px 24px rgba(0,0,0,.10)}.nv-brief:after{content:'';position:absolute;left:-25%;right:-25%;top:0;height:1px;background:linear-gradient(90deg,transparent,rgba(125,243,255,.38),transparent);animation:nvlScan 5.6s ease-in-out infinite}
.nvl-ambience{position:absolute;inset:0;z-index:0;overflow:hidden;pointer-events:none}.nvl-ambience:before,.nvl-ambience:after{content:'';position:absolute;border-radius:50%;filter:blur(28px);opacity:.24;animation:nvlBreath 7s ease-in-out infinite}.nvl-ambience:before{width:180px;height:180px;left:-80px;top:28%;background:#1e96ff}.nvl-ambience:after{width:220px;height:220px;right:-120px;bottom:10%;background:#794dff;animation-delay:-3.1s}.nvl-mote{position:absolute;width:2px;height:2px;border-radius:50%;background:#9befff;box-shadow:0 0 8px #55dfff;opacity:.25;animation:nvlMote var(--dur) linear infinite;animation-delay:var(--delay)}
.nvl-latest{position:relative;z-index:3;width:min(100%,590px);box-sizing:border-box;margin-top:clamp(5px,1.1vh,8px);padding:0;border:1px solid color-mix(in srgb,var(--rel,#7df3ff) 42%,transparent);border-radius:13px;background:linear-gradient(120deg,color-mix(in srgb,var(--rel,#7df3ff) 9%,#0b1424 91%),rgba(5,9,18,.94));box-shadow:0 10px 30px rgba(0,0,0,.16),inset 0 1px rgba(255,255,255,.04);overflow:hidden;text-align:left;color:#edf8ff;touch-action:manipulation;transition:transform .16s ease,border-color .18s ease,box-shadow .18s ease}.nvl-latest:hover{transform:translateY(-1px);border-color:color-mix(in srgb,var(--rel,#7df3ff) 68%,transparent);box-shadow:0 12px 34px rgba(0,0,0,.2),0 0 22px color-mix(in srgb,var(--rel,#7df3ff) 11%,transparent)}.nvl-latest:active{transform:scale(.992)}.nvl-latest:before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--rel,#7df3ff);box-shadow:0 0 15px var(--rel,#7df3ff)}.nvl-latest:after{content:'';position:absolute;width:120px;height:120px;border-radius:50%;right:-55px;top:-70px;background:var(--rel,#7df3ff);filter:blur(38px);opacity:.08;pointer-events:none}.nvl-latest-inner{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;padding:clamp(7px,1.2vh,10px) 12px}.nvl-live-dot{width:7px;height:7px;border-radius:50%;background:var(--rel,#7df3ff);box-shadow:0 0 11px var(--rel,#7df3ff);animation:nvlPulse 2s ease-in-out infinite}.nvl-latest-copy{min-width:0}.nvl-kicker{font:900 7px Orbitron,system-ui;letter-spacing:.15em;color:var(--rel,#7df3ff)}.nvl-title{display:flex;align-items:baseline;gap:7px;margin-top:2px;min-width:0}.nvl-version{font:900 clamp(9px,1.45vh,11px) Orbitron,system-ui;color:#f3fbff;white-space:nowrap}.nvl-codename{font:800 clamp(10px,1.7vh,12px) Rajdhani,system-ui;color:#c9d9e9;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nvl-headline{margin-top:2px;font:600 clamp(8px,1.35vh,9.5px)/1.15 Rajdhani,system-ui;color:#7890aa;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nvl-expand{display:flex;align-items:center;gap:6px;font:900 7px Orbitron,system-ui;letter-spacing:.09em;color:#a9c9df;white-space:nowrap}.nvl-expand span{font-size:13px;color:var(--rel,#7df3ff);transition:transform .18s ease}.nvl-latest:hover .nvl-expand span{transform:translateX(2px)}
.nvl-archive-overlay{position:fixed;inset:0;z-index:10030;display:flex;align-items:center;justify-content:center;padding:max(12px,env(safe-area-inset-top)) 12px max(12px,env(safe-area-inset-bottom));background:rgba(1,3,9,.91);backdrop-filter:blur(14px);touch-action:none;animation:nvlFade .18s ease both}.nvl-archive{position:relative;display:flex;flex-direction:column;width:min(700px,100%);height:min(760px,calc(100vh - 24px));border:1px solid rgba(130,215,255,.26);border-radius:18px;background:linear-gradient(160deg,rgba(12,20,39,.99),rgba(3,6,13,.995));box-shadow:0 30px 90px rgba(0,0,0,.58),inset 0 1px rgba(255,255,255,.045);overflow:hidden;animation:nvlPanel .28s cubic-bezier(.2,.84,.2,1) both}.nvl-archive-head{flex:none;padding:16px 54px 12px 16px;border-bottom:1px solid rgba(255,255,255,.07);background:linear-gradient(180deg,rgba(21,42,69,.54),rgba(7,11,22,.16))}.nvl-archive-title{font:900 14px Orbitron,system-ui;letter-spacing:.17em;color:#e8faff}.nvl-archive-sub{margin-top:4px;font:600 10px Rajdhani,system-ui;color:#71839a}.nvl-close{position:absolute;right:12px;top:12px;z-index:2;width:34px;height:34px;border:1px solid rgba(255,255,255,.13);border-radius:10px;background:rgba(255,255,255,.04);color:#c9d5e4;font-size:20px}.nvl-stream{flex:1;min-height:0;overflow-y:auto;overscroll-behavior:contain;touch-action:pan-y;padding:12px 12px 20px;scrollbar-width:thin;scrollbar-color:#31536d transparent}.nvl-stream::-webkit-scrollbar{width:5px}.nvl-stream::-webkit-scrollbar-thumb{background:#31536d;border-radius:9px}.nvl-release{--rel:#7df3ff;position:relative;margin:0 0 9px;padding:12px 13px 12px 16px;border:1px solid color-mix(in srgb,var(--rel) 32%,transparent);border-radius:13px;background:linear-gradient(125deg,color-mix(in srgb,var(--rel) 7%,#09111f 93%),rgba(5,8,16,.95));overflow:hidden;box-shadow:inset 0 1px rgba(255,255,255,.025)}.nvl-release:before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--rel);box-shadow:0 0 14px var(--rel)}.nvl-release-top{display:flex;align-items:center;gap:8px;min-width:0}.nvl-rel-ver{font:900 9px Orbitron,system-ui;letter-spacing:.08em;color:var(--rel);white-space:nowrap}.nvl-rel-name{font:800 12px Rajdhani,system-ui;color:#e5edf7;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nvl-rel-date{margin-left:auto;font:700 8px Orbitron,system-ui;color:#4e6077;white-space:nowrap}.nvl-rel-head{margin-top:5px;font:650 10px/1.25 Rajdhani,system-ui;color:#9caec2}.nvl-group{margin-top:9px}.nvl-group-name{font:900 7px Orbitron,system-ui;letter-spacing:.12em;color:color-mix(in srgb,var(--rel) 72%,#d8f7ff)}.nvl-items{margin:4px 0 0;padding-left:16px;font:600 9.5px/1.28 Rajdhani,system-ui;color:#bcc9d8}.nvl-items li{margin:3px 0}.nvl-family{display:inline-flex;margin-left:6px;padding:2px 5px;border:1px solid color-mix(in srgb,var(--rel) 30%,transparent);border-radius:999px;font:800 6px Orbitron,system-ui;letter-spacing:.08em;color:color-mix(in srgb,var(--rel) 78%,white)}
@keyframes nvlGrid{to{background-position:0 0,0 0,44px 44px,44px 44px}}@keyframes nvlScan{0%,62%{transform:translateX(-80%);opacity:0}74%{opacity:1}92%,100%{transform:translateX(80%);opacity:0}}@keyframes nvlBreath{50%{transform:scale(1.12);opacity:.34}}@keyframes nvlMote{0%{transform:translate3d(0,24px,0);opacity:0}12%{opacity:.28}80%{opacity:.18}100%{transform:translate3d(var(--drift),-105vh,0);opacity:0}}@keyframes nvlPulse{50%{opacity:.35;transform:scale(.78)}}@keyframes nvlFade{from{opacity:0}to{opacity:1}}@keyframes nvlPanel{from{opacity:0;transform:translateY(8px) scale(.992)}to{opacity:1;transform:none}}
@media(max-width:470px){.nvl-latest-inner{grid-template-columns:auto 1fr;padding-left:10px}.nvl-expand{grid-column:2;margin-top:-1px}.nvl-headline{display:none}.nvl-archive{border-radius:15px}.nvl-stream{padding:9px}.nvl-release{padding:10px 10px 10px 14px}.nvl-rel-date{display:none}}
@media(max-height:610px){.nvl-latest{margin-top:4px}.nvl-latest-inner{padding-top:5px;padding-bottom:5px}.nvl-headline{display:none}.nvl-kicker{font-size:6px}.nvl-archive-head{padding-top:10px;padding-bottom:8px}.nvl-release{padding-top:8px;padding-bottom:8px}.nvl-items{font-size:8.5px}}
@media(max-height:520px){.nvl-latest .nvl-codename{max-width:150px}.nvl-expand{display:none}}
@media(prefers-reduced-motion:reduce){.menu-grid-bg.nv-menu,.nvl-ambience:before,.nvl-ambience:after,.nvl-mote,.nv-brief:after,.nvl-live-dot,.nvl-archive-overlay,.nvl-archive{animation:none!important}.nvl-latest,.nvl-expand span{transition:none!important}}
`;
 document.head.appendChild(s);
}
function parts(v){var p=String(v||'0').split('.').map(function(x){return parseInt(x,10)||0});return[p[0]||0,p[1]||0,p[2]||0]}
function cmp(a,b){a=parts(a);b=parts(b);for(var i=0;i<3;i++){if(a[i]!==b[i])return a[i]-b[i]}return 0}
function hash(s){var h=0;s=String(s||'');for(var i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h)}
function colorFor(version,salt){var p=parts(version),major=p[0],minor=p[1],patch=p[2];var majorHue=(192+(Math.max(0,major-1)*71))%360;var minorShift=((minor%7)-3)*1.35;var patchShift=((patch%5)-2)*.8;var h=(majorHue+minorShift+patchShift+360)%360;var sat=74+((minor*3)%10);var light=58+((patch*4+hash(salt)%7)%15);return'hsl('+h.toFixed(1)+' '+sat+'% '+light+'%)'}
function normalize(r){if(!r||!r.version)return null;var groups={};if(r.groups&&typeof r.groups==='object')Object.keys(r.groups).forEach(function(k){if(Array.isArray(r.groups[k]))groups[k]=r.groups[k].slice()});if(!Object.keys(groups).length&&Array.isArray(r.guarantees))groups.Guarantees=r.guarantees.slice();if(!Object.keys(groups).length&&Array.isArray(r.fairPlay))groups['Fair Play']=r.fairPlay.slice();return{version:String(r.version),codename:String(r.codename||'Untitled Release'),date:String(r.date||''),headline:String(r.headline||''),groups:groups}}
function collectGlobals(list){Object.keys(window).forEach(function(k){if(k.indexOf('__NOVA_')!==0)return;var r=normalize(window[k]);if(r)list.push(r)});var pilot=normalize(window.__NOVA_PILOT_CONSOLE__);if(pilot)list.push(pilot)}
function dedupe(list){var out=[],seen={};list.forEach(function(r){r=normalize(r);if(!r)return;var key=r.version+'|'+r.codename;if(seen[key])return;seen[key]=1;out.push(r)});out.sort(function(a,b){var d=cmp(b.version,a.version);if(d)return d;return String(b.date).localeCompare(String(a.date))});return out}
function gather(done){var list=[];collectGlobals(list);fetch('./nova-updates/releases.json',{cache:'no-store'}).then(function(r){return r.ok?r.json():{releases:[]}}).then(function(j){(j.releases||[]).forEach(function(r){list.push(r)});archiveData=dedupe(list);done()}).catch(function(){archiveData=dedupe(list);done()})}
function menu(){return document.querySelector('#root .menu-grid-bg')}
function slot(name){var m=menu();return m&&m.querySelector('[data-nova-slot="'+name+'"]')}
function latest(){return archiveData[0]||normalize(window.__NOVA_LIVING_ARCHIVE_RELEASE__)}
function updaterLabel(){var st=window.__NOVA_UPDATE_STATUS||{};if(navigator.onLine===false)return'OFFLINE ARCHIVE';if(st.ok===false)return'UPDATE LINK DEGRADED';if(st.changed)return'NEW BUILD RECEIVED';return'LIVE BUILD'}
function closeOtherSurfaces(){
 var old=document.querySelector('.nv-history');if(old&&old.parentElement&&old.parentElement.classList.contains('nv-overlay'))old.parentElement.remove();
 var dbg=document.querySelector('.nv-debug-overlay');if(dbg)dbg.remove();
 var util=slot('utility');if(util)util.classList.remove('open');document.querySelectorAll('.nv-util-close').forEach(function(x){x.remove()});
 var m=menu(),intel=slot('intel');if(intel&&intel.classList.contains('nvs-open')){var l=intel.querySelector('.nvs-launch');if(l)l.click();else intel.classList.remove('nvs-open')}if(m){m.classList.remove('nv-showroom-mode');m.scrollTop=0}
 m&&m.querySelectorAll('.nv-action.on').forEach(function(b){b.classList.remove('on')});
}
function closeArchive(){if(archiveOverlay){archiveOverlay.remove();archiveOverlay=null}else{var e=document.querySelector('.nvl-archive-overlay');if(e)e.remove()}}
function releaseCard(r){var sec=document.createElement('section');var col=colorFor(r.version,r.codename);sec.className='nvl-release';sec.style.setProperty('--rel',col);var p=parts(r.version);sec.innerHTML='<div class="nvl-release-top"><span class="nvl-rel-ver"></span><span class="nvl-family"></span><span class="nvl-rel-name"></span><span class="nvl-rel-date"></span></div><div class="nvl-rel-head"></div>';sec.querySelector('.nvl-rel-ver').textContent='v'+r.version;sec.querySelector('.nvl-family').textContent=p[0]+'.'+p[1]+' FAMILY';sec.querySelector('.nvl-rel-name').textContent=r.codename;sec.querySelector('.nvl-rel-date').textContent=r.date;sec.querySelector('.nvl-rel-head').textContent=r.headline;Object.keys(r.groups||{}).forEach(function(g){var wrap=document.createElement('div');wrap.className='nvl-group';var name=document.createElement('div');name.className='nvl-group-name';name.textContent=g.toUpperCase();wrap.appendChild(name);var ul=document.createElement('ul');ul.className='nvl-items';(r.groups[g]||[]).forEach(function(x){var li=document.createElement('li');li.textContent=x;ul.appendChild(li)});wrap.appendChild(ul);sec.appendChild(wrap)});return sec}
function openArchive(){if(archiveOverlay)return closeArchive();closeOtherSurfaces();archiveOverlay=document.createElement('div');archiveOverlay.className='nvl-archive-overlay';var box=document.createElement('div');box.className='nvl-archive';box.onclick=function(e){e.stopPropagation()};box.innerHTML='<button class="nvl-close" aria-label="Close version history">×</button><div class="nvl-archive-head"><div class="nvl-archive-title">VERSION ARCHIVE</div><div class="nvl-archive-sub"></div></div><div class="nvl-stream"></div>';box.querySelector('.nvl-archive-sub').textContent=archiveData.length+' release posts · newest first · color follows version lineage';box.querySelector('.nvl-close').onclick=closeArchive;var stream=box.querySelector('.nvl-stream');archiveData.forEach(function(r){stream.appendChild(releaseCard(r))});archiveOverlay.onclick=closeArchive;archiveOverlay.appendChild(box);document.body.appendChild(archiveOverlay)}
function ambience(m){if(m.querySelector('.nvl-ambience'))return;var a=document.createElement('div');a.className='nvl-ambience';for(var i=0;i<14;i++){var s=document.createElement('span');s.className='nvl-mote';s.style.left=(5+((i*37)%91))+'%';s.style.top=(62+((i*19)%42))+'%';s.style.setProperty('--dur',(12+(i%6)*2.3)+'s');s.style.setProperty('--delay',(-i*1.7)+'s');s.style.setProperty('--drift',(((i%5)-2)*18)+'px');a.appendChild(s)}m.insertBefore(a,m.firstChild)}
function buildLatest(m){var r=latest();if(!r)return;var existing=m.querySelector('.nvl-latest'),acts=slot('actions');if(!acts)return;if(!existing){existing=document.createElement('button');existing.type='button';existing.className='nvl-latest';existing.dataset.novaSlot='latest-release';existing.innerHTML='<div class="nvl-latest-inner"><span class="nvl-live-dot"></span><div class="nvl-latest-copy"><div class="nvl-kicker"></div><div class="nvl-title"><span class="nvl-version"></span><span class="nvl-codename"></span></div><div class="nvl-headline"></div></div><div class="nvl-expand">OPEN ARCHIVE <span>›</span></div></div>';existing.onclick=openArchive;acts.insertAdjacentElement('afterend',existing)}var col=colorFor(r.version,r.codename);existing.style.setProperty('--rel',col);existing.querySelector('.nvl-kicker').textContent=updaterLabel()+' · LATEST TRANSMISSION';existing.querySelector('.nvl-version').textContent='v'+r.version;existing.querySelector('.nvl-codename').textContent=r.codename;existing.querySelector('.nvl-headline').textContent=r.headline}
function simplifyActions(m){var up=m.querySelector('[data-nova-action="updates"]');if(up)up.style.display='none';var grid=m.querySelector('.nv-action-grid');if(grid)grid.style.gridTemplateColumns='repeat(3,minmax(0,1fr))'}
function enrich(m){css();ambience(m);simplifyActions(m);buildLatest(m);if(!m.dataset.nvlExclusive){m.dataset.nvlExclusive='1';m.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('[data-nova-action]');if(b&&archiveOverlay)closeArchive()},true)}}
function apply(){applyQueued=false;var m=menu();if(!m)return;enrich(m)}
function schedule(){if(applyQueued)return;applyQueued=true;requestAnimationFrame(apply)}
function start(){gather(function(){schedule()});var root=document.getElementById('root');if(root){menuObserver=new MutationObserver(schedule);menuObserver.observe(root,{childList:true,subtree:true})}window.addEventListener('online',schedule);window.addEventListener('offline',schedule)}
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&archiveOverlay){e.stopImmediatePropagation();closeArchive()}},true);
window.__NOVA_LIVING_ARCHIVE_TEST__={parts:parts,colorFor:colorFor,dedupe:dedupe,normalize:normalize,version:VERSION};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
