/* NOVA TANKS v1.12.0 — Living Front / Stage III: Front Director + Strategic AI */
(function(){'use strict';
var LF=window.__NOVA_LIVING_FRONT_INTERNAL__,mods=window.__novaModules;if(!LF||!mods||!LF.instincts){console.error('[NOVA v1.12.0] Living Front stages missing');return;}if(window.__NOVA_LIVING_FRONT__)return;
var V=LF.VERSION,clamp=LF.clamp,d2=LF.d2,alive=LF.alive,xp=LF.xp,sectorCenter=LF.sectorCenter,sectorIndex=LF.sectorIndex;
var REJECTED=['convoys','reactors','supply beacons','extraction','crafting currency','factions','reputation','shape breeding','deep food chain','multiple Crasher species','random shape stat mutations','quests','daily objectives','XP multiplier zones','class ecology trees','new controls'];
var TIP_DEFS=[
 {id:'living-front-quiet-maturity',text:'Quiet ground matures. If a lane has been ignored, its next harvest may be worth the rotation.',tags:['battlefield','economy','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'},
 {id:'living-front-hex-keystone',text:'A Hexagon is more than 200 XP: undisturbed ones tend to gather a loose pocket of prey around themselves.',tags:['battlefield','economy','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'},
 {id:'living-front-triangle-evade',text:'Triangles get one committed evade, not infinite dodges. Bait the sidestep, then place the follow-up shot.',tags:['combat','aim','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'},
 {id:'living-front-crasher-bounty',text:'A bright Crasher core means stored bounty, not extra damage. Its charge still has the same readable commitment.',tags:['combat','economy','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'},
 {id:'living-front-bloom-choice',text:'BLOOM reports value that already exists. You can harvest it, ambush the approach, or let everyone else leave another lane empty.',tags:['battlefield','economy','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'},
 {id:'living-front-star-intercept',text:'Rogue Stars reward interception. Cut the route instead of chasing directly from behind.',tags:['battlefield','combat','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'},
 {id:'living-front-herding',text:'Explosions and near fire can herd skittish prey, but repeated disturbance quickly loses efficiency and depletes the lane.',tags:['battlefield','economy','living-front'],reviewed:'2026-08-30',source:'living-front-v1.12.0'}
];
var TIPS=TIP_DEFS.map(function(t){return t.text;});
function mean(st){var n=0;for(var i=0;i<16;i++)n+=st.sectors[i].value;return n/16;}
function bloomAgeEligible(st){return !!st&&LF.ageProgress(st)>=.15;}
function bloomCandidate(st){if(!bloomAgeEligible(st))return-1;var avg=mean(st),best=-1,score=0;for(var i=0;i<16;i++){var s=st.sectors[i],m=s.maturity/Math.max(.1,st.ceiling),v=s.value/(avg+1);if(s.value<310||m<.62||v<1.34)continue;var q=v*.72+m*.55-clamp(s.pressure,0,1)*.42;if(q>score){score=q;best=i;}}return best;}
function decision(st,ctx){if(ctx&&ctx.enabled===false)return null;var now=ctx&&ctx.now||0;if(st.signal&&now<st.signal.until)return null;if(now-st.lastSignalAt<8)return null;if(st.cooldowns.bloom<=0){var b=bloomCandidate(st);if(b>=0&&(b!==st.lastBloomSector||st.sectors[b].maturity>.78*st.ceiling))return{type:'BLOOM',sector:b};}if(st.cooldowns.migration<=0&&st.migrationHeat>=5){var from=ctx&&ctx.migrationFrom;if(from==null||from<0){var val=-1;for(var i=0;i<16;i++)if(st.sectors[i].outbound>val){val=st.sectors[i].outbound;from=i;}}if(from>=0){var m=Math.hypot(st.migrationX,st.migrationY)||1,c=sectorCenter(from),to=sectorIndex(c.x+st.migrationX/m*(LF.ARENA*2/LF.GRID)*.8,c.y+st.migrationY/m*(LF.ARENA*2/LF.GRID)*.8);if(to!==from)return{type:'MIGRATION',from:from,to:to};}}if(st.cooldowns.star<=0&&!(ctx&&ctx.hasStar)&&bloomCandidate(st)<0&&st.migrationHeat<3&&now>72&&now-st.lastMeaningfulAt>31)return{type:'ROGUE STAR'};return null;}
function setSignal(g,st,d){var now=g.time||0,sig={type:d.type,started:now,until:now+(d.type==='BLOOM'?5:d.type==='MIGRATION'?4.4:7)};if(d.type==='BLOOM'){sig.sector=d.sector;var c=sectorCenter(d.sector);sig.x=c.x;sig.y=c.y;st.cooldowns.bloom=24;st.lastBloomSector=d.sector;st.lastMeaningfulAt=now;st.stats.blooms++;}else if(d.type==='MIGRATION'){sig.from=d.from;sig.to=d.to;var a=sectorCenter(d.from),b=sectorCenter(d.to);sig.x=(a.x+b.x)/2;sig.y=(a.y+b.y)/2;st.cooldowns.migration=20;st.lastMeaningfulAt=now;st.stats.migrations++;st.migrationHeat*=.28;}else{st.cooldowns.star=58;var n=(g.shapes||[]).length;if(g.spawnShape)g.spawnShape('star',false);var s=(g.shapes||[])[(g.shapes||[]).length-1];if((g.shapes||[]).length<=n||!s||s.type!=='star')return;LF.initStar(g,st,s);sig.starId=s.id;sig.x=s.x;sig.y=s.y;st.lastMeaningfulAt=now;}st.signal=sig;st.lastSignal=d.type;st.lastSignalAt=now;if(g.toast)g.toast(d.type==='BLOOM'?'✦ SHAPE BLOOM · value has accumulated in quiet ground':d.type==='MIGRATION'?'⇢ MIGRATION · neutral population is moving':'★ ROGUE STAR · intercept the roaming prize','info');if(g.sfx&&g.sfx.novaLivingSignal)g.sfx.novaLivingSignal(d.type,g.player?clamp((sig.x-g.player.x)/900,-1,1):0);}
LF.directorTick=function(g,st){var t0=LF.ms(),hasStar=false,sh=g.shapes||[];for(var i=0;i<sh.length;i++)if(sh[i]&&sh[i].hp>0&&sh[i].type==='star'){hasStar=true;break;}if(st.signal&&st.signal.type==='ROGUE STAR'&&st.signal.starId&&g.getShape&&!g.getShape(st.signal.starId))st.signal=null;var d=decision(st,{enabled:st.directorEnabled,now:g.time||0,hasStar:hasStar});if(d)setSignal(g,st,d);if(st.signal&&(g.time||0)>=st.signal.until)st.signal=null;LF.planSample(st,LF.ms()-t0);};
function visible(g,t,s){var F=window.__NOVA_FAIR_ENGAGEMENT_TEST__;var inView=F&&F.inGameplayViewport?F.inGameplayViewport(g,t,s):(function(){var z=(g.cam&&g.cam.zoom)||1,hx=(g.w||800)/(2*z),hy=(g.h||600)/(2*z);return Math.abs(s.x-t.x)<=hx&&Math.abs(s.y-t.y)<=hy;})();return !!inView&&(!g.hasLineOfSight||g.hasLineOfSight(t.x,t.y,s.x,s.y,2));}
function saturation(g,key,id){var n=0,ts=g.tanks||[];for(var i=0;i<ts.length;i++){var q=ts[i];if(q&&q.id!==id&&q.ai&&alive(q)&&q.ai.__lfEcoKey===key&&q.ai.__lfEcoWeight>.05)n++;}return n;}
function routeCost(g,t,x,y,direct){direct=direct==null?Math.hypot(x-t.x,y-t.y):direct;if(!g.hasLineOfSight||g.hasLineOfSight(t.x,t.y,x,y,8)||!g.novaBattlefieldWaypoint)return direct;var wp=g.novaBattlefieldWaypoint(t.x,t.y,x,y,18,t.id);if(!wp)return direct*1.22;return Math.hypot(wp.x-t.x,wp.y-t.y)+Math.hypot(x-wp.x,y-wp.y);}
function publicEcoBias(g,t,defs,out){out=out||{};out.x=0;out.y=0;out.weight=0;out.key='none';out.mode='none';if(!g||!t||!t.ai)return out;var hp=clamp(t.hp/Math.max(1,t.maxHp||t.hp||1),0,1),a=t.ai,target=a.__v1112TargetId>=0&&g.getTank?g.getTank(a.__v1112TargetId):null;if(hp<.30||target&&alive(target)&&d2(t.x,t.y,target.x,target.y)<330*330)return out;var st=g.__lfState,sig=st&&st.signal,now=g.time||0,bx=0,by=0,bw=0,key='none',mode='none',judgment=a.isElite?1.08:.94;if(sig&&now<sig.until){var sx=sig.x,sy=sig.y;if(sig.type==='ROGUE STAR'&&sig.starId&&g.getShape){var star=g.getShape(sig.starId);if(star){sx=star.x;sy=star.y;}else return out;}var direct=Math.hypot(sx-t.x,sy-t.y),dist=routeCost(g,t,sx,sy,direct),base=sig.type==='ROGUE STAR'?.87:sig.type==='BLOOM'?.68:.48,k=sig.type+':'+(sig.sector!=null?sig.sector:sig.to!=null?sig.to:sig.starId||0),score=base-dist/2300-saturation(g,k,t.id)*.13;if(score>.20){var dx=sx-t.x,dy=sy-t.y,m=Math.hypot(dx,dy)||1;bx=dx/m;by=dy/m;bw=clamp(score*(.72+.28*hp)*judgment,0,.48);key=k;mode='signal';}}
 if(bw<=.04){var F=window.__NOVA_FAIR_ENGAGEMENT_TEST__,ext=F&&F.viewportHalfExtents?F.viewportHalfExtents(g):{x:Math.max(280,(g.w||800)/2),y:Math.max(220,(g.h||600)/2)},rad=Math.hypot(ext.x,ext.y),cand=st?LF.query(g,st,t.x,t.y,rad,0):(g.shapes||[]),vx=0,vy=0,value=0,count=0;for(var i=0;i<cand.length;i++){var s=cand[i];if(!s||s.kind!=='shape'||s.hp<=0||s.type==='crasher'||!visible(g,t,s))continue;var w=Math.max(5,xp(defs,s.type));vx+=s.x*w;vy+=s.y*w;value+=w;count++;}if(count>=4&&value>=170){vx/=value;vy/=value;var dx2=vx-t.x,dy2=vy-t.y,m2=Math.hypot(dx2,dy2)||1,k2='LOCAL:'+sectorIndex(vx,vy),travel=routeCost(g,t,vx,vy,m2),score2=clamp((value-160)/750,0,.36)-travel/3200-saturation(g,k2,t.id)*.10;if(score2>.08){bx=dx2/m2;by=dy2/m2;bw=clamp(score2*judgment,0,.32);key=k2;mode='local';}}}if(target&&alive(target))bw*=.55;if((t.id||0)%4===0)bw*=.72;out.x=bx;out.y=by;out.weight=bw;out.key=key;out.mode=mode;return out;}
LF.wrap('game/ai',function(ai,require){var old=ai.updateAI;if(!old||old.__novaLivingFront)return;var defs=(require('./types')||{}).SHAPE_DEFS||{};function patched(t,g,dt){if(!t||!t.ai||!g)return old(t,g,dt);var a=t.ai;a.__lfEcoT=(a.__lfEcoT||0)-dt;if(a.__lfEcoT<=0){a.__lfEcoT=(a.isElite?LF.AI_PERIOD*.82:LF.AI_PERIOD)+(Math.abs(t.id||0)%5)*.019;var prev=a.__lfEcoKey||'none',b=publicEcoBias(g,t,defs,a.__lfEcoBias||(a.__lfEcoBias={}));a.__lfEcoX=b.x;a.__lfEcoY=b.y;a.__lfEcoWeight=b.weight;a.__lfEcoKey=b.key;a.__lfEcoMode=b.mode;if(b.weight>.08&&prev!==b.key&&g.__lfState)g.__lfState.stats.aiRotations++;}var move=g.moveTank,own=Object.prototype.hasOwnProperty.call(g,'moveTank');if(move&&a.__lfEcoWeight>.04)g.moveTank=function(tt,vx,vy,dd){if(tt!==t)return move.apply(g,arguments);var sp=Math.hypot(vx||0,vy||0)||((g.tankSpeed&&g.tankSpeed(tt))||1),w=clamp(a.__lfEcoWeight,0,.48),x=(vx||0)/sp*(1-w)+a.__lfEcoX*w,y=(vy||0)/sp*(1-w)+a.__lfEcoY*w,m=Math.hypot(x,y)||1;return move.call(g,tt,x/m*sp,y/m*sp,dd);};try{return old(t,g,dt);}finally{if(move){if(own)g.moveTank=move;else delete g.moveTank;}}}patched.__novaLivingFront=true;ai.updateAI=patched;});
function diag(){var g=LF.getActive(),s=g?LF.snapshot(g):LF.getLast()||{active:false,version:V};return'NOVA TANKS · LIVING FRONT '+V+'\n'+JSON.stringify(s,null,2);}
function debugSummary(s){if(!s||!s.active)return'LIVING FRONT · no active/recorded match telemetry yet';var st=s.stats||{},counts=s.counts||{};return'LIVING FRONT v'+V+' · age '+s.age+'s · ceiling '+s.ceiling+' · '+s.director+' / last '+s.lastSignal+' · total XP '+s.totalXP+' · player neutral '+s.playerNeutralXPPerMin+' XP/min · plan '+s.planMsEma+'ms EMA / '+s.planMsPeak+'ms peak\nSHAPES C'+(counts.circle||0)+' T'+(counts.triangle||0)+' S'+(counts.square||0)+' P'+(counts.pentagon||0)+' H'+(counts.hexagon||0)+' ★'+(counts.star||0)+' CR'+(counts.crasher||0)+' · EVADE '+(st.triangleEvasions||0)+' · CRASH '+(st.crasherCharges||0)+'/'+(st.crasherHits||0)+'/'+(st.crasherMisses||0)+' · OVER '+(st.crasherOvershoots||0)+' · BOUNTY '+Math.round(st.bountyAbsorbed||0)+'/'+Math.round(st.bountyReleased||0)+' · STAR '+(st.starsIntercepted||0)+'/'+(st.starsSpawned||0)+' · BLOOM '+(st.blooms||0)+' · MIG '+(st.migrations||0)+' · AI ROT '+(st.aiRotations||0)+' · HEX AVG '+s.hexAvgNeighbors+'\n'+s.sectors.map(function(q){return q.i+':M'+q.m.toFixed(2)+' P'+q.p.toFixed(2)+' N'+q.n+' XP'+q.xp+' H'+q.harvest.toFixed(2)+' C'+q.combat.toFixed(2)+' '+q.in.toFixed(1)+'→/'+q.out.toFixed(1)+'←';}).join(' · ');}
function fill(root){if(!root)return;var h=root.querySelector('.nv-lf-debug');if(!h){h=document.createElement('div');h.className='nv-lf-debug';h.style.cssText='margin-top:8px;padding:8px;border:1px solid rgba(255,201,77,.18);border-radius:10px;background:rgba(12,16,26,.7);font:600 9px/1.25 Rajdhani,system-ui;color:#aebed0;white-space:pre-wrap;';var a=root.querySelector('.nv-debug-actions');a?root.insertBefore(h,a):root.appendChild(h);}var s=LF.getActive()?LF.snapshot(LF.getActive()):LF.getLast();h.textContent=debugSummary(s);var b=document.createElement('button');b.type='button';b.dataset.lfCopy='1';b.className='nv-debug-btn';b.textContent='COPY ECOLOGY';b.style.marginTop='7px';b.onclick=function(){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(diag()).catch(function(){});};h.appendChild(document.createElement('br'));h.appendChild(b);}
function registerTips(){var api=window.NOVATips;if(!api||typeof api.registerMany!=='function'||window.__NOVA_LIVING_FRONT_TIPS_REGISTERED__)return false;window.__NOVA_LIVING_FRONT_TIPS_REGISTERED__=true;api.registerMany(TIP_DEFS);return true;}
function bindTipLine(){return registerTips();} // compatibility shim: canonical Fieldcraft owns rendering, cadence, and shuffle bags.
function bindDebug(p){if(!p||p.__lfDebugBound)return;p.__lfDebugBound=true;fill(p);var r=p.querySelector('[data-debug-refresh]');if(r)r.addEventListener('click',function(){setTimeout(function(){if(p.isConnected)fill(p);},0);});}
function scanUi(){registerTips();var p=document.querySelector('.nv-debug-panel');if(p)bindDebug(p);}
registerTips();
if(typeof document!=='undefined'&&typeof MutationObserver!=='undefined'){var queued=false,o=new MutationObserver(function(){if(queued)return;queued=true;setTimeout(function(){queued=false;scanUi();},60);});var root=document.getElementById('root')||document.documentElement;o.observe(root,{childList:true,subtree:true});scanUi();}
window.__NOVA_VERSION=V;window.__NOVA_LIVING_FRONT__={version:V,codename:'Living Front',date:'2026-08-30',contract:{globalShapeTargetsPreserved:true,noXpMultiplierZones:true,noPityLogic:true,noNewControls:true,noPermanentEcologyPanel:true,noControllerStrategicAutonomy:true,noAiHiddenMaturity:true,noAiStatBuffs:true,terrainConstrained:true,physicalMigration:true,boundedHerding:true,nearFireHerding:true,explosionHerding:true,crasherBountyStatsOnly:true,explicitCrasherOvershoot:true,squareIntentionallySimple:true,directorMostlyObserves:true,rogueStarSingleCreatedOpportunity:true,ageGatedHighValueClustering:true,terrainVisibleInstincts:true,canonicalTipRegistry:true,rejectedScope:REJECTED.slice()},cadences:{sectorHz:+(1/LF.SECTOR_PERIOD).toFixed(2),shapeIntentHz:+(1/LF.BEHAVIOR_PERIOD).toFixed(2),directorHz:+(1/LF.DIRECTOR_PERIOD).toFixed(2),aiHz:+(1/LF.AI_PERIOD).toFixed(2)},shapeTargets:Object.assign({},LF.TARGETS)};
window.__NOVA_LIVING_FRONT_RELEASE__={version:V,codename:'Living Front',date:'2026-08-30',headline:'Fighting changes the farm. Farming changes where fights happen.',groups:{'Ecology Core':['Sixteen invisible sectors mature under quiet and lose value concentration under harvesting and combat pressure.','The existing 62/30/16/8/4 shape quotas remain authoritative; Living Front changes safe geography, not requested types or XP multipliers.','A shared match-age ceiling now gates high-value clustering as well as maturity, keeping early arenas distributed before later pockets emerge.'],'Wild Instincts':['Circles school gently, Triangles get one readable evade, Squares remain simple, cascades inherit impact direction and Hexagons become bounded terrain-visible keystones.','Stars are interception prey; Crashers telegraph, commit, explicitly overshoot, obey terrain, and store capped XP bounty from neutral prey without gaining combat stats.','Migration and herding are physical, bounded, terrain-constrained and self-limiting; near fire and explosions can move skittish prey with diminishing response.'],'Front Director':['BLOOM reports existing value only after ecological age makes a true mature pocket possible; MIGRATION reports actual crossings; ROGUE STAR is the sole rare created opportunity after strategic quiet.','Signals are brief minimap/world information, not capture zones, event meters, currencies, quests or forced contests.'],'Strategy & Performance':['Human Controller automation remains local and never chooses a distant ecology objective. AI consumes only terrain-visible Fair Engagement viewport shapes and public signals, with health, route cost, saturation and skill-level judgment gates.','Sector, shape, Director and AI planning are decimated and local candidate work reuses the canonical entity hash.'],'Fieldcraft':['Seven Living Front tactical tips register through the canonical NOVATips shuffle-bag API, inheriting the game-wide randomized cadence instead of rewriting the rendered tip line.']}};
window.__NOVA_LIVING_FRONT_TIPS__=TIP_DEFS.map(function(t){return{id:t.id,text:t.text,tags:t.tags.slice(),reviewed:t.reviewed,source:t.source};});
window.NOVALivingFront={version:V,snapshot:function(){var g=LF.getActive();return g?LF.snapshot(g):LF.getLast()||{active:false,version:V};},diagnostics:diag};
window.__NOVA_LIVING_FRONT_TEST__={GRID:LF.GRID,ARENA:LF.ARENA,SECTOR_PERIOD:LF.SECTOR_PERIOD,BEHAVIOR_PERIOD:LF.BEHAVIOR_PERIOD,DIRECTOR_PERIOD:LF.DIRECTOR_PERIOD,AI_PERIOD:LF.AI_PERIOD,BOUNTY_CAP:LF.BOUNTY_CAP,STAR_SPEED_MULT:LF.STAR_SPEED_MULT,sectorIndex:LF.sectorIndex,sectorCenter:LF.sectorCenter,neighbors:LF.neighbors,maturityCeiling:LF.maturityCeiling,ageProgress:LF.ageProgress,makeSector:LF.makeSector,advanceSector:LF.advanceSector,chooseSpawnSector:LF.chooseSpawnSector,bulletThreat:LF.bulletThreat,triangleEvadeVector:LF.evadeVector,advanceCrasherState:LF.crasherState,awardBounty:LF.awardBounty,bloomAgeEligible:bloomAgeEligible,bloomCandidate:bloomCandidate,directorDecision:decision,publicEcoBias:publicEcoBias,routeCost:routeCost,registerTips:registerTips,rejectedScope:REJECTED.slice(),shapeTargets:Object.assign({},LF.TARGETS)};
console.info('[NOVA TANKS] v'+V+' Living Front director/strategy online');
})();