/* NOVA TANKS v1.12.0 — Living Front / Stage II: Wild Instincts */
/* NOVA_VISUAL_INTENT: world telegraphs only — Crasher commitment/bounty, Star direction, Hexagon anchoring, and Triangle evasion communicate immediate spatial decisions. */
(function(){'use strict';
var LF=window.__NOVA_LIVING_FRONT_INTERNAL__,mods=window.__novaModules;if(!LF||!mods){console.error('[NOVA v1.12.0] Living Front core missing');return;}if(LF.instincts)return;LF.instincts=true;
var clamp=LF.clamp,lerp=LF.lerp,d2=LF.d2,alive=LF.alive,query=LF.query,speed=LF.speed,xp=LF.xp,sectorIndex=LF.sectorIndex,sectorCenter=LF.sectorCenter,neighbors=LF.neighbors,TAU=LF.TAU,ARENA=LF.ARENA,BOUNTY_CAP=LF.BOUNTY_CAP,STAR_SPEED_MULT=1.95;
function cap(s,m){var v=Math.hypot(s.vx||0,s.vy||0);if(v>m&&m>0){s.vx=s.vx/v*m;s.vy=s.vy/v*m;}}
function edge(s,k){var m=ARENA-120;k=k||1;if(s.x>m)s.vx-=((s.x-m)/120)*24*k;if(s.x<-m)s.vx+=((-m-s.x)/120)*24*k;if(s.y>m)s.vy-=((s.y-m)/120)*24*k;if(s.y<-m)s.vy+=((-m-s.y)/120)*24*k;}
function los(g,ax,ay,bx,by,pad){return !g.hasLineOfSight||g.hasLineOfSight(ax,ay,bx,by,pad||2);}
var BULLET_CELL=180;
function bulletKey(cx,cy){return cx*10000+cy;}
function bulletIndex(g){var ix=g.__lfBulletIndex;if(ix)return ix;return g.__lfBulletIndex={cell:BULLET_CELL,cells:new Map(),active:[],creates:0};}
function buildBulletIndex(g,st){var ix=bulletIndex(g),active=ix.active;for(var i=0;i<active.length;i++)active[i].length=0;active.length=0;var seen=Object.create(null),bs=g.bullets||[],cell=ix.cell;for(i=0;i<bs.length;i++){var b=bs[i];if(!b||b.dead)continue;var cx=Math.floor(b.x/cell),cy=Math.floor(b.y/cell),key=bulletKey(cx,cy),bucket=ix.cells.get(key);if(!bucket){bucket=[];ix.cells.set(key,bucket);ix.creates++;}if(bucket.length===0)active.push(bucket);bucket.push(b);var si=sectorIndex(b.x,b.y);if(!seen[si]){seen[si]=1;LF.addPressure(g,b.x,b.y,.005);}}return ix;}
function queryBullets(g,x,y,r,out){var ix=g.__lfBulletIndex;if(!ix)return out;var cell=ix.cell,cx0=Math.floor((x-r)/cell),cx1=Math.floor((x+r)/cell),cy0=Math.floor((y-r)/cell),cy1=Math.floor((y+r)/cell),rr=r*r;for(var cx=cx0;cx<=cx1;cx++)for(var cy=cy0;cy<=cy1;cy++){var a=ix.cells.get(bulletKey(cx,cy));if(!a)continue;for(var i=0;i<a.length;i++){var b=a[i];if(!b||b.dead||d2(x,y,b.x,b.y)>rr)continue;var exists=false;for(var j=0;j<out.length;j++)if(out[j]===b){exists=true;break;}if(!exists)out.push(b);}}return out;}
function calmNeighbor(st,i){var ns=neighbors(i),cur=st.sectors[i],best=-1,delta=.12;for(var k=0;k<ns.length;k++){var q=st.sectors[ns[k]],d=(cur.pressure-q.pressure)*.90+(q.maturity-cur.maturity)*.18;if(d>delta){delta=d;best=ns[k];}}return best;}
function migrate(st,s,defs){if(!({circle:1,triangle:1,square:1,pentagon:1})[s.type]){s.__lfMigrationIntent=-1;return;}var i=sectorIndex(s.x,s.y),to=calmNeighbor(st,i);if(to<0){s.__lfMigrationIntent=-1;return;}var c=sectorCenter(to),dx=c.x-s.x,dy=c.y-s.y,m=Math.hypot(dx,dy)||1,res=s.type==='pentagon'?.20:s.type==='square'?.34:s.type==='triangle'?.65:.54,sp=speed(defs,s.type);s.vx+=dx/m*sp*.24*res;s.vy+=dy/m*sp*.24*res;s.__lfMigrationIntent=to;cap(s,sp*(s.type==='triangle'?2:1.45));}
function transition(st,s){var n=sectorIndex(s.x,s.y),o=s.__lfSector;if(o==null){s.__lfSector=n;return;}if(n===o)return;if(s.__lfMigrationIntent===n){var a=sectorCenter(o),b=sectorCenter(n),dx=b.x-a.x,dy=b.y-a.y,m=Math.hypot(dx,dy)||1;st.sectors[o].outbound++;st.sectors[n].inbound++;st.sectors[o].flowX+=dx/m;st.sectors[o].flowY+=dy/m;st.migrationHeat++;st.migrationX+=dx/m;st.migrationY+=dy/m;st.migrationTransitions++;}s.__lfSector=n;}
function bulletThreat(s,b,h,pad){if(!b||b.dead||b.kind!=='bullet')return 0;var vx=b.vx||0,vy=b.vy||0,q=vx*vx+vy*vy;if(q<400)return 0;var rx=s.x-b.x,ry=s.y-b.y,t=(rx*vx+ry*vy)/q;if(t<.025||t>(h||.32))return 0;var x=b.x+vx*t,y=b.y+vy*t,miss=Math.hypot(s.x-x,s.y-y),r=(s.r||15)+(b.r||3)+(pad||18);return miss<r?(1-miss/r)*(1-t/(h||.32)):0;}
function evadeVector(s,b){var vx=b.vx||0,vy=b.vy||0,m=Math.hypot(vx,vy)||1,side=((s.id||0)^(b.id||0))&1?1:-1;return{x:-vy/m*side,y:vx/m*side};}
function triangle(g,st,s,defs,now){if(now<(s.__lfEvadeUntil||0)){edge(s,.9);cap(s,speed(defs,'triangle')*2);return;}var ready=now>=(s.__lfEvadeReady||0),a=query(g,st,s.x,s.y,210,0),best=null,near=null,nearD=135*135,bt=0;for(var i=0;i<a.length;i++){var e=a[i];if(e&&e.kind==='bullet'){if(!los(g,s.x,s.y,e.x,e.y,2))continue;var dd=d2(s.x,s.y,e.x,e.y);if(dd<nearD){nearD=dd;near=e;}}var q=ready?bulletThreat(s,e,.34,20):0;if(q>bt){bt=q;best=e;}}if(best&&bt>.13){var v=evadeVector(s,best),sp=speed(defs,'triangle');s.vx=v.x*sp*2.05;s.vy=v.y*sp*2.05;s.__lfEvadeUntil=now+.20;s.__lfEvadeReady=now+.84+((s.id^best.id)%7)*.03;s.__lfEvadeDirX=v.x;s.__lfEvadeDirY=v.y;s.wanderT=Math.max(s.wanderT||0,.38);st.stats.triangleEvasions++;return;}if(near){var dist=Math.sqrt(nearD),power=clamp((135-dist)/135,0,.42);if(power>.04)applyDisturbance(g,st,s,defs,s.x-near.x,s.y-near.y,power,'fire');}}
function circle(g,st,s,defs){var a=query(g,st,s.x,s.y,145,0),cx=0,cy=0,avx=0,avy=0,n=0,fx=0,fy=0,near=null,nearD=135*135;for(var i=0;i<a.length&&n<8;i++){var q=a[i];if(!q||q===s||!los(g,s.x,s.y,q.x,q.y,2))continue;if(q.kind==='shape'&&q.type==='circle'){cx+=q.x;cy+=q.y;avx+=q.vx||0;avy+=q.vy||0;n++;}else if(q.kind==='tank'&&alive(q)){var dx=s.x-q.x,dy=s.y-q.y,dd=dx*dx+dy*dy;if(dd<135*135&&dd>1){var m=Math.sqrt(dd);fx+=dx/m*(1-m/135);fy+=dy/m*(1-m/135);}}else if(q.kind==='bullet'&&!q.dead){var bd=d2(s.x,s.y,q.x,q.y);if(bd<nearD){nearD=bd;near=q;}}}if(n){cx=cx/n-s.x;cy=cy/n-s.y;var m2=Math.hypot(cx,cy)||1;s.vx+=cx/m2*.55+(avx/n-(s.vx||0))*.025;s.vy+=cy/m2*.55+(avy/n-(s.vy||0))*.025;}s.vx+=fx*1.8;s.vy+=fy*1.8;if(near){var dist=Math.sqrt(nearD),power=clamp((135-dist)/135,0,.48);if(power>.04)applyDisturbance(g,st,s,defs,s.x-near.x,s.y-near.y,power,'fire');}cap(s,speed(defs,'circle')*1.38);}
function herd(g,s,defs){if(s.type!=='circle'&&s.type!=='triangle')return;var ts=g.tanks||[],fx=0,fy=0;for(var i=0;i<ts.length;i++){var t=ts[i];if(!alive(t)||!los(g,s.x,s.y,t.x,t.y,2))continue;var dx=s.x-t.x,dy=s.y-t.y,r=s.type==='circle'?135:115,dd=dx*dx+dy*dy;if(dd>=r*r||dd<1)continue;var m=Math.sqrt(dd),q=1-m/r;fx+=dx/m*q;fy+=dy/m*q;}s.vx+=fx*(s.type==='circle'?1.25:.85);s.vy+=fy*(s.type==='circle'?1.25:.85);cap(s,speed(defs,s.type)*(s.type==='circle'?1.5:2));}
function disturbanceResistance(s){return s.type==='circle'?1:s.type==='triangle'?.68:s.type==='square'?.30:s.type==='pentagon'?.12:0;}
function applyDisturbance(g,st,s,defs,dx,dy,power,kind){var resist=disturbanceResistance(s);if(resist<=0)return false;var m=Math.hypot(dx,dy);if(m<1e-5)return false;var memory=Math.max(0,(Number(s.__lfDisturbance)||0)-LF.BEHAVIOR_PERIOD*.72),sat=1/(1+memory*.95),impulse=power*resist*sat,sp=Math.max(6,speed(defs,s.type));s.vx+=(dx/m)*sp*impulse;s.vy+=(dy/m)*sp*impulse;s.__lfDisturbance=clamp(memory+power*.78,0,2.8);cap(s,sp*(s.type==='triangle'?2:s.type==='circle'?1.55:1.35));if(kind==='fire')st.stats.nearFireHerds++;else if(kind==='burst')st.stats.burstHerds++;return true;}
function nearFire(g,st,s,defs){var resist=disturbanceResistance(s);if(resist<=0)return;var a=query(g,st,s.x,s.y,135,1),best=null,bd=Infinity;for(var i=0;i<a.length;i++){var b=a[i];if(!b||b.kind!=='bullet'||b.dead||!los(g,s.x,s.y,b.x,b.y,2))continue;var dd=d2(s.x,s.y,b.x,b.y);if(dd<bd){bd=dd;best=b;}}if(!best)return;var dist=Math.sqrt(bd),power=clamp((135-dist)/135,0,.55);if(power>.04)applyDisturbance(g,st,s,defs,s.x-best.x,s.y-best.y,power,'fire');}
function disturbBurst(g,x,y,radius,power){var st=g&&g.__lfState;if(!st)return;var defs=st.defs||LF.defs||{},a=query(g,st,x,y,Math.max(50,radius),1);for(var i=0;i<a.length;i++){var s=a[i];if(!s||s.kind!=='shape'||s.hp<=0||!los(g,x,y,s.x,s.y,2))continue;var d=Math.hypot(s.x-x,s.y-y),p=clamp(1-d/Math.max(1,radius),0,1)*(power||.6);if(p>.05)applyDisturbance(g,st,s,defs,s.x-x,s.y-y,p,'burst');}}
function hex(g,st,h,defs){var a=query(g,st,h.x,h.y,310,0),local=0,maturity=st.sectors[sectorIndex(h.x,h.y)].maturity/Math.max(.1,st.ceiling),strength=.46+.72*maturity;for(var i=0;i<a.length&&local<18;i++){var s=a[i];if(!s||s===h||s.kind!=='shape'||!({circle:1,triangle:1,square:1,pentagon:1})[s.type])continue;var dx=h.x-s.x,dy=h.y-s.y,d=Math.hypot(dx,dy);if(d<75||d>310||!los(g,h.x,h.y,s.x,s.y,Math.min(5,(s.r||12)*.2+1)))continue;var p=(1-d/310)*strength;s.vx+=dx/d*p;s.vy+=dy/d*p;cap(s,speed(defs,s.type)*(s.type==='triangle'?1.9:1.42));local++;}st.stats.hexSamples++;st.stats.hexNeighbors+=local;}
function crasherScore(defs,cr,e){if(!e||e===cr||e.hp==null||e.hp<=0)return-Infinity;var d=Math.hypot(e.x-cr.x,e.y-cr.y);if(e.kind==='shape'){if(e.type==='crasher'||e.type==='star'||e.type==='hexagon')return-Infinity;return 1.65*(1-clamp(e.hp/Math.max(1,e.maxHp||e.hp),0,1))+clamp(xp(defs,e.type)/110,0,.85)-d/620;}if(e.kind==='tank'&&alive(e)){var f=clamp(e.hp/Math.max(1,e.maxHp||e.hp),0,1);return f>.72?-Infinity:.25+1.55*(1-f)-d/760;}return-Infinity;}
function chooseCrasher(g,st,cr,defs){var a=query(g,st,cr.x,cr.y,700,0),best=null,score=-99;for(var i=0;i<a.length;i++){var e=a[i],q=crasherScore(defs,cr,e);if(q>score&&los(g,cr.x,cr.y,e.x,e.y,2)){score=q;best=e;}}return score>-.35?best:null;}
function crasherState(state,t,dt,aligned,inRange){t-=dt;if(state==='track'&&aligned&&inRange)return{state:'telegraph',t:.40};if(state==='telegraph'&&t<=0)return{state:'charge',t:.56};if(state==='charge'&&t<=0)return{state:'overshoot',t:.18};if(state==='overshoot'&&t<=0)return{state:'recover',t:.54};if(state==='recover'&&t<=0)return{state:'track',t:.28};return{state:state,t:t};}
function crasher(g,st,cr,defs,dt){
  cr.wanderT=999;var state=cr.__lfPredatorState||'track',target=null;if(cr.__lfTargetId>=0){target=cr.__lfTargetKind==='tank'?(g.getTank&&g.getTank(cr.__lfTargetId)):(g.getShape&&g.getShape(cr.__lfTargetId));if(!alive(target))target=null;}
  if(target&&(d2(cr.x,cr.y,target.x,target.y)>860*860||!los(g,cr.x,cr.y,target.x,target.y,2))){target=null;cr.__lfTargetId=-1;cr.__lfTargetKind='';}
  if(state==='track'&&!target){target=chooseCrasher(g,st,cr,defs);cr.__lfTargetId=target?target.id:-1;cr.__lfTargetKind=target?target.kind:'';}
  var dx=target?target.x-cr.x:0,dy=target?target.y-cr.y:0,d=Math.hypot(dx,dy),ang=d?Math.atan2(dy,dx):(cr.angle||0),heading=Math.atan2(cr.vy||0,cr.vx||0),da=Math.atan2(Math.sin(ang-heading),Math.cos(ang-heading)),n=crasherState(state,cr.__lfPredatorT==null?.2:cr.__lfPredatorT,dt,!!target&&Math.abs(da)<.34,!!target&&d<390);
  if(n.state!==state){
    if(n.state==='telegraph'){cr.__lfCommitAngle=ang;cr.__lfChargeHit=false;if(g.sfx&&g.sfx.novaLivingCrasher&&g.player&&d2(cr.x,cr.y,g.player.x,g.player.y)<850*850)g.sfx.novaLivingCrasher((cr.x-g.player.x)/700);}
    if(n.state==='charge'){cr.__lfCommitAngle=target?Math.atan2(target.y-cr.y,target.x-cr.x):(cr.__lfCommitAngle||heading);st.stats.crasherCharges++;}
    if(n.state==='overshoot'){st.stats.crasherOvershoots++;cr.__lfTargetId=-1;cr.__lfTargetKind='';}
    if(state==='overshoot'&&n.state==='recover'){if(cr.__lfChargeHit)st.stats.crasherHits++;else st.stats.crasherMisses++;}
    cr.__lfPredatorState=n.state;cr.__lfPredatorT=n.t;state=n.state;
  }else cr.__lfPredatorT=n.t;
  var sp=speed(defs,'crasher')||105;
  if(state==='track'){if(target){var ux=dx/(d||1),uy=dy/(d||1);cr.vx=lerp(cr.vx||0,ux*sp*.66,.18);cr.vy=lerp(cr.vy||0,uy*sp*.66,.18);}else{cr.vx*=.96;cr.vy*=.96;}}
  else if(state==='telegraph'){if(target)cr.__lfCommitAngle=Math.atan2(target.y-cr.y,target.x-cr.x);cr.vx*=.72;cr.vy*=.72;}
  else if(state==='charge'||state==='overshoot'){
    var ca=cr.__lfCommitAngle||0;cr.vx=Math.cos(ca)*sp*(state==='charge'?1.42:1.20);cr.vy=Math.sin(ca)*sp*(state==='charge'?1.42:1.20);
    if(cr.__novaTerrainBumpT>0){cr.__lfPredatorState='recover';cr.__lfPredatorT=.70;cr.vx*=.28;cr.vy*=.28;if(state==='charge'&&!cr.__lfChargeHit)st.stats.crasherMisses++;cr.__lfTargetId=-1;state='recover';}
    if(state==='charge'||state==='overshoot'){var a2=query(g,st,cr.x,cr.y,48,1);for(var k=0;k<a2.length;k++){var e=a2[k];if(!e||e===cr||!los(g,cr.x,cr.y,e.x,e.y,2))continue;if(e.kind==='tank'&&alive(e)&&d2(cr.x,cr.y,e.x,e.y)<Math.pow((cr.r||15)+(e.r||18)+4,2)){cr.__lfChargeHit=true;break;}if(e.kind==='shape'&&e.type!=='crasher'&&e.type!=='star'&&e.type!=='hexagon'&&e.hp>0&&d2(cr.x,cr.y,e.x,e.y)<Math.pow((cr.r||15)+(e.r||12)+3,2)){var dmg=22;if(e.hp<=dmg)e.__lfPredatorKiller=cr.id;if(g.damageShape)g.damageShape(e,dmg,cr.vx*.55,cr.vy*.55);cr.__lfChargeHit=true;break;}}}
  }else if(state==='recover'){cr.vx*=.88;cr.vy*=.88;}
  edge(cr,1.25);cap(cr,sp*1.45);
}
function starPoint(g,s,edgeId,seed){for(var i=0;i<20;i++){var span=ARENA-180,u=-span+2*span*((Math.sin((seed+i*19)*12.9898+(edgeId+61)*78.233)*43758.5453)%1+1)%1,p=edgeId===0?{x:-ARENA+125,y:u}:edgeId===1?{x:ARENA-125,y:u}:edgeId===2?{x:u,y:-ARENA+125}:{x:u,y:ARENA-125};if(!g.isTerrainSafe||g.isTerrainSafe(p.x,p.y,(s.r||24)+20))return p;}return{x:0,y:0};}
function initStar(g,st,s){var e=Math.floor((((Math.sin(s.id*17.3)*999)%1+1)%1)*4),p=starPoint(g,s,e,s.id),opp=e===0?1:e===1?0:e===2?3:2,q=starPoint(g,s,opp,s.id+101);s.x=p.x;s.y=p.y;s.__lfSector=sectorIndex(s.x,s.y);s.__lfRogue=true;s.__lfStarBorn=g.time||0;s.__lfGoalX=q.x;s.__lfGoalY=q.y;s.__lfGoalEdge=opp;s.wanderT=999;st.stats.starsSpawned++;}
function remove(g,s){var i=g.shapes.indexOf(s);if(i<0)return false,last=g.shapes.length-1;if(i!==last)g.shapes[i]=g.shapes[last];g.shapes.pop();if(g.shapeById)g.shapeById.delete(s.id);return true;}
function star(g,st,s,defs,now){s.wanderT=999;var age=now-(s.__lfStarBorn==null?now:s.__lfStarBorn);if(age>32){st.stats.starsExpired++;st.stats.starLifetimeTotal+=age;remove(g,s);return false;}if(age>23&&!s.__lfExit){s.__lfExit=true;var e=Math.abs(s.x)>Math.abs(s.y)?(s.x>0?1:0):(s.y>0?3:2),p=starPoint(g,s,e,s.id+211);s.__lfGoalX=p.x;s.__lfGoalY=p.y;}var gx=s.__lfGoalX,gy=s.__lfGoalY;if(!Number.isFinite(gx)){var c=sectorCenter((sectorIndex(s.x,s.y)+8)%16);gx=s.__lfGoalX=c.x;gy=s.__lfGoalY=c.y;}var tx=gx,ty=gy;if(!los(g,s.x,s.y,gx,gy,(s.r||24)+5)&&g.novaBattlefieldWaypoint){var wp=g.novaBattlefieldWaypoint(s.x,s.y,gx,gy,(s.r||24)+5,s.id);if(wp){tx=wp.x;ty=wp.y;}}var dx=tx-s.x,dy=ty-s.y,m=Math.hypot(dx,dy)||1,sp=(speed(defs,'star')||78)*STAR_SPEED_MULT;s.vx=lerp(s.vx||0,dx/m*sp,.28);s.vy=lerp(s.vy||0,dy/m*sp,.28);edge(s,1.4);cap(s,sp*1.12);return true;}
LF.disturbBurst=disturbBurst;LF.queryBullets=queryBullets;LF.buildBulletIndex=buildBulletIndex;
LF.behaviorTick=function(g,st,defs,dt){var t0=LF.ms(),now=g.time||0,sh=g.shapes||[];buildBulletIndex(g,st);
  for(var i=0;i<sh.length;i++){var s=sh[i];if(!s||s.hp<=0)continue;transition(st,s);if(s.__lfDisturbance)s.__lfDisturbance=Math.max(0,s.__lfDisturbance-dt*.72);if(s.type==='circle')circle(g,st,s,defs);else if(s.type==='triangle')triangle(g,st,s,defs,now);else if(s.type==='crasher')crasher(g,st,s,defs,dt);else if(s.type==='star'){if(!star(g,st,s,defs,now)){i--;continue;}}var committed=s.type==='triangle'&&now<(s.__lfEvadeUntil||0);if(!committed)herd(g,s,defs);if(!committed)migrate(st,s,defs);edge(s,s.type==='hexagon'?.25:1);}for(i=0;i<sh.length;i++)if(sh[i]&&sh[i].hp>0&&sh[i].type==='hexagon')hex(g,st,sh[i],defs);LF.planSample(st,LF.ms()-t0);};
LF.bulletThreat=bulletThreat;LF.evadeVector=evadeVector;LF.crasherState=crasherState;LF.initStar=initStar;LF.disturbanceResistance=disturbanceResistance;LF.STAR_SPEED_MULT=STAR_SPEED_MULT;
LF.wrap('game/audio',function(audio){var Sfx=audio.Sfx;if(!Sfx||Sfx.prototype.__novaLivingFrontAudio)return;Sfx.prototype.__novaLivingFrontAudio=true;function tone(self,a,b,d,g,p,type){if(self.muted)return;if(self.resume)self.resume();if(!self.ctx||!self.master)return;var c=self.ctx,t=c.currentTime,o=c.createOscillator(),v=c.createGain(),pan=null;o.type=type||'triangle';o.frequency.setValueAtTime(Math.max(35,a),t);o.frequency.exponentialRampToValueAtTime(Math.max(35,b),t+d);v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);if(c.createStereoPanner){pan=c.createStereoPanner();pan.pan.value=clamp(p||0,-1,1);o.connect(v).connect(pan).connect(self.master);}else o.connect(v).connect(self.master);o.start(t);o.stop(t+d+.03);}Sfx.prototype.novaLivingSignal=function(k,p){if(k==='ROGUE STAR'){tone(this,420,880,.19,.018,p);tone(this,700,1320,.12,.009,p,'sine');}else if(k==='BLOOM')tone(this,360,620,.15,.012,p,'sine');else tone(this,520,410,.11,.010,p);};Sfx.prototype.novaLivingCrasher=function(p){tone(this,150,310,.22,.016,p,'sawtooth');};});
LF.wrap('game/render',function(render){var old=render.render;if(!old||old.__novaLivingFront)return;if(window.NOVAVisuals&&window.NOVAVisuals.registerMany)try{window.NOVAVisuals.registerMany([{id:'living-front-crasher-commitment',intent:'threat',channel:'world',question:'Where is this Crasher about to commit its charge?',reason:'The charge line creates a dodge, bait, terrain or shoot-down decision.',duration:'while-telegraphing'},{id:'living-front-fed-crasher',intent:'state',channel:'world',question:'Is this Crasher carrying additional neutral bounty?',reason:'Core intensity changes whether contesting the predator is worth positional risk.',duration:'while-fed'},{id:'living-front-star-motion',intent:'spatial',channel:'world',question:'Which way is the roaming Star moving?',reason:'A short trail supports interception rather than blind pursuit.',duration:'while-visible'}]);}catch(_){}function patched(g,w,h){old(g,w,h);if(!g||!g.ctx||!g.__lfState)return;var ctx=g.ctx,z=(g.cam&&g.cam.zoom)||1,cx=g.cam.x,cy=g.cam.y,hw=g.w*.5,hh=g.h*.5,tm=g.time||0,sh=g.shapes||[];ctx.save();ctx.setTransform(g.dpr||1,0,0,g.dpr||1,0,0);for(var i=0;i<sh.length;i++){var s=sh[i];if(!s||s.hp<=0)continue;var x=(s.x-cx)*z+hw,y=(s.y-cy)*z+hh;if(x<-90||x>w+90||y<-90||y>h+90)continue;if(s.type==='crasher'){var bounty=Number(s.__lfBounty)||0;if(bounty){ctx.save();ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.12+.26*clamp(bounty/BOUNTY_CAP,0,1);ctx.fillStyle='#ffe066';ctx.beginPath();ctx.arc(x,y,Math.max(3,(s.r||15)*z*.48),0,TAU);ctx.fill();ctx.restore();}if(s.__lfPredatorState==='telegraph'){var a=s.__lfCommitAngle||0;ctx.save();ctx.strokeStyle='#ff8a77';ctx.globalAlpha=.35+.25*Math.sin(tm*18);ctx.lineWidth=Math.max(1,1.3*z);ctx.setLineDash([7*z,6*z]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*95*z,y+Math.sin(a)*95*z);ctx.stroke();ctx.restore();}else if(s.__lfPredatorState==='overshoot'){ctx.save();ctx.strokeStyle='#ffb093';ctx.globalAlpha=.16;ctx.lineWidth=Math.max(1,1*z);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-(s.vx||0)*.12*z,y-(s.vy||0)*.12*z);ctx.stroke();ctx.restore();}}else if(s.type==='star'){var m=Math.hypot(s.vx||0,s.vy||0);if(m>1){ctx.save();ctx.strokeStyle='#ffe066';ctx.globalAlpha=.30;ctx.lineWidth=Math.max(1,1.2*z);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-s.vx/m*34*z,y-s.vy/m*34*z);ctx.stroke();ctx.restore();}}else if(s.type==='hexagon'){ctx.save();ctx.strokeStyle='#ff9ac2';ctx.globalAlpha=.12;ctx.beginPath();ctx.arc(x,y,(s.r||33)*z*1.18,0,TAU);ctx.stroke();ctx.restore();}else if(s.type==='triangle'&&tm<(s.__lfEvadeUntil||0)){ctx.save();ctx.strokeStyle='#a9ffd1';ctx.globalAlpha=.38;ctx.beginPath();ctx.moveTo(x-(s.__lfEvadeDirX||0)*7*z,y-(s.__lfEvadeDirY||0)*7*z);ctx.lineTo(x+(s.__lfEvadeDirX||0)*9*z,y+(s.__lfEvadeDirY||0)*9*z);ctx.stroke();ctx.restore();}}ctx.restore();}patched.__novaLivingFront=true;render.render=patched;});
console.info('[NOVA TANKS] v'+LF.VERSION+' Living Front wild instincts online');
})();