/* NOVA TANKS data-driven lobby release browser */
(function(){
'use strict';
var data=null,modal=null;
var accents={'1.5.1':'#7df3ff','1.5.0':'#7df3ff','1.4.1':'#b06bff','1.4.0':'#b06bff','1.3.1':'#75f0a3','1.3.0':'#75f0a3','1.2.0':'#c493ff','1.1.0':'#75f0a3','1.0.0':'#4de3ff'};
function css(){if(document.getElementById('nova-history-css'))return;var s=document.createElement('style');s.id='nova-history-css';s.textContent=`
.nv-chip{display:inline-flex;align-items:center;gap:6px;margin-top:9px;padding:5px 10px;border:1px solid var(--nvc,#7df3ff55);border-radius:999px;background:rgba(40,70,90,.20);color:var(--nvt,#d9f4ff);font:700 9px Orbitron,system-ui;letter-spacing:.15em}.nv-dot{width:5px;height:5px;border-radius:50%;background:var(--nvd,#75f0a3);box-shadow:0 0 8px var(--nvd,#75f0a3)}.nv-card{width:100%;box-sizing:border-box;margin-top:12px;padding:12px;border:1px solid var(--nvc,#7df3ff40);border-radius:14px;background:linear-gradient(145deg,var(--nvb,rgba(20,40,60,.55)),#070b18e8);text-align:left}.nv-top{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.nv-k{color:var(--nvt,#7df3ff);font:800 9px Orbitron,system-ui;letter-spacing:.2em}.nv-h{margin-top:4px;color:#e7eef7;font:700 12px Rajdhani,system-ui}.nv-s{display:grid;gap:3px;margin-top:7px;color:#aab7cc;font:600 10px Rajdhani,system-ui}.nv-s span:before{content:'›';margin-right:6px;color:var(--nvd,#75f0a3)}.nv-btn{border:1px solid #7df3ff55;border-radius:10px;padding:7px 9px;background:#1e466955;color:#c9f5ff;font:800 9px Orbitron,system-ui;letter-spacing:.1em;white-space:nowrap}.nv-overlay{position:fixed;inset:0;z-index:9999;display:flex;justify-content:center;align-items:center;padding:max(16px,env(safe-area-inset-top)) 14px max(16px,env(safe-area-inset-bottom));background:#010309d9;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);touch-action:pan-y}.nv-shell{position:relative;width:min(560px,100%);max-height:90vh;overflow:auto;box-sizing:border-box;padding:16px;border:1px solid #7dd2ff38;border-radius:18px;background:linear-gradient(160deg,#0d1428fa,#050812fe);box-shadow:0 24px 80px #000b;overscroll-behavior:contain;-webkit-overflow-scrolling:touch}.nv-title{color:#e0faff;font:900 15px Orbitron,system-ui;letter-spacing:.2em}.nv-sub{margin-top:4px;color:#7e8ba2;font:600 11px Rajdhani,system-ui}.nv-x{position:absolute;right:11px;top:11px;width:34px;height:34px;border:1px solid #ffffff22;border-radius:10px;background:#ffffff0d;color:#c4cede;font-size:20px}.nv-entry{margin-top:14px;padding:13px;border:1px solid var(--a);border-radius:14px;background:linear-gradient(145deg,var(--b),#050914d8)}.nv-v{color:var(--c);font:900 13px Orbitron,system-ui;letter-spacing:.12em}.nv-name{margin-top:3px;color:#edf4ff;font:800 15px Rajdhani,system-ui}.nv-head{margin-top:2px;color:#9eabc0;font:600 11px Rajdhani,system-ui}.nv-gt{margin-top:10px;color:var(--c);font:800 9px Orbitron,system-ui;letter-spacing:.15em}.nv-list{margin:5px 0 0;padding-left:17px;color:#c2ccdb;font:600 11px/1.35 Rajdhani,system-ui}.nv-list li{margin:4px 0}@media(max-width:480px){.nv-card{padding:10px}.nv-top{gap:7px}.nv-btn{padding:7px;font-size:8px}.nv-shell{padding:14px}.nv-entry{padding:11px}.nv-h{line-height:1.25}}
`;document.head.appendChild(s)}
function current(){if(!data||!data.releases)return null;for(var i=0;i<data.releases.length;i++)if(data.releases[i].version===data.currentVersion)return data.releases[i];return data.releases[0]||null}
function colorFor(r){return accents[r&&r.version]||'#7df3ff'}
function tint(c,a){if(/^#[0-9a-f]{6}$/i.test(c)){var n=parseInt(c.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return 'rgba('+r+','+g+','+b+','+a+')'}return 'rgba(80,220,255,'+a+')'}
function close(){if(modal){modal.remove();modal=null}}
function openHistory(){if(!data)return;close();css();modal=document.createElement('div');modal.className='nv-overlay';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');var sh=document.createElement('div');sh.className='nv-shell';sh.onclick=function(e){e.stopPropagation()};var x=document.createElement('button');x.className='nv-x';x.textContent='×';x.onclick=close;sh.appendChild(x);var t=document.createElement('div');t.className='nv-title';t.textContent='UPDATE HISTORY';sh.appendChild(t);var sub=document.createElement('div');sub.className='nv-sub';sub.textContent='NOVA TANKS evolution · newest first';sh.appendChild(sub);data.releases.forEach(function(r){var c=colorFor(r),e=document.createElement('section');e.className='nv-entry';e.style.setProperty('--c',c);e.style.setProperty('--a',tint(c,.34));e.style.setProperty('--b',tint(c,.07));var v=document.createElement('div');v.className='nv-v';v.textContent='v'+r.version+(r.date?' · '+r.date:'');e.appendChild(v);var n=document.createElement('div');n.className='nv-name';n.textContent=r.codename||'';e.appendChild(n);var h=document.createElement('div');h.className='nv-head';h.textContent=r.headline||'';e.appendChild(h);Object.keys(r.groups||{}).forEach(function(g){var gt=document.createElement('div');gt.className='nv-gt';gt.textContent=g.toUpperCase();e.appendChild(gt);var ul=document.createElement('ul');ul.className='nv-list';r.groups[g].forEach(function(it){var li=document.createElement('li');li.textContent=it;ul.appendChild(li)});e.appendChild(ul)});sh.appendChild(e)});modal.appendChild(sh);modal.onclick=close;document.body.appendChild(modal)}
function deployButton(menu){var bs=menu.querySelectorAll('button');for(var i=0;i<bs.length;i++)if((bs[i].textContent||'').indexOf('DEPLOY')>=0)return bs[i];return null}
function firstBullets(r,n){var out=[];if(!r)return out;var gs=r.groups||{},keys=Object.keys(gs);for(var i=0;i<keys.length&&out.length<n;i++){var a=gs[keys[i]]||[];for(var j=0;j<a.length&&out.length<n;j++)out.push(a[j])}return out}
function showroomRelease(){var r=window.__NOVA_SHOWROOM_RELEASE__;if(!r)return null;return {version:r.version,codename:r.codename,date:r.date,headline:r.headline,groups:{'Tank Intelligence Showroom':['The compact Evolution Tree expands in place into the Blackglass intelligence bay.','Browse every chassis with lineage filters, evolution breadcrumbs, catchphrases, tactical descriptions and runtime telemetry.','The animated selected tank uses the actual hull, barrel, weapon and drone definition.'],'Trait Graft Lab':['Foreign lineage genes show build-specific before → after effects rather than generic text.','The simulator reports exact base changes to damage, reload, speed, penetration, range, splash, knockback, drones, HP, mobility, body damage and reduction.'],'Responsive Lobby UX':['Desktop uses library / animated stage / intelligence columns; mobile reflows into a dossier rail, stage and telemetry stack.']}}}
function patchRelease(){var d=window.__NOVA_DRONE_RELEASE__;if(!d)return null;return {version:'1.5.1',codename:'Swarm Discipline',date:'2026-08-08',headline:'Blackglass is polished, drones coordinate properly, and NOVA gains its lobby score.',groups:{'Blackglass Polish':['Portrait-mobile showroom spacing, typography, dossier cards, breadcrumbs, telemetry rows and graft deltas were rebuilt to prevent overlaps and cramped labels.','The showroom stage is shorter and denser on phones while preserving the animated chassis preview and full inspection depth.'],'Drone Discipline':['Idle Controller drones use persistent steering plus return/resume hysteresis instead of oscillating at a hard distance boundary.','Friendly drones reserve different harvest shapes whenever alternatives exist.','Defensive drones automatically intercept incoming hostile combat drones; Forward Observer spotters are exempt from automatic defense.','Manually directed Controller swarms can still attack any enemy drone, including spotters.'],'Music and Presentation':['Added a catchy procedural NOVA lobby theme with a shared motif, syncopated bass and neon groove.','Opening Blackglass smoothly morphs the lobby score into a crystalline intelligence-room variation rather than switching tracks abruptly.','The precision SHOT edge callout is forced screen-upright instead of inheriting indicator rotation.']}}}
function mergeRuntimeRelease(j){var s=showroomRelease(),p=patchRelease(),rs=(j.releases||[]).slice();function add(x){if(!x)return;rs=rs.filter(function(r){return r.version!==x.version});rs.unshift(x)}add(s);add(p);j.releases=rs;if(p)j.currentVersion=p.version;else if(s&&(!j.currentVersion||j.currentVersion<'1.5.0'))j.currentVersion=s.version;return j}
function enhance(){if(!data)return;css();var r=current();if(!r)return;var col=colorFor(r),menu=document.querySelector('#root .menu-grid-bg');if(!menu)return;var title=menu.querySelector('h1');var chip=menu.querySelector('.nv-chip');if(title&&!chip){chip=document.createElement('div');chip.className='nv-chip';title.insertAdjacentElement('afterend',chip)}if(chip){chip.style.setProperty('--nvc',tint(col,.34));chip.style.setProperty('--nvt',col);chip.style.setProperty('--nvd',col);chip.innerHTML='<span class="nv-dot"></span>v'+r.version+' · '+String(r.codename||'').toUpperCase()}
var card=menu.querySelector('.nv-card');if(!card){var d=deployButton(menu);if(d&&d.parentElement){card=document.createElement('div');card.className='nv-card';d.parentElement.insertAdjacentElement('afterend',card)}}if(card){card.style.setProperty('--nvc',tint(col,.28));card.style.setProperty('--nvt',col);card.style.setProperty('--nvd',col);card.style.setProperty('--nvb',tint(col,.08));card.innerHTML='';var top=document.createElement('div');top.className='nv-top';var cp=document.createElement('div');var k=document.createElement('div');k.className='nv-k';k.textContent='LATEST UPDATE · v'+r.version;var h=document.createElement('div');h.className='nv-h';h.textContent=String(r.codename||'').toUpperCase()+' — '+(r.headline||'');cp.appendChild(k);cp.appendChild(h);var b=document.createElement('button');b.className='nv-btn';b.textContent='UPDATE HISTORY';b.onclick=openHistory;top.appendChild(cp);top.appendChild(b);card.appendChild(top);var bullets=firstBullets(r,3);if(bullets.length){var sm=document.createElement('div');sm.className='nv-s';bullets.forEach(function(text){var sp=document.createElement('span');sp.textContent=text;sm.appendChild(sp)});card.appendChild(sm)}}var ds=menu.querySelectorAll('div');for(var j=0;j<ds.length;j++){var tx=(ds[j].textContent||'').trim();if(/^NOVA TANKS v\d+\.\d+(?:\.\d+)?\b/.test(tx)&&ds[j].children.length===0){ds[j].textContent='NOVA TANKS v'+r.version+' · '+String(r.codename||'').toUpperCase()+' · EVOLVE · SPLICE · ASCEND';break}}}
function start(){fetch('./nova-updates/releases.json',{cache:'no-store'}).then(function(r){return r.json()}).then(function(j){data=mergeRuntimeRelease(j);enhance();var root=document.getElementById('root');if(root){var q=false;new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;enhance()})}).observe(root,{childList:true,subtree:true})}}).catch(function(e){console.error('[NOVA] release history unavailable',e)})}
document.addEventListener('keydown',function(e){if(e.key==='Escape')close()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
