/* NOVA TANKS v1.7.6 — First Contact
 * Owns the front-door layout and the stable extension contract for future lobby features.
 * Slots: hero, primary, briefing, actions, feature-rail, intel, utility, footer.
 */
(function(){'use strict';
var VERSION='1.7.6',CODENAME='First Contact',data=null,modal=null,timer=0,menuRef=null,pendingActions={},pendingCards={};
window.__NOVA_LOBBY_RELEASE__={version:VERSION,codename:CODENAME,date:'2026-08-08',headline:'The first screen becomes a launch bay instead of a feature wall.',groups:{'First Contact':['The opening view leads with identity, live field status and one dominant Deploy action.','Blackglass, controls/audio and update history are clear secondary destinations that open only when requested.','A compact rotating briefing keeps the lobby alive without competing with play.'],'Lobby Architecture':['Stable named slots define where future lobby features belong.','window.NOVALobby exposes slot(), registerAction() and registerCard() so later runtime layers do not need brittle text-node insertion.','Legacy Evolution Tree and Genome Forge clutter stays out of first contact; Blackglass remains the canonical tank-intelligence destination.']}};
function css(){if(document.getElementById('nova-history-css'))return;var s=document.createElement('style');s.id='nova-history-css';s.textContent=`
.menu-grid-bg.nv-menu{scrollbar-width:none}.menu-grid-bg.nv-menu::-webkit-scrollbar{display:none}.nv-shell{max-width:720px!important;padding:max(24px,env(safe-area-inset-top)) clamp(18px,5vw,38px) max(22px,env(safe-area-inset-bottom))!important;justify-content:flex-start}.nv-hero{width:100%;margin-top:auto;text-align:center}.nv-hero>div:first-child{font-size:9px!important;letter-spacing:.4em!important;color:#9eb2d4!important}.nv-hero>div:first-child:before{content:'WELCOME, PILOT · ';color:#7df3ff}.nv-hero h1{margin-top:8px!important;font-size:clamp(42px,11vw,66px)!important;letter-spacing:.055em!important}.nv-hero p{max-width:520px;margin:9px auto 0!important;color:#91a0b8!important;font-size:clamp(12px,3vw,14px)!important;line-height:1.35}.nv-primary{width:min(100%,470px)!important;margin-top:21px!important}.nv-primary>button{position:relative;min-height:58px;overflow:hidden}.nv-primary>button:after{content:'';position:absolute;inset:-2px;background:linear-gradient(105deg,transparent 25%,#ffffff55 45%,transparent 64%);transform:translateX(-125%);animation:nvSweep 4.8s ease-in-out infinite;pointer-events:none}@keyframes nvSweep{0%,58%{transform:translateX(-125%)}78%,100%{transform:translateX(125%)}}
.nv-brief{width:min(100%,560px);box-sizing:border-box;margin-top:13px;padding:10px 12px;border:1px solid #7df3ff24;border-radius:13px;background:linear-gradient(110deg,#10243ab8,#080c1ad1);text-align:left;box-shadow:inset 0 1px #ffffff0a}.nv-brief-top{display:flex;align-items:center;gap:7px}.nv-live{width:6px;height:6px;border-radius:50%;background:#75f0a3;box-shadow:0 0 10px #75f0a3;animation:nvLive 1.7s ease-in-out infinite}@keyframes nvLive{50%{opacity:.35}}.nv-brief-k,.nv-brief-v{font:800 8px Orbitron,system-ui;letter-spacing:.14em}.nv-brief-k{color:#7df3ff}.nv-brief-v{margin-left:auto;color:#61738c}.nv-brief-line{min-height:29px;margin-top:5px;font:700 11px/1.3 Rajdhani,system-ui;color:#d2deed;transition:.18s}.nv-brief-line.swap{opacity:0;transform:translateY(3px)}
.nv-actions{width:min(100%,590px);margin-top:11px}.nv-action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.nv-action{min-width:0;padding:10px 9px;border:1px solid #ffffff16;border-radius:13px;background:linear-gradient(145deg,#111d32d1,#070b17e8);color:#dce9f7;text-align:left;touch-action:manipulation}.nv-action:active{transform:scale(.97)}.nv-action.on{border-color:#7df3ff66;box-shadow:0 0 18px #4de3ff16}.nv-ai{display:block;font-size:16px;color:#7df3ff}.nv-ak{display:block;margin-top:5px;font:900 8px Orbitron,system-ui;letter-spacing:.1em;color:#dff8ff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nv-as{display:block;margin-top:3px;font:600 9.5px Rajdhani,system-ui;color:#7889a2}.nv-rail{display:none;width:min(100%,590px);margin-top:8px;gap:8px}.nv-rail.has-items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.nv-feature{padding:10px;border:1px solid #ffffff16;border-radius:13px;background:#09101de0;text-align:left}.nv-fk{font:900 8px Orbitron,system-ui;letter-spacing:.12em;color:#90eaff}.nv-fh{margin-top:4px;font:700 11px/1.2 Rajdhani,system-ui;color:#d4deea}
.nv-intel{display:none!important;width:100%!important;margin-top:14px!important}.nv-intel.nvs-open{display:block!important}.nv-intel>.nvs-launch{display:none!important}.nv-intel>:not(.nvs-launch):not(.nvs-panel){display:none!important}.nv-intel.nvs-open .nvs-panel{margin-top:0!important}.nv-forge{display:none!important}.nv-util{display:none!important;width:min(100%,590px)!important;margin:12px auto 0!important}.nv-util.open{display:block!important;animation:riseFade .24s ease both}.nv-footer{margin-top:auto!important;padding-top:16px!important;font-size:8px!important;letter-spacing:.13em!important;color:#3e4b61!important}.nv-chip,.nv-card{display:none!important}
.nv-overlay{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px 14px;background:#010309df;backdrop-filter:blur(12px);touch-action:pan-y}.nv-history{position:relative;width:min(580px,100%);max-height:90vh;overflow:auto;padding:16px;border:1px solid #7dd2ff38;border-radius:18px;background:linear-gradient(160deg,#0d1428fa,#050812fe);box-sizing:border-box}.nv-ht{font:900 15px Orbitron,system-ui;letter-spacing:.18em;color:#e0faff}.nv-hs{margin-top:4px;font:600 11px Rajdhani,system-ui;color:#7e8ba2}.nv-x{position:absolute;right:11px;top:11px;width:34px;height:34px;border:1px solid #ffffff22;border-radius:10px;background:#ffffff0d;color:#c4cede;font-size:20px}.nv-entry{margin-top:13px;padding:12px;border:1px solid #7df3ff28;border-radius:13px;background:#09101dcc}.nv-v{font:900 11px Orbitron,system-ui;letter-spacing:.1em;color:#7df3ff}.nv-name{margin-top:3px;font:800 14px Rajdhani,system-ui;color:#edf4ff}.nv-head{margin-top:2px;font:600 11px/1.3 Rajdhani,system-ui;color:#9eabc0}.nv-gt{margin-top:9px;font:800 8px Orbitron,system-ui;letter-spacing:.12em;color:#83dff6}.nv-list{margin:4px 0 0;padding-left:17px;font:600 10.5px/1.35 Rajdhani,system-ui;color:#c2ccdb}.nv-list li{margin:3px 0}
@media(max-width:470px){.nv-shell{padding-top:max(18px,env(safe-area-inset-top))!important}.nv-hero h1{font-size:42px!important}.nv-primary{margin-top:17px!important}.nv-primary>button{min-height:54px}.nv-action-grid{gap:6px}.nv-action{padding:9px 7px}.nv-as{display:none}.nv-brief{padding:9px 10px}.nv-brief-line{font-size:10.5px}.nv-rail.has-items{grid-template-columns:1fr}}@media(max-height:690px) and (max-width:520px){.nv-shell{padding-top:max(14px,env(safe-area-inset-top))!important;padding-bottom:max(12px,env(safe-area-inset-bottom))!important}.nv-hero h1{font-size:38px!important}.nv-hero p{margin-top:5px!important}.nv-primary{margin-top:12px!important}.nv-brief{margin-top:8px}.nv-actions{margin-top:7px}.nv-footer{padding-top:9px!important}}
`;document.head.appendChild(s)}
function cmp(a,b){a=String(a||'0').split('.').map(Number);b=String(b||'0').split('.').map(Number);for(var i=0;i<Math.max(a.length,b.length);i++){var d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
function merge(j){var rs=(j&&j.releases||[]).slice(),p=window.__NOVA_PERFORMANCE_RELEASE__;if(p){rs=rs.filter(function(r){return r.version!==p.version});rs.push({version:p.version,codename:p.codename,date:p.date,headline:p.headline,groups:{Performance:(p.guarantees||[]).slice()}})}var l=window.__NOVA_LOBBY_RELEASE__;rs=rs.filter(function(r){return r.version!==l.version});rs.push(l);rs.sort(function(a,b){return cmp(b.version,a.version)});return{currentVersion:l.version,releases:rs}}
function current(){return data&&data.releases&&data.releases[0]||window.__NOVA_LOBBY_RELEASE__}
function leaf(root,text){var ds=root.querySelectorAll('div');for(var i=0;i<ds.length;i++)if(!ds[i].children.length&&(ds[i].textContent||'').trim()===text)return ds[i];return null}
function top(shell,node){if(!node)return null;while(node&&node.parentElement!==shell)node=node.parentElement;return node&&node.parentElement===shell?node:null}
function shell(menu,title){var n=title;while(n&&n.parentElement!==menu)n=n.parentElement;return n}
function deploy(menu){var bs=menu.querySelectorAll('button');for(var i=0;i<bs.length;i++)if((bs[i].textContent||'').indexOf('DEPLOY')>=0)return bs[i]}
function footer(menu){var ds=menu.querySelectorAll('div');for(var i=0;i<ds.length;i++)if(!ds[i].children.length&&/^NOVA TANKS v\d+\.\d+/.test((ds[i].textContent||'').trim()))return ds[i]}
function button(icon,label,sub,fn,id){var b=document.createElement('button');b.type='button';b.className='nv-action';b.dataset.novaAction=id;b.innerHTML='<span class="nv-ai"></span><span class="nv-ak"></span><span class="nv-as"></span>';b.querySelector('.nv-ai').textContent=icon;b.querySelector('.nv-ak').textContent=label;b.querySelector('.nv-as').textContent=sub;b.onclick=fn;return b}
function status(r){var a=[];if(r.headline)a.push(r.headline);Object.keys(r.groups||{}).forEach(function(k){(r.groups[k]||[]).forEach(function(x){if(a.length<4)a.push(x)})});return a}
function tick(menu,r){if(menuRef!==menu){if(timer)clearInterval(timer);menuRef=menu;timer=0}var el=menu.querySelector('.nv-brief-line'),lines=status(r),i=0;if(!el)return;el.textContent=lines[0]||'';if(timer||lines.length<2)return;timer=setInterval(function(){if(!menuRef||!menuRef.isConnected){clearInterval(timer);timer=0;menuRef=null;return}el.classList.add('swap');setTimeout(function(){if(!el.isConnected)return;i=(i+1)%lines.length;el.textContent=lines[i];el.classList.remove('swap')},180)},4200)}
function openHistory(){if(!data)return;closeHistory();modal=document.createElement('div');modal.className='nv-overlay';var h=document.createElement('div');h.className='nv-history';h.onclick=function(e){e.stopPropagation()};h.innerHTML='<button class="nv-x" aria-label="Close">×</button><div class="nv-ht">UPDATE HISTORY</div><div class="nv-hs">NOVA TANKS evolution · newest first</div>';h.querySelector('.nv-x').onclick=closeHistory;data.releases.forEach(function(r){var e=document.createElement('section');e.className='nv-entry';e.innerHTML='<div class="nv-v"></div><div class="nv-name"></div><div class="nv-head"></div>';e.querySelector('.nv-v').textContent='v'+r.version+(r.date?' · '+r.date:'');e.querySelector('.nv-name').textContent=r.codename||'';e.querySelector('.nv-head').textContent=r.headline||'';Object.keys(r.groups||{}).forEach(function(g){var k=document.createElement('div');k.className='nv-gt';k.textContent=g.toUpperCase();e.appendChild(k);var ul=document.createElement('ul');ul.className='nv-list';(r.groups[g]||[]).forEach(function(x){var li=document.createElement('li');li.textContent=x;ul.appendChild(li)});e.appendChild(ul)});h.appendChild(e)});modal.appendChild(h);modal.onclick=closeHistory;document.body.appendChild(modal)}
function closeHistory(){if(modal){modal.remove();modal=null}}
function slot(name){var m=document.querySelector('#root .menu-grid-bg');return m&&m.querySelector('[data-nova-slot="'+String(name)+'"]')}
function renderExtensions(menu){var grid=menu.querySelector('.nv-action-grid'),rail=menu.querySelector('.nv-rail');if(!grid||!rail)return;Object.keys(pendingActions).forEach(function(id){if(grid.querySelector('[data-nova-action="'+id+'"]'))return;var a=pendingActions[id];grid.appendChild(button(a.icon||'◇',a.label||id,a.sub||'',function(){if(a.onClick)a.onClick({menu:menu,slot:slot});else if(a.href)location.href=a.href},id))});Object.keys(pendingCards).forEach(function(id){if(rail.querySelector('[data-nova-card="'+id+'"]'))return;var c=pendingCards[id],e=document.createElement('div');e.className='nv-feature';e.dataset.novaCard=id;e.innerHTML='<div class="nv-fk"></div><div class="nv-fh"></div>';e.querySelector('.nv-fk').textContent=c.kicker||'NEW';e.querySelector('.nv-fh').textContent=c.headline||'';if(c.onClick){e.style.cursor='pointer';e.onclick=function(){c.onClick({menu:menu,slot:slot})}}rail.appendChild(e)});rail.classList.toggle('has-items',!!rail.children.length)}
function enhance(){css();var menu=document.querySelector('#root .menu-grid-bg');if(!menu)return;var title=menu.querySelector('h1');if(!title)return;var sh=shell(menu,title);menu.classList.add('nv-menu');sh.classList.add('nv-shell');var hero=title.parentElement;hero.classList.add('nv-hero');hero.dataset.novaSlot='hero';var tag=hero.querySelector('p');if(tag)tag.textContent='Evolve fast. Read the battlefield. Build something dangerous.';var d=deploy(menu),pri=top(sh,d);if(pri){pri.classList.add('nv-primary');pri.dataset.novaSlot='primary'}var intel=menu.querySelector('.nvs-host');if(intel){intel.classList.add('nv-intel');intel.dataset.novaSlot='intel'}var f=top(sh,leaf(sh,'LATE-GAME GENOME FORGE'));if(f)f.classList.add('nv-forge');var util=top(sh,leaf(sh,'— HOW TO PLAY —'));if(util){util.classList.add('nv-util');util.dataset.novaSlot='utility'}var ft=footer(menu);if(ft){ft.classList.add('nv-footer');ft.dataset.novaSlot='footer';ft.textContent='NOVA TANKS v'+VERSION+' · FIRST CONTACT · EVOLVE · ADAPT · ASCEND'}menu.querySelectorAll('.nv-chip,.nv-card').forEach(function(e){e.remove()});var br=slot('briefing');if(!br&&pri){br=document.createElement('section');br.className='nv-brief';br.dataset.novaSlot='briefing';br.innerHTML='<div class="nv-brief-top"><span class="nv-live"></span><span class="nv-brief-k">FIELD BRIEFING</span><span class="nv-brief-v"></span></div><div class="nv-brief-line"></div>';pri.insertAdjacentElement('afterend',br)}var r=current();if(br){br.querySelector('.nv-brief-v').textContent='v'+r.version+' · '+String(r.codename||'').toUpperCase();tick(menu,r)}var acts=slot('actions');if(!acts&&br){acts=document.createElement('section');acts.className='nv-actions';acts.dataset.novaSlot='actions';acts.innerHTML='<div class="nv-action-grid"></div>';br.insertAdjacentElement('afterend',acts);var grid=acts.firstChild,ib,ub;ib=button('⌬','BLACKGLASS','Tanks & builds',function(){var h=slot('intel'),l=h&&h.querySelector('.nvs-launch');if(l){l.click();requestAnimationFrame(function(){ib.classList.toggle('on',h.classList.contains('nvs-open'));if(h.classList.contains('nvs-open'))h.scrollIntoView({behavior:'smooth',block:'start'})})}},'blackglass');ub=button('⚙','CONTROLS','Input & audio',function(){var u=slot('utility');if(u){u.classList.toggle('open');ub.classList.toggle('on',u.classList.contains('open'));if(u.classList.contains('open'))u.scrollIntoView({behavior:'smooth',block:'nearest'})}},'controls');grid.appendChild(ib);grid.appendChild(ub);grid.appendChild(button('↻','UPDATES','Version history',openHistory,'updates'))}var rail=slot('feature-rail');if(!rail&&acts){rail=document.createElement('section');rail.className='nv-rail';rail.dataset.novaSlot='feature-rail';acts.insertAdjacentElement('afterend',rail)}renderExtensions(menu)}
window.NOVALobby={version:VERSION,slot:slot,openHistory:openHistory,refresh:enhance,registerAction:function(id,s){if(id&&s){pendingActions[id]=s;enhance()}},registerCard:function(id,s){if(id&&s){pendingCards[id]=s;enhance()}},removeAction:function(id){delete pendingActions[id];var e=document.querySelector('[data-nova-action="'+id+'"]');if(e)e.remove()},removeCard:function(id){delete pendingCards[id];var e=document.querySelector('[data-nova-card="'+id+'"]');if(e)e.remove()}};
function start(){fetch('./nova-updates/releases.json',{cache:'no-store'}).then(function(r){return r.json()}).then(function(j){data=merge(j);enhance()}).catch(function(){data=merge({releases:[]});enhance()});var root=document.getElementById('root');if(root){var q=0;new MutationObserver(function(){if(q)return;q=1;requestAnimationFrame(function(){q=0;enhance()})}).observe(root,{childList:true,subtree:true})}}
document.addEventListener('keydown',function(e){if(e.key==='Escape'){if(modal)closeHistory();else{var u=slot('utility');if(u)u.classList.remove('open');var i=slot('intel');if(i&&i.classList.contains('nvs-open')){var l=i.querySelector('.nvs-launch');if(l)l.click()}}}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
