/* NOVA TANKS v1.10.2 — War Room
 * Efficient live level-30 bot battlefield behind the lobby.
 * Separate presentation simulation: no player input, audio, progression or gameplay state.
 */
(function(){
'use strict';
if(window.__NOVA_WAR_ROOM__)return;
var VERSION='1.10.2',CODENAME='War Room',LEVEL=30,TAU=Math.PI*2;
var BOT_MOBILE=12,BOT_DESKTOP=18,MAX_BULLETS=84,MAX_FX=72,PAN_SECONDS=38;
var REDUCED=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
var CLASS_IDS=['scout','twin','cannon','marksman','carrier','guard','minigun','shotgun','bomber','demolisher','railgun','ghost','overlord','warden','fortress','juggernaut','tempest','needlestorm','breachlord','flakmaster','clusterking','siegebomber','annihilator','quake','singularity','prism','specter','assassin','hivemind','broodmother','citadel','valkyrie','bastion','aegis','meteor','ravager'];
var LINE_COLORS={origin:'#dce9ff',gunner:'#4de3ff',cannon:'#ffb45e',sniper:'#b06bff',controller:'#54e38a',guardian:'#ff6ea9'};
var classes=null,CLASSES={},lineageFor=function(id){if(id==='scout')return'origin';if(['twin','minigun','shotgun','tempest','needlestorm','breachlord','flakmaster'].indexOf(id)>=0)return'gunner';if(['cannon','bomber','demolisher','clusterking','siegebomber','annihilator','quake'].indexOf(id)>=0)return'cannon';if(['marksman','railgun','ghost','singularity','prism','specter','assassin'].indexOf(id)>=0)return'sniper';if(['carrier','overlord','warden','hivemind','broodmother','citadel','valkyrie'].indexOf(id)>=0)return'controller';return'guardian';};
try{var make=window.__novaMakeRequire;if(make){classes=make('war-room')('./game/classes');CLASSES=classes&&classes.CLASSES||{};if(classes&&classes.lineageForClass)lineageFor=function(id){return id==='scout'?'origin':classes.lineageForClass(id)||'origin';};}}catch(_){classes=null;}
window.__NOVA_VERSION=VERSION;
window.__NOVA_WAR_ROOM_RELEASE__={version:VERSION,codename:CODENAME,date:'2026-08-09',headline:'The lobby now overlooks an active level-30 battlefield without running a second copy of the real match engine.',groups:{
 'Live battlefield':['A rotating roster spans all 36 canonical tank classes; 12 bots run on compact/mobile viewports and 18 on larger screens, all represented at level 30.','Bots continuously acquire one another, move, fire, use lineage-flavored abilities, die and respawn into different classes so the scene keeps revealing new combatants.','Cannon impacts explode, Snipers throw long precision traces, Gunners burst, Controllers carry small drone satellites and Guardians flash defensive fields.'],
 'Cinematic background':['The spectator camera drifts through the battlefield over a 38-second vertical pass, revealing different cover, craters and engagements while the lobby UI remains fixed above it.','Tracers, muzzle flashes, debris, smoke sparks, explosions and distant signal lights add motion without labels or combat HUD competing with Deploy.','The battlefield is intentionally darkened and non-interactive: it communicates a war outside the launch bay, not a second screen the player must read.'],
 'Performance contract':['The diorama is a bounded presentation simulation, not a second Game instance: it owns no audio, input, saves, progression, network or full AI systems.','Rendering is capped at 24 FPS on compact/mobile screens and 30 FPS elsewhere, uses a reduced internal canvas scale, fixed bullet/effect pools, pauses while the tab is hidden and stops when the lobby leaves the DOM.','prefers-reduced-motion receives one composed still battlefield frame with no camera movement.']
}};
function css(){if(document.getElementById('nova-war-room-css'))return;var s=document.createElement('style');s.id='nova-war-room-css';s.textContent=`
.menu-grid-bg{position:relative!important}.nova-war-room{position:absolute;inset:0;width:100%;height:100%;z-index:0;pointer-events:none!important;touch-action:none;opacity:.52;filter:saturate(.82) contrast(1.06);contain:strict}.nova-war-room-shade{position:absolute;inset:0;z-index:1;pointer-events:none;background:radial-gradient(circle at 50% 42%,rgba(2,5,12,.36),rgba(2,5,12,.62) 48%,rgba(2,5,12,.84) 100%),linear-gradient(180deg,rgba(3,6,14,.30),rgba(3,6,14,.60));}.nv-shell,.nv-hero,.nv-primary,.nv-brief,.nv-action-grid,[data-nova-slot]{position:relative;z-index:2}@media(max-width:600px){.nova-war-room{opacity:.43}}@media(prefers-reduced-motion:reduce){.nova-war-room{opacity:.42}}
`;document.head.appendChild(s);}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function rand(a,b){return a+Math.random()*(b-a);}
function d2(a,b){var x=b.x-a.x,y=b.y-a.y;return x*x+y*y;}
function rgba(hex,a){var h=String(hex||'#ffffff').replace('#','');if(h.length===3)h=h.split('').map(function(x){return x+x}).join('');var n=parseInt(h,16);if(!Number.isFinite(n))return'rgba(255,255,255,'+a+')';return'rgba('+((n>>16)&255)+','+((n>>8)&255)+','+(n&255)+','+a+')';}
function profile(id){var c=CLASSES[id]||{},lin=lineageFor(id),bullet=c.bullet||{};var p={id:id,lineage:lin,color:c.color||LINE_COLORS[lin]||'#dce9ff',size:clamp(Number(c.size)||15,10,25),speed:clamp(Number(c.speed)||150,95,235),reload:clamp(Number(bullet.reload)||.72,.16,1.65),damage:clamp(Number(bullet.damage)||18,7,48)};if(lin==='sniper'){p.range=620;p.reload=Math.max(.95,p.reload);p.damage*=1.28;}else if(lin==='cannon'){p.range=430;p.reload=Math.max(.78,p.reload);p.damage*=1.15;}else if(lin==='controller'){p.range=390;}else if(lin==='guardian'){p.range=350;p.speed*=.84;}else{p.range=390;}return p;}
function Sim(canvas,menu){this.canvas=canvas;this.menu=menu;this.ctx=canvas.getContext('2d',{alpha:true});this.w=0;this.h=0;this.scale=1;this.worldW=1500;this.worldH=1500;this.bots=[];this.bullets=[];this.fx=[];this.cover=[];this.craters=[];this.roster=0;this.time=0;this.last=0;this.raf=0;this.frameMs=33.34;this.cam={x:750,y:940};this.destroyed=false;this.resize();this.seedWorld();this.seedBots();}
Sim.prototype.resize=function(){var r=this.menu.getBoundingClientRect(),w=Math.max(1,Math.round(r.width||innerWidth||800)),h=Math.max(1,Math.round(r.height||innerHeight||600)),compact=w<650||h<590;this.w=w;this.h=h;this.frameMs=1000/(compact?24:30);this.scale=(compact?.68:.82)*Math.min(1.25,window.devicePixelRatio||1);this.canvas.width=Math.max(1,Math.round(w*this.scale));this.canvas.height=Math.max(1,Math.round(h*this.scale));this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';};
Sim.prototype.seedWorld=function(){var i;for(i=0;i<28;i++)this.cover.push({x:rand(100,1400),y:rand(80,1420),w:rand(45,130),h:rand(24,70),a:rand(-.5,.5)});for(i=0;i<34;i++)this.craters.push({x:rand(30,1470),y:rand(30,1470),r:rand(12,42),a:rand(.04,.12)});};
Sim.prototype.spawnBot=function(slot,delay){var id=CLASS_IDS[this.roster++%CLASS_IDS.length],p=profile(id),edge=slot%4,x=edge===0?rand(80,1420):edge===2?rand(80,1420):edge===1?rand(90,320):rand(1180,1410),y=edge===0?rand(1040,1420):edge===2?rand(80,420):rand(80,1420);return{id:slot+1,cls:id,level:LEVEL,lineage:p.lineage,color:p.color,size:p.size,speed:p.speed,range:p.range,reload:p.reload,damage:p.damage,x:x,y:y,vx:0,vy:0,angle:rand(0,TAU),hp:100,maxHp:100,alive:!delay,respawn:delay||0,fireCd:rand(0,p.reload),abilityCd:rand(1.2,5.5),target:null,flash:0,shield:0,drones:p.lineage==='controller'?[rand(0,TAU),rand(0,TAU)]:null};};
Sim.prototype.seedBots=function(){var n=(this.w<650||this.h<590)?BOT_MOBILE:BOT_DESKTOP;for(var i=0;i<n;i++)this.bots.push(this.spawnBot(i,0));};
Sim.prototype.chooseTarget=function(b){var best=null,bs=Infinity,rr=b.range*b.range*1.35;for(var i=0;i<this.bots.length;i++){var t=this.bots[i];if(t===b||!t.alive)continue;var q=d2(b,t);if(q<bs&&q<rr){bs=q;best=t;}}b.target=best;return best;};
Sim.prototype.pushFx=function(type,x,y,color,size,life,vx,vy){if(this.fx.length>=MAX_FX)this.fx.shift();this.fx.push({type:type,x:x,y:y,color:color||'#fff',size:size||12,life:life||.4,max:life||.4,vx:vx||0,vy:vy||0});};
Sim.prototype.fire=function(b,t){if(this.bullets.length>=MAX_BULLETS)this.bullets.shift();var dx=t.x-b.x,dy=t.y-b.y,m=Math.hypot(dx,dy)||1,lin=b.lineage,speed=lin==='cannon'?275:lin==='sniper'?760:lin==='gunner'?470:390,explosive=lin==='cannon',ttl=lin==='sniper'?1.0:1.55;b.flash=.08;
 if(lin==='sniper'){this.pushFx('trace',b.x,b.y,b.color,m,.18,dx,dy);t.hp-=b.damage*.72;if(t.hp<=0)this.kill(t,b);return;}
 var count=lin==='gunner'&&Math.random()<.28?2:1;for(var k=0;k<count;k++){var spread=(k?rand(-.07,.07):rand(-.025,.025)),ca=Math.cos(spread),sa=Math.sin(spread),ux=dx/m,uy=dy/m,sx=ux*ca-uy*sa,sy=ux*sa+uy*ca;this.bullets.push({x:b.x+sx*(b.size+4),y:b.y+sy*(b.size+4),vx:sx*speed,vy:sy*speed,r:explosive?4:2.1,damage:b.damage*(count>1?.58:1),owner:b,life:ttl,explosive:explosive,color:b.color});}
};
Sim.prototype.kill=function(t,killer){if(!t.alive)return;t.alive=false;t.respawn=rand(1.25,2.4);t.hp=0;t.target=null;this.pushFx('boom',t.x,t.y,killer?killer.color:t.color,42,.65);for(var i=0;i<5;i++)this.pushFx('spark',t.x,t.y,t.color,3,rand(.25,.6),rand(-90,90),rand(-90,90));};
Sim.prototype.ability=function(b){b.abilityCd=rand(5.2,9.5);var lin=b.lineage;if(lin==='guardian'){b.shield=1.1;this.pushFx('shield',b.x,b.y,b.color,b.size+18,.55);}else if(lin==='cannon'){this.pushFx('boom',b.x+Math.cos(b.angle)*70,b.y+Math.sin(b.angle)*70,b.color,30,.45);}else if(lin==='sniper'&&b.target){this.pushFx('trace',b.x,b.y,b.color,Math.hypot(b.target.x-b.x,b.target.y-b.y),.24,b.target.x-b.x,b.target.y-b.y);}else if(lin==='gunner'){b.fireCd=Math.min(b.fireCd,.04);this.pushFx('spark',b.x,b.y,b.color,6,.25);}else if(lin==='controller'){this.pushFx('ring',b.x,b.y,b.color,38,.5);}else{b.vx+=Math.cos(b.angle)*80;b.vy+=Math.sin(b.angle)*80;this.pushFx('ring',b.x,b.y,b.color,25,.35);}};
Sim.prototype.stepBots=function(dt){for(var i=0;i<this.bots.length;i++){var b=this.bots[i];if(!b.alive){b.respawn-=dt;if(b.respawn<=0){var fresh=this.spawnBot(i,0);Object.assign(b,fresh);}continue;}b.fireCd-=dt;b.abilityCd-=dt;b.flash=Math.max(0,b.flash-dt);b.shield=Math.max(0,b.shield-dt);var t=b.target;if(!t||!t.alive||d2(b,t)>b.range*b.range*1.8)t=this.chooseTarget(b);var ax=0,ay=0;if(t){var dx=t.x-b.x,dy=t.y-b.y,m=Math.hypot(dx,dy)||1,ideal=b.range*(b.lineage==='sniper'?.70:b.lineage==='cannon'?.58:.48),push=clamp((m-ideal)/Math.max(80,ideal),-1,1);ax+=dx/m*push;ay+=dy/m*push;b.angle=Math.atan2(dy,dx);if(m<b.range&&b.fireCd<=0){this.fire(b,t);b.fireCd=b.reload*rand(.86,1.16);}if(b.abilityCd<=0)this.ability(b);}else{b.angle+=rand(-.6,.6)*dt;ax+=Math.cos(b.angle)*.22;ay+=Math.sin(b.angle)*.22;}
 for(var j=0;j<this.bots.length;j++){var o=this.bots[j];if(o===b||!o.alive)continue;var sx=b.x-o.x,sy=b.y-o.y,sd=sx*sx+sy*sy;if(sd<62*62&&sd>1){var sm=Math.sqrt(sd),f=(62-sm)/62;ax+=sx/sm*f*.8;ay+=sy/sm*f*.8;}}
 var k=1-Math.exp(-3.2*dt),spd=b.speed*.44;b.vx+=(ax*spd-b.vx)*k;b.vy+=(ay*spd-b.vy)*k;b.x=clamp(b.x+b.vx*dt,35,this.worldW-35);b.y=clamp(b.y+b.vy*dt,35,this.worldH-35);}
};
Sim.prototype.stepBullets=function(dt){for(var i=this.bullets.length-1;i>=0;i--){var p=this.bullets[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0||p.x<0||p.x>this.worldW||p.y<0||p.y>this.worldH){this.bullets.splice(i,1);continue;}var hit=null;for(var j=0;j<this.bots.length;j++){var t=this.bots[j];if(!t.alive||t===p.owner)continue;var rr=t.size+p.r;if(d2(p,t)<=rr*rr){hit=t;break;}}if(hit){var dmg=p.damage*(hit.shield>0?.42:1);hit.hp-=dmg;this.pushFx(p.explosive?'boom':'spark',p.x,p.y,p.color,p.explosive?26:4,p.explosive?.42:.18);if(hit.hp<=0)this.kill(hit,p.owner);this.bullets.splice(i,1);}}
};
Sim.prototype.stepFx=function(dt){for(var i=this.fx.length-1;i>=0;i--){var f=this.fx[i];f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=Math.max(0,1-dt*2.5);f.vy*=Math.max(0,1-dt*2.5);if(f.life<=0)this.fx.splice(i,1);}};
Sim.prototype.stepCamera=function(){var phase=(this.time%PAN_SECONDS)/PAN_SECONDS,e=.5-.5*Math.cos(phase*TAU),travel=this.worldH*.42;this.cam.x=this.worldW*.5+Math.sin(this.time*.055)*this.worldW*.055;this.cam.y=this.worldH*.77-e*travel;};
Sim.prototype.update=function(dt){this.time+=dt;this.stepCamera();this.stepBots(dt);this.stepBullets(dt);this.stepFx(dt);};
Sim.prototype.world=function(x,y){var viewW=this.w*1.22,viewH=this.h*1.22;return{x:(x-this.cam.x)/viewW*this.w+this.w*.5,y:(y-this.cam.y)/viewH*this.h+this.h*.5,s:this.w/viewW};};
Sim.prototype.drawTank=function(ctx,b){var p=this.world(b.x,b.y),s=p.s,sz=b.size*s;if(p.x<-60||p.x>this.w+60||p.y<-60||p.y>this.h+60)return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(b.angle);ctx.globalAlpha=.78;ctx.fillStyle=rgba(b.color,.20);ctx.beginPath();ctx.arc(0,0,sz*1.75,0,TAU);ctx.fill();ctx.fillStyle=rgba(b.color,.82);ctx.strokeStyle=rgba('#dff8ff',.28);ctx.lineWidth=1;ctx.beginPath();if(b.lineage==='cannon'){ctx.rect(-sz*.9,-sz*.65,sz*1.8,sz*1.3);}else if(b.lineage==='sniper'){ctx.moveTo(sz,0);ctx.lineTo(-sz*.75,-sz*.65);ctx.lineTo(-sz*.55,0);ctx.lineTo(-sz*.75,sz*.65);ctx.closePath();}else if(b.lineage==='controller'){for(var i=0;i<6;i++){var a=i/6*TAU;ctx.lineTo(Math.cos(a)*sz*(i%2?1:.72),Math.sin(a)*sz*(i%2?1:.72));}ctx.closePath();}else{ctx.arc(0,0,sz,0,TAU);}ctx.fill();ctx.stroke();ctx.fillStyle=rgba('#ffffff',b.flash>0?.78:.23);ctx.fillRect(sz*.25,-1,sz*1.55,2);if(b.shield>0){ctx.strokeStyle=rgba(b.color,.55);ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,sz*1.55,-1.1,1.1);ctx.stroke();}if(b.drones){for(var d=0;d<b.drones.length;d++){var da=b.drones[d]+this.time*(d?1.4:-1.2),rr=sz*2.2;ctx.fillStyle=rgba(b.color,.72);ctx.beginPath();ctx.arc(Math.cos(da)*rr,Math.sin(da)*rr,Math.max(1.5,sz*.18),0,TAU);ctx.fill();}}
 ctx.restore();};
Sim.prototype.draw=function(){var c=this.ctx;if(!c)return;c.setTransform(this.scale,0,0,this.scale,0,0);c.clearRect(0,0,this.w,this.h);var grd=c.createLinearGradient(0,0,0,this.h);grd.addColorStop(0,'#06101c');grd.addColorStop(.55,'#08131d');grd.addColorStop(1,'#03070d');c.fillStyle=grd;c.fillRect(0,0,this.w,this.h);
 c.save();c.globalAlpha=.14;c.strokeStyle='#75d8ff';c.lineWidth=.55;var gy=((this.time*4)%44);for(var x=-44;x<this.w+44;x+=44){c.beginPath();c.moveTo(x,0);c.lineTo(x,this.h);c.stroke();}for(var y=-44+gy;y<this.h+44;y+=44){c.beginPath();c.moveTo(0,y);c.lineTo(this.w,y);c.stroke();}c.restore();
 for(var i=0;i<this.craters.length;i++){var cr=this.craters[i],cp=this.world(cr.x,cr.y);if(cp.x<0||cp.x>this.w||cp.y<0||cp.y>this.h)continue;c.fillStyle='rgba(0,0,0,'+cr.a+')';c.beginPath();c.ellipse(cp.x,cp.y,cr.r*cp.s,cr.r*.55*cp.s,0,0,TAU);c.fill();}
 c.save();c.fillStyle='rgba(60,94,113,.16)';c.strokeStyle='rgba(125,211,255,.09)';for(i=0;i<this.cover.length;i++){var o=this.cover[i],op=this.world(o.x,o.y);if(op.x<-100||op.x>this.w+100||op.y<-100||op.y>this.h+100)continue;c.save();c.translate(op.x,op.y);c.rotate(o.a);c.fillRect(-o.w*.5*op.s,-o.h*.5*op.s,o.w*op.s,o.h*op.s);c.strokeRect(-o.w*.5*op.s,-o.h*.5*op.s,o.w*op.s,o.h*op.s);c.restore();}c.restore();
 for(i=0;i<this.bullets.length;i++){var b=this.bullets[i],bp=this.world(b.x,b.y),tail=this.world(b.x-b.vx*.045,b.y-b.vy*.045);c.strokeStyle=rgba(b.color,b.explosive?.55:.42);c.lineWidth=b.explosive?2.2:1;c.beginPath();c.moveTo(tail.x,tail.y);c.lineTo(bp.x,bp.y);c.stroke();}
 for(i=0;i<this.bots.length;i++)if(this.bots[i].alive)this.drawTank(c,this.bots[i]);
 for(i=0;i<this.fx.length;i++){var f=this.fx[i],fp=this.world(f.x,f.y),a=clamp(f.life/f.max,0,1);c.save();if(f.type==='boom'||f.type==='ring'||f.type==='shield'){c.strokeStyle=rgba(f.color,.55*a);c.lineWidth=f.type==='boom'?2:1;c.beginPath();c.arc(fp.x,fp.y,f.size*fp.s*(1.2-a*.35),0,TAU);c.stroke();if(f.type==='boom'){c.fillStyle=rgba('#ffb45e',.11*a);c.beginPath();c.arc(fp.x,fp.y,f.size*.55*fp.s,0,TAU);c.fill();}}else if(f.type==='trace'){var len=f.size*fp.s,ang=Math.atan2(f.vy,f.vx);c.strokeStyle=rgba(f.color,.52*a);c.lineWidth=1.4;c.beginPath();c.moveTo(fp.x,fp.y);c.lineTo(fp.x+Math.cos(ang)*len,fp.y+Math.sin(ang)*len);c.stroke();}else{c.fillStyle=rgba(f.color,.65*a);c.beginPath();c.arc(fp.x,fp.y,Math.max(1,f.size*fp.s),0,TAU);c.fill();}c.restore();}
 c.fillStyle='rgba(2,5,12,.34)';c.fillRect(0,0,this.w,this.h);};
Sim.prototype.frame=function(ts){if(this.destroyed||!this.canvas.isConnected||!this.menu.isConnected){this.destroy();return;}var self=this;if(document.hidden){this.last=ts;this.raf=requestAnimationFrame(function(t){self.frame(t)});return;}if(!this.last)this.last=ts;var elapsed=ts-this.last;if(elapsed+1<this.frameMs){this.raf=requestAnimationFrame(function(t){self.frame(t)});return;}this.last=ts;var dt=clamp(elapsed/1000,.001,.06);if(!REDUCED)this.update(dt);this.draw();if(REDUCED){this.raf=0;return;}this.raf=requestAnimationFrame(function(t){self.frame(t)});};
Sim.prototype.start=function(){var self=this;this.draw();if(!REDUCED)this.raf=requestAnimationFrame(function(t){self.frame(t)});};
Sim.prototype.destroy=function(){if(this.destroyed)return;this.destroyed=true;if(this.raf)cancelAnimationFrame(this.raf);this.raf=0;if(this._resize)window.removeEventListener('resize',this._resize);};
var active=null,observer=null,queued=false;
function menu(){return document.querySelector('#root .menu-grid-bg');}
function mount(){queued=false;var m=menu();if(!m)return;if(active&&active.menu===m&&!active.destroyed)return;if(active)active.destroy();css();var old=m.querySelector('.nova-war-room');if(old)old.remove();var oldShade=m.querySelector('.nova-war-room-shade');if(oldShade)oldShade.remove();var canvas=document.createElement('canvas');canvas.className='nova-war-room';canvas.setAttribute('aria-hidden','true');var shade=document.createElement('div');shade.className='nova-war-room-shade';shade.setAttribute('aria-hidden','true');m.insertBefore(canvas,m.firstChild);m.insertBefore(shade,canvas.nextSibling);active=new Sim(canvas,m);active._resize=function(){if(active&&!active.destroyed){active.resize();active.draw();}};window.addEventListener('resize',active._resize,{passive:true});active.start();window.__NOVA_WAR_ROOM__.mounted++;}
function queue(){if(queued)return;queued=true;requestAnimationFrame(mount);}
function observe(){var root=document.getElementById('root');if(!root)return;observer=new MutationObserver(queue);observer.observe(root,{childList:true,subtree:true});queue();}
window.__NOVA_WAR_ROOM__={version:VERSION,codename:CODENAME,level:LEVEL,classCount:CLASS_IDS.length,mounted:0,botMobile:BOT_MOBILE,botDesktop:BOT_DESKTOP,maxBullets:MAX_BULLETS,maxFx:MAX_FX,panSeconds:PAN_SECONDS,presentationOnly:true,audio:false,input:false};
window.__NOVA_WAR_ROOM_TEST__={classes:CLASS_IDS.slice(),profile:profile,level:LEVEL,botMobile:BOT_MOBILE,botDesktop:BOT_DESKTOP,maxBullets:MAX_BULLETS,maxFx:MAX_FX,panSeconds:PAN_SECONDS,reducedMotion:REDUCED};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe,{once:true});else observe();
console.info('[NOVA TANKS] v'+VERSION+' '+CODENAME+' lobby battlefield online');
})();
