/* NOVA TANKS v1.7.7 — Contained First Contact
 * Canonical lobby rule: the front door fits inside one viewport and does not scroll.
 * Deep inspection surfaces such as Blackglass may opt into their own scrolling mode.
 * Stable slots: hero, primary, briefing, actions, feature-rail, intel, utility, footer.
 */
(function(){'use strict';
var VERSION='1.7.7',CODENAME='Contained First Contact';
var data=null,modal=null,timer=0,menuRef=null,historyPages=[],historyIndex=0;
var pendingActions={},pendingCards={};
var ACTION_LIMIT=4,CARD_LIMIT=2;
window.__NOVA_LOBBY_RELEASE__={version:VERSION,codename:CODENAME,date:'2026-08-08',headline:'Everything important fits in one launch screen; depth opens in contained surfaces.',groups:{
  'One-Screen Doctrine':[
    'The default lobby never scrolls: identity, Deploy, briefing and primary destinations stay inside one viewport.',
    'Controls and update history open as contained overlays instead of extending the page.',
    'Blackglass is the deliberate exception: deep tank inspection may use scrolling inside its dedicated mode.'
  ],
  'Extension Contract':[
    'Future features must occupy a named lobby slot or open a contained overlay; they may not append vertical page height.',
    'Primary actions have a strict four-button budget and the feature rail has a strict two-card budget.',
    'Overflow registrations are rejected visibly in the console rather than silently making the lobby taller.'
  ]
}};
function css(){if(document.getElementById('nova-history-css'))return;var s=document.createElement('style');s.id='nova-history-css';s.textContent=`
.menu-grid-bg.nv-menu{overflow:hidden!important;overscroll-behavior:none!important;touch-action:none!important;scrollbar-width:none}.menu-grid-bg.nv-menu::-webkit-scrollbar{display:none}.menu-grid-bg.nv-menu.nv-showroom-mode{overflow-y:auto!important;overscroll-behavior:contain!important;touch-action:pan-y!important}
.nv-shell{position:relative!important;width:100%!important;max-width:720px!important;height:100%!important;min-height:0!important;box-sizing:border-box!important;overflow:hidden!important;padding:clamp(12px,2.8vh,24px) clamp(16px,5vw,38px)!important;justify-content:center!important}.nv-showroom-mode .nv-shell{height:auto!important;min-height:100%!important;overflow:visible!important;justify-content:flex-start!important;padding:10px!important}
.nv-hero{width:100%;margin:0!important;text-align:center}.nv-hero>div:first-child{font-size:clamp(7px,1.4vh,9px)!important;letter-spacing:.36em!important;color:#9eb2d4!important}.nv-hero>div:first-child:before{content:'WELCOME, PILOT · ';color:#7df3ff}.nv-hero h1{margin-top:clamp(4px,1vh,8px)!important;font-size:clamp(34px,min(11vw,7.8vh),66px)!important;letter-spacing:.055em!important}.nv-hero p{max-width:520px;margin:clamp(4px,1vh,9px) auto 0!important;color:#91a0b8!important;font-size:clamp(10px,1.9vh,14px)!important;line-height:1.25}
.nv-primary{width:min(100%,470px)!important;margin-top:clamp(10px,2.4vh,21px)!important}.nv-primary>button{position:relative;min-height:clamp(46px,7.8vh,58px);overflow:hidden}.nv-primary>button:after{content:'';position:absolute;inset:-2px;background:linear-gradient(105deg,transparent 25%,#ffffff55 45%,transparent 64%);transform:translateX(-125%);animation:nvSweep 4.8s ease-in-out infinite;pointer-events:none}@keyframes nvSweep{0%,58%{transform:translateX(-125%)}78%,100%{transform:translateX(125%)}}.nv-primary>div{margin-top:clamp(3px,.8vh,8px)!important;font-size:clamp(8px,1.4vh,11px)!important}
.nv-brief{width:min(100%,560px);box-sizing:border-box;margin-top:clamp(7px,1.8vh,13px);padding:clamp(7px,1.3vh,10px) 12px;border:1px solid #7df3ff24;border-radius:13px;background:linear-gradient(110deg,#10243ab8,#080c1ad1);text-align:left;box-shadow:inset 0 1px #ffffff0a}.nv-brief-top{display:flex;align-items:center;gap:7px}.nv-live{width:6px;height:6px;border-radius:50%;background:#75f0a3;box-shadow:0 0 10px #75f0a3;animation:nvLive 1.7s ease-in-out infinite}@keyframes nvLive{50%{opacity:.35}}.nv-brief-k,.nv-brief-v{font:800 clamp(7px,1.2vh,8px) Orbitron,system-ui;letter-spacing:.13em}.nv-brief-k{color:#7df3ff}.nv-brief-v{margin-left:auto;color:#61738c;white-space:nowrap}.nv-brief-line{height:clamp(22px,4.4vh,30px);overflow:hidden;margin-top:4px;font:700 clamp(9px,1.7vh,11px)/1.25 Rajdhani,system-ui;color:#d2deed;transition:.18s}.nv-brief-line.swap{opacity:0;transform:translateY(3px)}
.nv-actions{width:min(100%,590px);margin-top:clamp(6px,1.6vh,11px)}.nv-action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:clamp(5px,1vw,8px)}.nv-action{min-width:0;min-height:clamp(45px,7.5vh,64px);padding:clamp(6px,1.2vh,10px) 9px;border:1px solid #ffffff16;border-radius:13px;background:linear-gradient(145deg,#111d32d1,#070b17e8);color:#dce9f7;text-align:left;touch-action:manipulation}.nv-action:active{transform:scale(.97)}.nv-action.on{border-color:#7df3ff66;box-shadow:0 0 18px #4de3ff16}.nv-ai{display:block;font-size:clamp(13px,2.3vh,16px);color:#7df3ff}.nv-ak{display:block;margin-top:3px;font:900 clamp(7px,1.25vh,8px) Orbitron,system-ui;letter-spacing:.09em;color:#dff8ff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nv-as{display:block;margin-top:2px;font:600 clamp(8px,1.45vh,9.5px) Rajdhani,system-ui;color:#7889a2;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.nv-rail{display:none;width:min(100%,590px);margin-top:clamp(5px,1.1vh,8px);gap:6px}.nv-rail.has-items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.nv-feature{min-height:38px;padding:6px 9px;border:1px solid #ffffff16;border-radius:11px;background:#09101de0;text-align:left;overflow:hidden}.nv-fk{font:900 7px Orbitron,system-ui;letter-spacing:.1em;color:#90eaff}.nv-fh{margin-top:2px;font:700 9px/1.15 Rajdhani,system-ui;color:#d4deea;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.nv-intel{display:none!important;width:100%!important;margin:0!important}.nv-intel>.nvs-launch{display:none!important}.nv-intel>:not(.nvs-launch):not(.nvs-panel){display:none!important}.nv-intel.nvs-open{display:block!important}.nv-showroom-mode .nv-intel.nvs-open>.nvs-launch{display:flex!important;position:sticky;top:0;z-index:40;margin:0 0 8px!important;background:#07101bf5!important;backdrop-filter:blur(10px)}.nv-showroom-mode .nv-intel.nvs-open .nvs-panel{margin-top:0!important}.nv-showroom-mode .nv-hero,.nv-showroom-mode .nv-primary,.nv-showroom-mode .nv-brief,.nv-showroom-mode .nv-actions,.nv-showroom-mode .nv-rail,.nv-showroom-mode .nv-footer{display:none!important}
.nv-forge{display:none!important}.nv-util{display:none!important}.nv-util.open{display:block!important;position:fixed!important;inset:0!important;z-index:9998!important;width:auto!important;margin:0!important;padding:max(48px,env(safe-area-inset-top)) 16px max(16px,env(safe-area-inset-bottom))!important;overflow:hidden!important;background:#010309e8!important;backdrop-filter:blur(12px);touch-action:none}.nv-util.open>div:first-child{margin-top:0!important}.nv-util.open .panel{max-width:560px;margin-left:auto;margin-right:auto}.nv-util.open>div:last-child{max-width:560px;margin-left:auto;margin-right:auto}.nv-util-close{position:fixed;right:14px;top:max(12px,env(safe-area-inset-top));z-index:10000;width:34px;height:34px;border:1px solid #ffffff22;border-radius:10px;background:#ffffff0d;color:#c4cede;font-size:20px}.nv-footer{position:absolute!important;left:0;right:0;bottom:max(5px,env(safe-area-inset-bottom));margin:0!important;padding:0!important;font-size:clamp(6px,1vh,8px)!important;letter-spacing:.12em!important;color:#3e4b61!important}.nv-chip,.nv-card{display:none!important}
.nv-overlay{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;padding:max(14px,env(safe-area-inset-top)) 14px max(14px,env(safe-area-inset-bottom));background:#010309e8;backdrop-filter:blur(12px);touch-action:none;overflow:hidden}.nv-history{position:relative;display:flex;flex-direction:column;width:min(620px,100%);height:min(620px,calc(100vh - 28px));max-height:calc(100vh - 28px);overflow:hidden;padding:16px;border:1px solid #7dd2ff38;border-radius:18px;background:linear-gradient(160deg,#0d1428fa,#050812fe);box-sizing:border-box}.nv-ht{font:900 14px Orbitron,system-ui;letter-spacing:.17em;color:#e0faff}.nv-hs{margin-top:3px;font:600 10px Rajdhani,system-ui;color:#7e8ba2}.nv-x{position:absolute;right:11px;top:11px;width:34px;height:34px;border:1px solid #ffffff22;border-radius:10px;background:#ffffff0d;color:#c4cede;font-size:20px}.nv-page{display:flex;flex:1;min-height:0;flex-direction:column;justify-content:center;margin-top:10px;padding:clamp(10px,2vh,16px);border:1px solid #7df3ff28;border-radius:14px;background:#09101dcc;overflow:hidden}.nv-v{font:900 clamp(9px,1.6vh,11px) Orbitron,system-ui;letter-spacing:.1em;color:#7df3ff}.nv-name{margin-top:3px;font:800 clamp(13px,2.2vh,16px) Rajdhani,system-ui;color:#edf4ff}.nv-head{margin-top:3px;font:600 clamp(9px,1.7vh,11px)/1.25 Rajdhani,system-ui;color:#9eabc0}.nv-gt{margin-top:clamp(8px,1.6vh,12px);font:800 clamp(7px,1.25vh,9px) Orbitron,system-ui;letter-spacing:.12em;color:#83dff6}.nv-list{margin:5px 0 0;padding-left:17px;font:600 clamp(9px,1.55vh,10.5px)/1.25 Rajdhani,system-ui;color:#c2ccdb}.nv-list li{margin:clamp(2px,.6vh,4px) 0}.nv-nav{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:8px;margin-top:9px}.nv-nav button{border:1px solid #7df3ff3d;border-radius:10px;padding:8px 10px;background:#15304a66;color:#c9f5ff;font:800 8px Orbitron,system-ui;letter-spacing:.08em}.nv-nav button:last-child{justify-self:end}.nv-nav button:disabled{opacity:.25}.nv-count{font:800 8px Orbitron,system-ui;letter-spacing:.1em;color:#64748b}
@media(max-width:470px){.nv-shell{padding:10px 14px!important}.nv-hero h1{font-size:clamp(32px,10.5vw,42px)!important}.nv-action-grid{gap:5px}.nv-action{padding:6px}.nv-as{display:none}.nv-brief{padding:7px 9px}.nv-brief-v{max-width:48%;overflow:hidden;text-overflow:ellipsis}.nv-rail.has-items{grid-template-columns:repeat(2,minmax(0,1fr))}.nv-history{padding:13px}.nv-page{padding:10px}}
@media(max-height:620px){.nv-shell{padding:8px 14px!important}.nv-hero>div:first-child{font-size:7px!important}.nv-hero h1{font-size:32px!important;margin-top:3px!important}.nv-hero p{font-size:10px!important;margin-top:3px!important}.nv-primary{margin-top:8px!important}.nv-primary>button{min-height:44px!important;padding-top:8px!important;padding-bottom:8px!important}.nv-brief{margin-top:6px;padding:6px 9px}.nv-brief-line{height:22px;font-size:9px}.nv-actions{margin-top:5px}.nv-action{min-height:42px;padding:5px 7px}.nv-ai{font-size:12px}.nv-footer{display:none!important}}
@media(max-height:520px){.nv-hero p{display:none!important}.nv-brief-line{white-space:nowrap;text-overflow:ellipsis}.nv-action{min-height:38px}.nv-ak{margin-top:1px}.nv-rail{display:none!important}}
`;document.head.appendChild(s)}
function cmp(a,b){a=String(a||'0').split('.').map(Number);b=String(b||'0').split('.').map(Number);for(var i=0;i<Math.max(a.length,b.length);i++){var d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
function merge(j){var rs=(j&&j.releases||[]).slice(),p=window.__NOVA_PERFORMANCE_RELEASE__;if(p){rs=rs.filter(function(r){return r.version!==p.version});rs.push({version:p.version,codename:p.codename,date:p.date,headline:p.headline,groups:{Performance:(p.guarantees||[]).slice()}})}var l=window.__NOVA_LOBBY_RELEASE__;rs=rs.filter(function(r){return r.version!==l.version});rs.push(l);rs.sort(function(a,b){return cmp(b.version,a.version)});return{currentVersion:l.version,releases:rs}}
function current(){return data&&data.releases&&data.releases[0]||window.__NOVA_LOBBY_RELEASE__}
function leaf(root,text){var ds=root.querySelectorAll('div');for(var i=0;i<ds.length;i++)if(!ds[i].children.length&&(ds[i].textContent||'').trim()===text)return ds[i];return null}
function top(sh,node){if(!node)return null;while(node&&node.parentElement!==sh)node=node.parentElement;return node&&node.parentElement===sh?node:null}
function shell(menu,title){var n=title;while(n&&n.parentElement!==menu)n=n.parentElement;return n}
function deploy(menu){var bs=menu.querySelectorAll('button');for(var i=0;i<bs.length;i++)if((bs[i].textContent||'').indexOf('DEPLOY')>=0)return bs[i]}
function footer(menu){var ds=menu.querySelectorAll('div');for(var i=0;i<ds.length;i++)if(!ds[i].children.length&&/^NOVA TANKS v\d+\.\d+/.test((ds[i].textContent||'').trim()))return ds[i]}
function slot(name){var m=document.querySelector('#root .menu-grid-bg');return m&&m.querySelector('[data-nova-slot="'+String(name)+'"]')}
function button(icon,label,sub,fn,id){var b=document.createElement('button');b.type='button';b.className='nv-action';b.dataset.novaAction=id;b.innerHTML='<span class="nv-ai"></span><span class="nv-ak"></span><span class="nv-as"></span>';b.querySelector('.nv-ai').textContent=icon;b.querySelector('.nv-ak').textContent=label;b.querySelector('.nv-as').textContent=sub;b.onclick=fn;return b}
function status(r){var a=[];if(r.headline)a.push(r.headline);Object.keys(r.groups||{}).forEach(function(k){(r.groups[k]||[]).forEach(function(x){if(a.length<4)a.push(x)})});return a}
function tick(menu,r){if(menuRef!==menu){if(timer)clearInterval(timer);menuRef=menu;timer=0}var el=menu.querySelector('.nv-brief-line'),lines=status(r),i=0;if(!el)return;el.textContent=lines[0]||'';if(timer||lines.length<2)return;timer=setInterval(function(){if(!menuRef||!menuRef.isConnected){clearInterval(timer);timer=0;menuRef=null;return}el.classList.add('swap');setTimeout(function(){if(!el.isConnected)return;i=(i+1)%lines.length;el.textContent=lines[i];el.classList.remove('swap')},180)},4200)}
function makeHistoryPages(){historyPages=[];(data&&data.releases||[]).forEach(function(r){historyPages.push({release:r,group:null,items:null});Object.keys(r.groups||{}).forEach(function(g){var items=(r.groups[g]||[]).slice();if(!items.length)return;for(var i=0;i<items.length;i+=4)historyPages.push({release:r,group:g,items:items.slice(i,i+4)})})})}
function renderHistory(){if(!modal||!historyPages.length)return;historyIndex=Math.max(0,Math.min(historyPages.length-1,historyIndex));var p=historyPages[historyIndex],r=p.release,box=modal.querySelector('.nv-page');box.innerHTML='';var v=document.createElement('div');v.className='nv-v';v.textContent='v'+r.version+(r.date?' · '+r.date:'');box.appendChild(v);var n=document.createElement('div');n.className='nv-name';n.textContent=r.codename||'';box.appendChild(n);var h=document.createElement('div');h.className='nv-head';h.textContent=r.headline||'';box.appendChild(h);if(p.group){var gt=document.createElement('div');gt.className='nv-gt';gt.textContent=p.group.toUpperCase();box.appendChild(gt);var ul=document.createElement('ul');ul.className='nv-list';p.items.forEach(function(x){var li=document.createElement('li');li.textContent=x;ul.appendChild(li)});box.appendChild(ul)}else{var ks=Object.keys(r.groups||{});if(ks.length){var gt2=document.createElement('div');gt2.className='nv-gt';gt2.textContent='IN THIS RELEASE';box.appendChild(gt2);var ul2=document.createElement('ul');ul2.className='nv-list';ks.slice(0,5).forEach(function(x){var li2=document.createElement('li');li2.textContent=x;ul2.appendChild(li2)});box.appendChild(ul2)}}modal.querySelector('.nv-count').textContent=(historyIndex+1)+' / '+historyPages.length;modal.querySelector('[data-hist="prev"]').disabled=historyIndex===0;modal.querySelector('[data-hist="next"]').disabled=historyIndex===historyPages.length-1}
function openHistory(){if(!data)return;closeHistory();makeHistoryPages();historyIndex=0;modal=document.createElement('div');modal.className='nv-overlay';var h=document.createElement('div');h.className='nv-history';h.onclick=function(e){e.stopPropagation()};h.innerHTML='<button class="nv-x" aria-label="Close">×</button><div class="nv-ht">UPDATE HISTORY</div><div class="nv-hs">Paged to preserve the one-screen rule</div><div class="nv-page"></div><div class="nv-nav"><button data-hist="prev">← PREV</button><span class="nv-count"></span><button data-hist="next">NEXT →</button></div>';h.querySelector('.nv-x').onclick=closeHistory;h.querySelector('[data-hist="prev"]').onclick=function(){historyIndex--;renderHistory()};h.querySelector('[data-hist="next"]').onclick=function(){historyIndex++;renderHistory()};modal.appendChild(h);modal.onclick=closeHistory;document.body.appendChild(modal);renderHistory()}
function closeHistory(){if(modal){modal.remove();modal=null}}
function closeUtility(){var u=slot('utility');if(u)u.classList.remove('open');var b=document.querySelector('[data-nova-action="controls"]');if(b)b.classList.remove('on')}
function syncMode(menu){var intel=slot('intel'),open=!!(intel&&intel.classList.contains('nvs-open'));menu.classList.toggle('nv-showroom-mode',open);if(!open)menu.scrollTop=0}
function toggleShowroom(buttonEl){var menu=document.querySelector('#root .menu-grid-bg'),h=slot('intel'),l=h&&h.querySelector('.nvs-launch');if(!menu||!l)return;l.click();requestAnimationFrame(function(){syncMode(menu);buttonEl.classList.toggle('on',h.classList.contains('nvs-open'));if(h.classList.contains('nvs-open'))menu.scrollTop=0})}
function renderExtensions(menu){var grid=menu.querySelector('.nv-action-grid'),rail=menu.querySelector('.nv-rail');if(!grid||!rail)return;var actionIds=Object.keys(pendingActions),room=Math.max(0,ACTION_LIMIT-grid.querySelectorAll('.nv-action').length);actionIds.slice(0,room).forEach(function(id){if(grid.querySelector('[data-nova-action="'+id+'"]'))return;var a=pendingActions[id];grid.appendChild(button(a.icon||'◇',a.label||id,a.sub||'',function(){if(a.onClick)a.onClick({menu:menu,slot:slot});else if(a.href)location.href=a.href},id))});if(actionIds.length>room)console.warn('[NOVA lobby] action budget exceeded; use a contained overlay or feature card instead.');var cardIds=Object.keys(pendingCards);cardIds.slice(0,CARD_LIMIT).forEach(function(id){if(rail.querySelector('[data-nova-card="'+id+'"]'))return;var c=pendingCards[id],e=document.createElement('button');e.type='button';e.className='nv-feature';e.dataset.novaCard=id;e.innerHTML='<div class="nv-fk"></div><div class="nv-fh"></div>';e.querySelector('.nv-fk').textContent=c.kicker||'NEW';e.querySelector('.nv-fh').textContent=c.headline||'';e.onclick=function(){if(c.onClick)c.onClick({menu:menu,slot:slot})};rail.appendChild(e)});if(cardIds.length>CARD_LIMIT)console.warn('[NOVA lobby] feature-card budget exceeded; open a contained overlay instead.');rail.classList.toggle('has-items',!!rail.children.length)}
function enhance(){css();var menu=document.querySelector('#root .menu-grid-bg');if(!menu)return;var title=menu.querySelector('h1');if(!title)return;var sh=shell(menu,title);menu.classList.add('nv-menu');sh.classList.add('nv-shell');var hero=title.parentElement;hero.classList.add('nv-hero');hero.dataset.novaSlot='hero';var tag=hero.querySelector('p');if(tag)tag.textContent='Evolve fast. Read the battlefield. Build something dangerous.';var d=deploy(menu),pri=top(sh,d);if(pri){pri.classList.add('nv-primary');pri.dataset.novaSlot='primary'}var intel=menu.querySelector('.nvs-host');if(intel){intel.classList.add('nv-intel');intel.dataset.novaSlot='intel'}var f=top(sh,leaf(sh,'LATE-GAME GENOME FORGE'));if(f)f.classList.add('nv-forge');var util=top(sh,leaf(sh,'— HOW TO PLAY —'));if(util){util.classList.add('nv-util');util.dataset.novaSlot='utility';if(!util.querySelector('.nv-util-close')){var cx=document.createElement('button');cx.type='button';cx.className='nv-util-close';cx.textContent='×';cx.setAttribute('aria-label','Close controls');cx.onclick=closeUtility;util.appendChild(cx)}}var ft=footer(menu);if(ft){ft.classList.add('nv-footer');ft.dataset.novaSlot='footer';ft.textContent='NOVA TANKS v'+VERSION+' · ONE SCREEN · EVOLVE · ADAPT · ASCEND'}menu.querySelectorAll('.nv-chip,.nv-card').forEach(function(e){e.remove()});var br=slot('briefing');if(!br&&pri){br=document.createElement('section');br.className='nv-brief';br.dataset.novaSlot='briefing';br.innerHTML='<div class="nv-brief-top"><span class="nv-live"></span><span class="nv-brief-k">FIELD BRIEFING</span><span class="nv-brief-v"></span></div><div class="nv-brief-line"></div>';pri.insertAdjacentElement('afterend',br)}var r=current();if(br){br.querySelector('.nv-brief-v').textContent='v'+r.version+' · '+String(r.codename||'').toUpperCase();tick(menu,r)}var acts=slot('actions');if(!acts&&br){acts=document.createElement('section');acts.className='nv-actions';acts.dataset.novaSlot='actions';acts.innerHTML='<div class="nv-action-grid"></div>';br.insertAdjacentElement('afterend',acts);var grid=acts.firstChild,ib,ub;ib=button('⌬','BLACKGLASS','Tanks & builds',function(){toggleShowroom(ib)},'blackglass');ub=button('⚙','CONTROLS','Input & audio',function(){var u=slot('utility');if(u){u.classList.toggle('open');ub.classList.toggle('on',u.classList.contains('open'))}},'controls');grid.appendChild(ib);grid.appendChild(ub);grid.appendChild(button('↻','UPDATES','Version history',openHistory,'updates'))}var rail=slot('feature-rail');if(!rail&&acts){rail=document.createElement('section');rail.className='nv-rail';rail.dataset.novaSlot='feature-rail';acts.insertAdjacentElement('afterend',rail)}renderExtensions(menu);syncMode(menu)}
window.NOVALobby={version:VERSION,scrollPolicy:'viewport-only-except-deep-inspection',slot:slot,openHistory:openHistory,refresh:enhance,registerAction:function(id,s){if(id&&s){pendingActions[id]=s;enhance()}},registerCard:function(id,s){if(id&&s){pendingCards[id]=s;enhance()}},removeAction:function(id){delete pendingActions[id];var e=document.querySelector('[data-nova-action="'+id+'"]');if(e)e.remove()},removeCard:function(id){delete pendingCards[id];var e=document.querySelector('[data-nova-card="'+id+'"]');if(e)e.remove()}};
function start(){fetch('./nova-updates/releases.json',{cache:'no-store'}).then(function(r){return r.json()}).then(function(j){data=merge(j);enhance()}).catch(function(){data=merge({releases:[]});enhance()});var root=document.getElementById('root');if(root){var q=0;new MutationObserver(function(){if(q)return;q=1;requestAnimationFrame(function(){q=0;enhance()})}).observe(root,{childList:true,subtree:true})}window.addEventListener('resize',enhance)}
document.addEventListener('keydown',function(e){if(e.key==='Escape'){if(modal)closeHistory();else{var u=slot('utility');if(u&&u.classList.contains('open'))closeUtility();else{var i=slot('intel');if(i&&i.classList.contains('nvs-open')){var l=i.querySelector('.nvs-launch');if(l)l.click();var m=document.querySelector('#root .menu-grid-bg');if(m)requestAnimationFrame(function(){syncMode(m)})}}}}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
