/* NOVA TANKS v1.7.8 — Signal Flow
 * Preserves the Contained First Contact one-screen contract while adding:
 * - rotating tactical Tips instead of release-status Field Briefing
 * - one-open-at-a-time navigation across Blackglass / Controls / Debug / Updates
 * - read-only runtime diagnostics
 * - restrained menu, overlay, showroom and deploy/loading motion
 */
(function(){'use strict';
var VERSION='1.7.8',CODENAME='Signal Flow',tipTimer=0,tipMenu=null,debugModal=null,loading=null,applyQueued=false;
var TIPS=[
 'Hard cover blocks bullets, sight, and most blast pressure. Break it when the lane matters more than the shell.',
 'Friendly drones carry a faint blue IFF halo; hostile drones read red without replacing their lineage color.',
 'Cannon fuse depth changes where pressure lands. An early wall impact can make the programmed airburst unreachable.',
 'Guardians reward facing. Keep the armored front toward the threat and save Perfect Guard for committed shots.',
 'Tempest is strongest near its redline, not beyond it. Overshooting heat trades rhythm for recoil and recovery.',
 'Controller drones fight best when you give the swarm space. Tight geometry can turn a winning dive into a traffic jam.',
 'Destructible cover is part of the fight. Cannon pressure can open routes that did not exist at the start of the match.',
 'Apex tanks are sidegrades with mastery problems, not automatic upgrades. Pick the mechanic you can actually exploit.',
 'Gene grafts change how a build expresses its lineage. Read the tradeoff before chasing the bonus.'
];
window.__NOVA_VERSION=VERSION;
window.__NOVA_MENU_EXPERIENCE_RELEASE__={version:VERSION,codename:CODENAME,date:'2026-08-08',headline:'One-open-at-a-time menus, tactical Tips, diagnostics, and a coherent motion language.',groups:{
 'Menu Logic':['Field Briefing is replaced by rotating tactical Tips.','Blackglass, Controls, Debug and Updates are mutually exclusive: opening one closes the others.','Debug joins the primary action budget as a contained, read-only diagnostics surface.'],
 'Motion':['Lobby entrance, action buttons, contained overlays and Blackglass receive restrained transition motion.','Deploy now bridges into the arena with a short chassis-initialization loading screen.','prefers-reduced-motion disables nonessential animation.'],
 'Cleanup':['The obsolete v1.7.4 AUTO-UPDATE TEST badge/runtime flag is no longer shipped.']
}};
function css(){if(document.getElementById('nova-signal-flow-css'))return;var s=document.createElement('style');s.id='nova-signal-flow-css';s.textContent=`
.nv-action-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important}
.nv-tip-line{height:clamp(20px,4vh,28px);overflow:hidden;margin-top:3px;font:700 clamp(9px,1.6vh,10.5px)/1.2 Rajdhani,system-ui;color:#d2deed;transition:opacity .18s ease,transform .18s ease}.nv-tip-line.swap{opacity:0;transform:translateY(3px)}
.nv-motion-ready .nv-hero{animation:nvSigHero .48s cubic-bezier(.2,.82,.2,1) both}.nv-motion-ready .nv-primary{animation:nvSigRise .38s .06s ease both}.nv-motion-ready .nv-brief{animation:nvSigRise .38s .11s ease both}.nv-motion-ready .nv-action{animation:nvSigAction .36s ease both}.nv-motion-ready .nv-action:nth-child(1){animation-delay:.16s}.nv-motion-ready .nv-action:nth-child(2){animation-delay:.20s}.nv-motion-ready .nv-action:nth-child(3){animation-delay:.24s}.nv-motion-ready .nv-action:nth-child(4){animation-delay:.28s}.nv-action{transition:transform .15s ease,border-color .18s ease,box-shadow .18s ease,background .18s ease}.nv-action.on{background:linear-gradient(145deg,#132940e0,#07101fe8)}
.nv-overlay{animation:nvSigFade .18s ease both}.nv-history,.nv-debug-panel{animation:nvSigPanel .28s cubic-bezier(.2,.84,.2,1) both}.nv-util.open{animation:nvSigFade .2s ease both}.nv-showroom-mode .nvs-panel{animation:nvSigPanel .3s cubic-bezier(.2,.84,.2,1) both}
.nv-debug-panel{position:relative;display:flex;flex-direction:column;width:min(620px,100%);height:min(610px,calc(100vh - 24px));overflow:hidden;padding:14px;border:1px solid #7dd2ff38;border-radius:16px;background:linear-gradient(160deg,#0d1428fa,#050812fe);box-sizing:border-box}.nv-debug-panel .nv-x{position:absolute;top:10px;right:10px}.nv-debug-title{font:900 13px Orbitron,system-ui;letter-spacing:.16em;color:#e0faff}.nv-debug-sub{margin-top:3px;font:600 9px Rajdhani,system-ui;color:#7e8ba2}.nv-debug-state{margin-top:12px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;overflow:auto;min-height:0}.nv-debug-cell{min-width:0;padding:9px;border:1px solid #ffffff14;border-radius:10px;background:#07101dcc}.nv-debug-k{font:800 7px Orbitron,system-ui;letter-spacing:.11em;color:#6d88a8}.nv-debug-v{margin-top:4px;font:700 10px/1.2 Rajdhani,system-ui;color:#d7e5f3;overflow-wrap:anywhere}.nv-debug-actions{display:flex;gap:7px;margin-top:9px}.nv-debug-btn{flex:1;padding:8px;border:1px solid #7df3ff36;border-radius:9px;background:#102239;color:#c9f5ff;font:800 8px Orbitron,system-ui;letter-spacing:.08em}.nv-debug-note{min-height:13px;margin-top:7px;font:600 9px/1.25 Rajdhani,system-ui;color:#657a95}
.nv-loading{position:fixed;inset:0;z-index:2147483646;display:grid;place-items:center;background:radial-gradient(circle at 50% 42%,#102b45 0,#07111f 28%,#02050b 70%);opacity:1;transition:opacity .26s ease;overflow:hidden}.nv-loading.out{opacity:0;pointer-events:none}.nv-loading:before{content:'';position:absolute;inset:-25%;background:repeating-linear-gradient(90deg,transparent 0 44px,#58cfff0a 45px 46px),repeating-linear-gradient(0deg,transparent 0 44px,#58cfff08 45px 46px);transform:perspective(520px) rotateX(62deg) translateY(18%);animation:nvSigGrid 2.8s linear infinite}.nv-load-core{position:relative;width:min(320px,78vw);text-align:center}.nv-load-ring{width:76px;height:76px;margin:0 auto 18px;border-radius:50%;border:1px solid #7df3ff30;box-shadow:0 0 28px #4de3ff18,inset 0 0 24px #4de3ff0e;position:relative}.nv-load-ring:before,.nv-load-ring:after{content:'';position:absolute;border-radius:50%;inset:8px;border:2px solid transparent;border-top-color:#7df3ff;border-right-color:#7df3ff55;animation:nvSigSpin 1.15s linear infinite}.nv-load-ring:after{inset:21px;border-width:1px;border-top-color:#b06bff;animation-duration:.82s;animation-direction:reverse}.nv-load-title{font:900 11px Orbitron,system-ui;letter-spacing:.22em;color:#dff8ff}.nv-load-sub{margin-top:8px;font:700 9px Rajdhani,system-ui;letter-spacing:.16em;color:#62809f}.nv-load-bar{height:2px;margin-top:16px;border-radius:99px;background:#ffffff0c;overflow:hidden}.nv-load-bar:after{content:'';display:block;width:42%;height:100%;background:linear-gradient(90deg,transparent,#7df3ff,transparent);animation:nvSigBar 1.15s ease-in-out infinite}
@keyframes nvSigHero{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:none}}@keyframes nvSigRise{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}@keyframes nvSigAction{from{opacity:0;transform:translateY(7px) scale(.985)}to{opacity:1;transform:none}}@keyframes nvSigPanel{from{opacity:0;transform:translateY(-7px) scale(.992)}to{opacity:1;transform:none}}@keyframes nvSigFade{from{opacity:0}to{opacity:1}}@keyframes nvSigSpin{to{transform:rotate(360deg)}}@keyframes nvSigGrid{to{transform:perspective(520px) rotateX(62deg) translateY(12%) translateX(46px)}}@keyframes nvSigBar{0%{transform:translateX(-120%)}100%{transform:translateX(340%)}}
@media(max-width:390px){.nv-action{padding-left:4px!important;padding-right:4px!important}.nv-ak{letter-spacing:.045em!important}.nv-debug-state{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){.nv-motion-ready .nv-hero,.nv-motion-ready .nv-primary,.nv-motion-ready .nv-brief,.nv-motion-ready .nv-action,.nv-overlay,.nv-history,.nv-debug-panel,.nv-util.open,.nv-showroom-mode .nvs-panel,.nv-loading:before,.nv-load-ring:before,.nv-load-ring:after,.nv-load-bar:after{animation:none!important;transition:none!important}}
`;document.head.appendChild(s)}
function menu(){return document.querySelector('#root .menu-grid-bg')}
function slot(name){var m=menu();return m&&m.querySelector('[data-nova-slot="'+name+'"]')}
function actionButton(id){var m=menu();return m&&m.querySelector('[data-nova-action="'+id+'"]')}
function setOn(id,on){var b=actionButton(id);if(b)b.classList.toggle('on',!!on)}
function closeHistory(){var h=document.querySelector('.nv-history');if(h&&h.parentElement&&h.parentElement.classList.contains('nv-overlay'))h.parentElement.remove();setOn('updates',false)}
function closeControls(){var u=slot('utility');if(u)u.classList.remove('open');document.querySelectorAll('.nv-util-close').forEach(function(x){x.remove()});setOn('controls',false)}
function closeBlackglass(){var m=menu(),h=slot('intel');if(h&&h.classList.contains('nvs-open')){var l=h.querySelector('.nvs-launch');if(l)l.click();else h.classList.remove('nvs-open')}if(m){m.classList.remove('nv-showroom-mode');m.scrollTop=0}setOn('blackglass',false)}
function closeDebug(){if(debugModal){debugModal.remove();debugModal=null}else{var d=document.querySelector('.nv-debug-overlay');if(d)d.remove()}setOn('debug',false)}
function closeEverything(except){if(except!=='blackglass')closeBlackglass();if(except!=='controls')closeControls();if(except!=='updates')closeHistory();if(except!=='debug')closeDebug()}
function updaterState(){var s=window.__NOVA_UPDATE_STATUS||{};if(!navigator.onLine)return 'OFFLINE';if(s.ok===false)return 'ERROR';if(s.changed)return 'UPDATED';if(s.ok)return 'CURRENT';return 'IDLE'}
function snapshot(){var st=window.__NOVA_UPDATE_STATUS||{},ready=window.__NOVA_UPDATE_READY||{},sw=navigator.serviceWorker&&navigator.serviceWorker.controller;return{
 'BUILD':'v'+VERSION+' · '+CODENAME,
 'LOBBY':window.__NOVA_LOBBY_RELEASE__?'v'+window.__NOVA_LOBBY_RELEASE__.version+' · '+window.__NOVA_LOBBY_RELEASE__.codename:'n/a',
 'PERFORMANCE':window.__NOVA_PERFORMANCE_RELEASE__?'v'+window.__NOVA_PERFORMANCE_RELEASE__.version:'n/a',
 'DRONE IFF':window.__NOVA_DRONE_IFF_RELEASE__?'v'+window.__NOVA_DRONE_IFF_RELEASE__.version:'n/a',
 'UPDATER':updaterState(),
 'FINGERPRINT':st.fingerprint||ready.fingerprint||'none',
 'SERVICE WORKER':sw?'controlled':'not controlled',
 'NETWORK':navigator.onLine?'online':'offline',
 'DISPLAY':window.innerWidth+'×'+window.innerHeight+' @ '+(window.devicePixelRatio||1)+'x',
 'TOUCH':String(navigator.maxTouchPoints||0)+' points'
}}
function fillDebug(){if(!debugModal)return;var grid=debugModal.querySelector('.nv-debug-state'),s=snapshot();grid.innerHTML='';Object.keys(s).forEach(function(k){var c=document.createElement('div');c.className='nv-debug-cell';c.innerHTML='<div class="nv-debug-k"></div><div class="nv-debug-v"></div>';c.firstChild.textContent=k;c.lastChild.textContent=s[k];grid.appendChild(c)})}
function diagnosticText(){var s=snapshot();return 'NOVA TANKS DEBUG\n'+Object.keys(s).map(function(k){return k+': '+s[k]}).join('\n')+'\nUA: '+navigator.userAgent}
function copyDiagnostics(){var note=debugModal&&debugModal.querySelector('.nv-debug-note'),text=diagnosticText();function done(ok){if(note)note.textContent=ok?'Diagnostics copied.':'Clipboard unavailable; diagnostics remain visible above.'}if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){done(true)},function(){done(false)});else done(false)}
function openDebug(){closeEverything('debug');debugModal=document.createElement('div');debugModal.className='nv-overlay nv-debug-overlay';var p=document.createElement('div');p.className='nv-debug-panel';p.onclick=function(e){e.stopPropagation()};p.innerHTML='<button class="nv-x" aria-label="Close">×</button><div class="nv-debug-title">DEBUG</div><div class="nv-debug-sub">Read-only runtime and updater diagnostics</div><div class="nv-debug-state"></div><div class="nv-debug-actions"><button class="nv-debug-btn" data-debug-refresh>REFRESH</button><button class="nv-debug-btn" data-debug-copy>COPY DIAGNOSTICS</button></div><div class="nv-debug-note">No gameplay state, saves, caches, or settings are modified here.</div>';p.querySelector('.nv-x').onclick=closeDebug;p.querySelector('[data-debug-refresh]').onclick=fillDebug;p.querySelector('[data-debug-copy]').onclick=copyDiagnostics;debugModal.onclick=closeDebug;debugModal.appendChild(p);document.body.appendChild(debugModal);fillDebug();setOn('debug',true)}
function tipify(m){var br=m&&m.querySelector('[data-nova-slot="briefing"], [data-nova-slot="tips"]');if(!br)return;br.dataset.novaSlot='tips';var k=br.querySelector('.nv-brief-k'),v=br.querySelector('.nv-brief-v'),old=br.querySelector('.nv-brief-line');if(k)k.textContent='TIPS';if(old){var n=document.createElement('div');n.className='nv-tip-line';old.replaceWith(n)}var line=br.querySelector('.nv-tip-line');if(!line)return;if(tipMenu!==m){if(tipTimer)clearInterval(tipTimer);tipMenu=m;tipTimer=0;line.dataset.tipIndex='0'}function paint(){var i=Number(line.dataset.tipIndex||0)%TIPS.length;line.textContent=TIPS[i];if(v)v.textContent='TIP '+(i+1)+' / '+TIPS.length}paint();if(tipTimer)return;tipTimer=setInterval(function(){if(!tipMenu||!tipMenu.isConnected){clearInterval(tipTimer);tipTimer=0;tipMenu=null;return}var l=tipMenu.querySelector('.nv-tip-line'),tag=tipMenu.querySelector('.nv-brief-v');if(!l)return;l.classList.add('swap');setTimeout(function(){if(!l.isConnected)return;var i=(Number(l.dataset.tipIndex||0)+1)%TIPS.length;l.dataset.tipIndex=String(i);l.textContent=TIPS[i];if(tag)tag.textContent='TIP '+(i+1)+' / '+TIPS.length;l.classList.remove('swap')},180)},5200)}
function showLoading(){if(loading)return;loading=document.createElement('div');loading.className='nv-loading';loading.innerHTML='<div class="nv-load-core"><div class="nv-load-ring"></div><div class="nv-load-title">INITIALIZING CHASSIS</div><div class="nv-load-sub">LINKING ARENA · INPUT · TELEMETRY</div><div class="nv-load-bar"></div></div>';document.body.appendChild(loading);var root=document.getElementById('root'),done=false,obs=null;function finish(){if(done||!loading)return;done=true;if(obs)obs.disconnect();loading.classList.add('out');setTimeout(function(){if(loading){loading.remove();loading=null}},280)}if(root){obs=new MutationObserver(function(){if(root.querySelector('canvas'))setTimeout(finish,120)});obs.observe(root,{childList:true,subtree:true})}setTimeout(finish,1800)}
function bindDeploy(m){var bs=m.querySelectorAll('button');for(var i=0;i<bs.length;i++)if((bs[i].textContent||'').indexOf('DEPLOY')>=0&&!bs[i].dataset.nvSignalLoading){bs[i].dataset.nvSignalLoading='1';bs[i].addEventListener('click',showLoading,{capture:true});break}}
function bindActions(m){var black=actionButton('blackglass'),controls=actionButton('controls'),updates=actionButton('updates'),debug=actionButton('debug');if(black&&!black.dataset.nvExclusive){black.dataset.nvExclusive='1';var ob=black.onclick;black.onclick=function(e){var h=slot('intel'),was=!!(h&&h.classList.contains('nvs-open'));if(!was)closeEverything('blackglass');if(ob)ob.call(this,e);requestAnimationFrame(function(){var now=!!(h&&h.classList.contains('nvs-open'));setOn('blackglass',now);if(!now){var mm=menu();if(mm)mm.classList.remove('nv-showroom-mode')}})}}if(controls&&!controls.dataset.nvExclusive){controls.dataset.nvExclusive='1';var oc=controls.onclick;controls.onclick=function(e){var u=slot('utility'),was=!!(u&&u.classList.contains('open'));if(!was)closeEverything('controls');if(oc)oc.call(this,e);requestAnimationFrame(function(){setOn('controls',!!(u&&u.classList.contains('open')))})}}if(updates&&!updates.dataset.nvExclusive){updates.dataset.nvExclusive='1';var ou=updates.onclick;updates.onclick=function(e){var open=!!document.querySelector('.nv-history');if(open){closeHistory();return}closeEverything('updates');if(ou)ou.call(this,e);requestAnimationFrame(function(){setOn('updates',!!document.querySelector('.nv-history'))})}}if(debug&&!debug.dataset.nvExclusive){debug.dataset.nvExclusive='1';debug.onclick=function(){if(debugModal||document.querySelector('.nv-debug-overlay'))closeDebug();else openDebug()}}}
function ensureDebugAction(){if(!window.NOVALobby||!window.NOVALobby.registerAction)return;var m=menu();if(!m||actionButton('debug'))return;window.NOVALobby.registerAction('debug',{icon:'⌘',label:'DEBUG',sub:'Runtime status',onClick:function(){if(debugModal||document.querySelector('.nv-debug-overlay'))closeDebug();else openDebug()}})}
function apply(){css();var m=menu();if(!m)return;ensureDebugAction();m=menu();if(!m)return;tipify(m);bindDeploy(m);bindActions(m);var foot=m.querySelector('[data-nova-slot="footer"]');if(foot)foot.textContent='NOVA TANKS v'+VERSION+' · SIGNAL FLOW · EVOLVE · ADAPT · ASCEND';if(!m.dataset.nvSignalAnimated){m.dataset.nvSignalAnimated='1';m.classList.add('nv-motion-ready');setTimeout(function(){if(m.isConnected)m.classList.remove('nv-motion-ready')},700)}}
function queueApply(){if(applyQueued)return;applyQueued=true;requestAnimationFrame(function(){applyQueued=false;apply()})}
window.NOVAMenuExperience={version:VERSION,closeEverything:closeEverything,debugSnapshot:snapshot,refresh:apply};
window.__NOVA_MENU_TEST__={version:VERSION,codename:CODENAME,tips:TIPS.slice(),exclusiveTargets:['blackglass','controls','debug','updates'],nextOpen:function(current,requested){return current===requested?null:requested}};
function start(){queueApply();var root=document.getElementById('root');if(root)new MutationObserver(queueApply).observe(root,{childList:true,subtree:true});window.addEventListener('resize',queueApply)}
document.addEventListener('keydown',function(e){if(e.key!=='Escape')return;var any=!!(debugModal||document.querySelector('.nv-history')||slot('utility')&&slot('utility').classList.contains('open')||slot('intel')&&slot('intel').classList.contains('nvs-open'));if(!any)return;e.stopImmediatePropagation();closeEverything(null)},{capture:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
