const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function load(){
 const CLASSES={marksman:{bullet:{reload:1}},cannon:{bullet:{reload:.95}},twin:{bullet:{reload:.26}},guard:{bullet:{reload:.5}}};
 const classes={CLASSES,lineageForClass:id=>id==='marksman'?'sniper':id==='cannon'?'cannon':id==='guard'?'guardian':'gunner'};
 function Game(){this.time=10;this.tanks=[];this.bullets=[];this.powerups=[];this.status='playing';this.applied=[];this.los=true;}
 Game.prototype.tryFire=function(t){this.bullets.push({ownerId:t.id,x:t.x,y:t.y,vx:400,vy:0});};Game.prototype.updatePowerups=function(){};Game.prototype.applyPowerup=function(t,type){this.applied.push([t.id,type]);};Game.prototype.moveTank=function(){};Game.prototype.hasLineOfSight=function(){return this.los;};Game.prototype.getTank=function(id){return this.tanks.find(t=>t.id===id)||null;};
 const mods={'game/engine':m=>m.exports={Game},'game/classes':m=>m.exports=classes,'game/ai':m=>m.exports={updateAI(){}}};const c={window:{__novaModules:mods},console,Math};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../nova-updates/battle-sense-v1.8.1.js'),'utf8'),c);const cache={};function req(id){if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;mods[id](m,m.exports,s=>s==='./classes'?req('game/classes'):null);return m.exports;}return{c,Game:req('game/engine').Game,ai:req('game/ai'),classes};}
const T=(id,cls,x=0,y=0)=>({id,cls,x,y,vx:0,vy:0,hp:100,maxHp:100,alive:true,isPlayer:false,ai:{__v180TargetId:-1}});
test('publishes fair-play Battle Sense',()=>{const {c}=load();assert.equal(c.window.__NOVA_BATTLE_SENSE_RELEASE__.version,'1.8.1');assert.equal(c.window.__NOVA_BATTLE_SENSE__.fairPlay.hiddenCooldownReads,false);assert.equal(c.window.__NOVA_BATTLE_SENSE__.fairPlay.teamHiveMind,false);assert.equal(c.window.__NOVA_BATTLE_SENSE__.fairPlay.perObserverShotMemory,true);});
test('wounded tanks value heal above offensive resources',()=>{const {c}=load(),t=T(1,'twin');t.hp=20;const h=c.window.__NOVA_BATTLE_SENSE_TEST__;assert.ok(h.resourceValue(t,{type:'heal'},0)>h.resourceValue(t,{type:'triple'},0));});
test('witnessed heavy shot creates a finite punish window',()=>{const {c,Game,classes}=load(),g=new Game(),a=T(1,'twin'),q=T(2,'marksman',300,0);a.ai.__v181ObservedShotId=2;a.ai.__v181ObservedShotAt=9.7;assert.ok(c.window.__NOVA_BATTLE_SENSE_TEST__.witnessedOpening(g,classes,a,q,10)>0);a.ai.__v181ObservedShotAt=8;assert.equal(c.window.__NOVA_BATTLE_SENSE_TEST__.witnessedOpening(g,classes,a,q,10),0);});
test('fast-fire weapons do not create fake reload punish windows',()=>{const {c,Game,classes}=load(),g=new Game(),a=T(1,'guard'),q=T(2,'twin',200,0);a.ai.__v181ObservedShotId=2;a.ai.__v181ObservedShotAt=9.9;assert.equal(c.window.__NOVA_BATTLE_SENSE_TEST__.witnessedOpening(g,classes,a,q,10),0);});
test('hidden shots do not enter another AI observer memory',()=>{const {Game}=load(),g=new Game(),observer=T(1,'twin'),shooter=T(2,'marksman',250,0);g.tanks=[observer,shooter];g.los=false;g.tryFire(shooter);assert.equal(observer.ai.__v181ObservedShotId,undefined);g.los=true;g.time=10.2;g.tryFire(shooter);assert.equal(observer.ai.__v181ObservedShotId,2);assert.equal(observer.ai.__v181ObservedShotAt,10.2);});
test('third-party geometry chooses the opposite side of an existing duelist',()=>{const {c,Game}=load(),g=new Game(),self=T(1,'twin',-300,0),target=T(2,'guard',0,0),duelist=T(3,'cannon',200,0);g.tanks=[self,target,duelist];const v=c.window.__NOVA_BATTLE_SENSE_TEST__.thirdPartyVector(g,self,target,{});assert.ok(v.x<-.9);assert.ok(v.weight>0);});
test('AI can collect neutral powerups while player behavior remains delegated',()=>{const {Game}=load(),g=new Game(),bot=T(1,'guard',0,0);g.tanks=[bot];g.powerups=[{id:8,type:'shield',x:10,y:0}];g.updatePowerups(.1);assert.deepEqual(g.applied,[[1,'shield']]);assert.equal(g.powerups.length,0);});
test('lane risk recognizes projectile-dense ground',()=>{const {c,Game}=load(),g=new Game();g.bullets=[{x:0,y:0,vx:900,vy:0},{x:15,y:0,vx:800,vy:0}];const h=c.window.__NOVA_BATTLE_SENSE_TEST__;assert.ok(h.laneRisk(g,0,0)>h.laneRisk(g,400,400));});
test('lane risk values incoming fire above the same projectile moving away',()=>{const {c,Game}=load(),g=new Game(),h=c.window.__NOVA_BATTLE_SENSE_TEST__;g.bullets=[{x:-120,y:0,vx:600,vy:0}];const incoming=h.laneRisk(g,0,0);g.bullets=[{x:120,y:0,vx:600,vy:0}];const departing=h.laneRisk(g,0,0);assert.ok(incoming>0.35,`expected incoming threat, got ${incoming}`);assert.ok(departing<0.05,`departing fire should not poison a lane, got ${departing}`);});
test('lane risk detects a crossing trajectory before the projectile reaches the lane',()=>{const {c,Game}=load(),g=new Game(),h=c.window.__NOVA_BATTLE_SENSE_TEST__;g.bullets=[{x:55,y:-120,vx:0,vy:650}];const crossing=h.laneRisk(g,0,0);g.bullets=[{x:190,y:-120,vx:0,vy:650}];const miss=h.laneRisk(g,0,0);assert.ok(crossing>0.2,`expected projected crossing threat, got ${crossing}`);assert.ok(crossing>miss+0.15,`crossing fire should matter more than a wide miss: ${crossing} vs ${miss}`);});
test('immediate projectile proximity remains dangerous even when the shot is departing',()=>{const {c,Game}=load(),g=new Game(),h=c.window.__NOVA_BATTLE_SENSE_TEST__;g.bullets=[{x:18,y:0,vx:900,vy:0}];assert.ok(h.laneRisk(g,0,0)>0.3);});
test('lane risk can ignore the evaluating tank own projectile without hiding hostile fire',()=>{const {c,Game}=load(),g=new Game(),h=c.window.__NOVA_BATTLE_SENSE_TEST__;g.bullets=[{ownerId:7,x:-90,y:0,vx:600,vy:0},{ownerId:9,x:-110,y:0,vx:600,vy:0}];const all=h.laneRisk(g,0,0);const ignoreOwn=h.laneRisk(g,0,0,7);assert.ok(all>ignoreOwn,`self-fire should be removed from tactical risk: ${all} vs ${ignoreOwn}`);assert.ok(ignoreOwn>0.25,`hostile fire must remain dangerous after filtering own shot: ${ignoreOwn}`);});
test('resource choice does not reject a useful pickup because the bot fired through it itself',()=>{const {c,Game}=load(),g=new Game(),h=c.window.__NOVA_BATTLE_SENSE_TEST__,bot=T(7,'guard',0,0);bot.hp=25;g.tanks=[bot];g.powerups=[{id:3,type:'heal',x:120,y:0}];g.bullets=[{ownerId:7,x:20,y:0,vx:600,vy:0}];assert.equal(h.chooseResource(g,bot).id,3);g.bullets.push({ownerId:9,x:20,y:0,vx:600,vy:0});assert.ok(h.laneRisk(g,120,0,7)>0);});