const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../../nova-updates/drone-field-service-v1.10.3.js'),'utf8');
function boot(){
 function Game(){this.time=0;this.drones=[];this.tanks=[];this.bullets=[];this.tankById=new Map();this.rings=0;this.particles=0;}
 Game.prototype.getTank=function(id){return this.tankById.get(id)||null;};
 Game.prototype.damageDrone=function(d,dmg){d.hp=Math.max(0,d.hp-dmg);};
 Game.prototype.updateDrones=function(){};
 Game.prototype.hasLineOfSight=function(){return true;};
 Game.prototype.addRing=function(){this.rings++;};
 Game.prototype.addParticles=function(){this.particles++;};
 const mods={'game/engine':m=>m.exports={Game}},tips=[];
 const context={window:{__novaModules:mods,NOVATips:{registerMany(v){tips.push(...v);}}},console:{info(){},error(){}},Math,Number,Date,Map,Object,Array};
 vm.runInNewContext(source,context,{filename:'drone-field-service-v1.10.3.js'});
 const m={exports:{}};mods['game/engine'](m,m.exports,()=>null);return{Game:m.exports.Game,window:context.window,tips};
}
function tank(id,cls='marksman'){return{id,cls,x:0,y:0,hp:100,maxHp:100,alive:true};}
function drone(ownerId,extra={}){return Object.assign({id:7,kind:'drone',ownerId,x:80,y:0,hp:100,r:8,speed:180,attackCd:0},extra);}
function setup(cls='marksman'){const B=boot(),g=new B.Game(),owner=tank(1,cls),d=drone(owner.id);g.tanks=[owner];g.tankById.set(owner.id,owner);g.drones=[d];return{...B,g,owner,d};}
test('publishes repair-only Field Service after Terrain Intelligence',()=>{const {window,tips}=boot();assert.equal(window.__NOVA_FIELD_SERVICE__.version,'1.10.3');assert.equal(window.__NOVA_FIELD_SERVICE__.routingOwner,'Terrain Intelligence');assert.equal(window.__NOVA_FIELD_SERVICE__.controllerUsesCommandWeave,true);assert.equal(window.__NOVA_FIELD_SERVICE__.repairRate,.045);assert.equal(window.__NOVA_FIELD_SERVICE__.projectileHorizon,.38);assert.equal(window.__NOVA_FIELD_SERVICE__.projectileInterval,.12);assert.equal(tips.length,2);});
test('ordinary drone repairs only after the real out-of-combat delay',()=>{const {g,d}=setup();g.damageDrone(d,20);assert.equal(d.hp,80);g.time=4.4;g.updateDrones(.1);assert.equal(d.hp,80);g.time=4.7;g.updateDrones(.2);assert.ok(d.hp>80&&d.hp<82);assert.ok(g.particles>0);assert.ok(g.rings>0);});
test('visible nearby hostile keeps a damaged drone in combat',()=>{const {g,d}=setup();const enemy=tank(2,'gunner');enemy.x=180;g.tanks.push(enemy);g.tankById.set(2,enemy);g.damageDrone(d,30);g.time=7;g.updateDrones(.5);assert.equal(d.hp,70);});
test('incoming hostile projectile suppresses repair before impact',()=>{const {g,d}=setup();const enemy=tank(2,'gunner');enemy.x=-400;g.tanks.push(enemy);g.tankById.set(2,enemy);g.damageDrone(d,30);g.time=7;g.bullets=[{ownerId:2,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.equal(d.hp,70);});
test('projectile from a defeated hostile still suppresses repair while the shot is live',()=>{const {g,d}=setup();const enemy=tank(2,'gunner');enemy.team='red';enemy.alive=false;enemy.hp=0;g.tanks[0].team='blue';g.tanks.push(enemy);g.tankById.set(2,enemy);g.damageDrone(d,30);g.time=7;g.bullets=[{ownerId:2,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.equal(d.hp,70,'a live enemy shot remains dangerous after its shooter is defeated');});
test('defeated allied shooter remains friendly for projectile threat checks',()=>{const {g,d}=setup();const friend=tank(3,'gunner');friend.team='blue';friend.alive=false;friend.hp=0;g.tanks[0].team='blue';g.tanks.push(friend);g.tankById.set(3,friend);g.damageDrone(d,20);g.time=7;g.bullets=[{ownerId:3,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.ok(d.hp>80,'defeated allies must not turn their already-fired projectiles hostile');});
test('remembered hostile projectile allegiance survives shooter entity removal',()=>{const {g,d,owner}=setup();owner.team='blue';const enemy=tank(2,'gunner');enemy.team='red';enemy.x=-500;g.tanks.push(enemy);g.tankById.set(2,enemy);g.damageDrone(d,30);g.time=1;g.bullets=[{ownerId:2,x:-500,y:0,vx:600,vy:0}];g.updateDrones(.01);g.tanks=g.tanks.filter(t=>t.id!==2);g.tankById.delete(2);g.time=7;g.bullets=[{ownerId:2,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.equal(d.hp,70,'a known enemy shot must stay hostile after its shooter leaves the entity tables');});
test('remembered allied projectile allegiance survives shooter entity removal',()=>{const {g,d,owner}=setup();owner.team='blue';const friend=tank(3,'gunner');friend.team='blue';friend.x=-500;g.tanks.push(friend);g.tankById.set(3,friend);g.damageDrone(d,20);g.time=1;g.bullets=[{ownerId:3,x:-500,y:0,vx:600,vy:0}];g.updateDrones(.01);g.tanks=g.tanks.filter(t=>t.id!==3);g.tankById.delete(3);g.time=7;g.bullets=[{ownerId:3,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.ok(d.hp>80,'remembered allies must not become hostile just because their entity record was removed');});
test('fresh incoming fire interrupts repair before the slower unit-threat cache refresh',()=>{const {g,d}=setup();const enemy=tank(2,'gunner');enemy.x=-500;g.tanks.push(enemy);g.tankById.set(2,enemy);g.damageDrone(d,20);g.time=7;g.updateDrones(.1);const healed=d.hp;assert.ok(healed>80,'drone should have entered repair while the lane is clear');const state=d.__novaFieldService;assert.ok(state.nextThreatAt>7.3,'nearby-unit threat cache should still be live');g.bullets=[{ownerId:2,x:-100,y:0,vx:700,vy:0}];g.time=7.14;g.updateDrones(.2);assert.equal(d.hp,healed,'fresh incoming shot must stop repair without waiting for the slower unit scan');assert.ok(state.nextThreatAt>g.time,'the fix must not defeat staggered nearby-unit scanning');});
test('friendly and departing projectiles do not keep a drone falsely in combat',()=>{const {g,d}=setup();const friend=tank(3,'gunner');friend.team='blue';const enemy=tank(2,'gunner');enemy.team='red';enemy.x=600;g.tanks[0].team='blue';g.tanks.push(friend,enemy);g.tankById.set(3,friend);g.tankById.set(2,enemy);g.damageDrone(d,20);g.time=7;g.bullets=[{ownerId:3,x:-70,y:0,vx:600,vy:0},{ownerId:2,x:160,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.ok(d.hp>80,'friendly or departing fire must not suppress repair');});
test('wide hostile projectile miss does not suppress repair',()=>{const {g,d}=setup();const enemy=tank(2,'gunner');enemy.x=-400;g.tanks.push(enemy);g.tankById.set(2,enemy);g.damageDrone(d,20);g.time=7;g.bullets=[{ownerId:2,x:-120,y:140,vx:600,vy:0}];g.updateDrones(.5);assert.ok(d.hp>80,'wide miss should not count as active incoming fire');});
test('terrain-blocked projectile does not suppress repair',()=>{const {g,d}=setup();const enemy=tank(2,'gunner');enemy.x=-400;g.tanks.push(enemy);g.tankById.set(2,enemy);g.hasLineOfSight=()=>false;g.damageDrone(d,20);g.time=7;g.bullets=[{ownerId:2,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.ok(d.hp>80,'cover should prevent a blocked shot from suppressing repair');});
test('committed attack phases never repair',()=>{const {g,d}=setup();d.__novaPhase='dash';d.__novaCommitted=true;g.damageDrone(d,25);g.time=10;g.updateDrones(1);assert.equal(d.hp,75);});
test('Controller drones remain on Command Weave repair instead of generic repair',()=>{const {g,d}=setup('carrier');g.damageDrone(d,20);g.time=10;g.updateDrones(1);assert.equal(d.hp,80);});
test('healthy drones short-circuit before threat scanning work',()=>{assert.match(source,/if\(max<=0\|\|d\.hp>=max-\.01\)return false/);});
test('projectile refresh stays bounded while nearby-unit scans remain staggered',()=>{assert.match(source,/PROJECTILE_INTERVAL=\.12/);assert.match(source,/THREAT_INTERVAL=\.34/);assert.match(source,/if\(s\.threat\)return false;if\(tm>=s\.nextProjectileAt\)/);});
test('projectile allegiance memory never guesses an unknown shooter hostile',()=>{const {g,d,owner,window}=setup();owner.team='blue';g.damageDrone(d,20);g.time=7;const api=window.__NOVA_FIELD_SERVICE_TEST__;assert.equal(api.rememberedProjectileHostile(g,owner,999),false);g.bullets=[{ownerId:999,x:-120,y:0,vx:600,vy:0}];g.updateDrones(.5);assert.ok(d.hp>80,'unknown owner IDs remain ignored rather than guessed hostile');});
test('Field Service cannot compete with Terrain Intelligence routing',()=>{assert.doesNotMatch(source,/novaBattlefieldWaypoint|planVisibilityRoute|cachedWaypoint|navmesh|AStar|Dijkstra/i);assert.doesNotMatch(source,/d\.x\s*[+\-]=|d\.y\s*[+\-]=/);});
