const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function load(){
 const CLASSES={carrier:{size:18},marksman:{size:15},railgun:{size:17},enemy:{size:20},scout:{size:14}};
 function Game(){this.w=1000;this.h=700;this.zoom=1;this.cam={x:0,y:0,zoom:1,shake:0};this.time=10;this.drones=[];this.tanks=[];this.input={mouseActive:false,firing:false,mouseX:0,mouseY:0};this.canvas={getBoundingClientRect:()=>({left:0,top:0})};this.player=null;}
 Game.prototype.getTank=function(id){return this.tanks.find(t=>t.id===id)||null};Game.prototype.update=function(){};
 const mods={'game/classes':m=>m.exports={CLASSES},'game/engine':m=>m.exports={Game}};
 const c={window:{__novaModules:mods},console,Math,Number};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../nova-updates/tactical-framing-v1.8.2.js'),'utf8'),c);
 const cache={};function req(id){if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;mods[id](m,m.exports,s=>s==='./classes'?req('game/classes'):null);return m.exports;}return{c,Game:req('game/engine').Game,CLASSES};
}
function player(cls='carrier',extra={}){return Object.assign({id:1,cls,x:0,y:0,vx:0,vy:0,alive:true,isPlayer:true},extra);}
test('publishes Long Glass precision and reliability contract',()=>{const {c}=load();assert.equal(c.window.__NOVA_TACTICAL_FRAMING_RELEASE__.version,'1.8.2');assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.projectionCorrectAim,true);assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.hiddenTargetReveal,false);assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.hitboxInflation,false);assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.lifecycleSafe,true);assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.spotterOwnershipChecked,true);});
test('near Controller node leaves the native camera alone',()=>{const {c,Game}=load(),g=new Game();g.player=player();g.player.__novaSwarm={active:true,nodeX:180,nodeY:0};const h=c.window.__NOVA_TACTICAL_FRAMING_TEST__,pts=h.tacticalPoints(g),fit=h.fitFor(g,pts,1,false);assert.equal(pts[0].kind,'controller-node');assert.equal(fit.active,false);assert.equal(fit.zoom,1);});
test('off-screen Controller node produces a wider two-point frame',()=>{const {c,Game}=load(),g=new Game();g.player=player();g.player.__novaSwarm={active:true,nodeX:900,nodeY:0};const h=c.window.__NOVA_TACTICAL_FRAMING_TEST__,fit=h.fitFor(g,h.tacticalPoints(g),1,false);assert.equal(fit.active,true);assert.ok(fit.zoom<1);assert.equal(fit.x,450);assert.equal(fit.y,0);});
test('Sniper framing contains own spotter plus legitimate relay contact',()=>{const {c,Game}=load(),g=new Game();g.player=player('marksman');const spot={id:7,ownerId:1,x:650,y:80,hp:10,__novaSpotter:true};const enemy={id:9,cls:'enemy',x:1180,y:120,alive:true};g.drones=[spot];g.tanks=[g.player,enemy];g.player.__novaSpotterDroneId=7;g.player.__novaSpotterContactId=9;g.player.__novaSpotterContactUntil=12;const pts=c.window.__NOVA_TACTICAL_FRAMING_TEST__.tacticalPoints(g);assert.deepEqual(Array.from(pts,p=>p.kind),['spotter','relay-target']);const fit=c.window.__NOVA_TACTICAL_FRAMING_TEST__.fitFor(g,pts,1,false);assert.equal(fit.active,true);assert.ok(fit.x>500);});
test('expired relay never contributes a hidden enemy coordinate',()=>{const {c,Game}=load(),g=new Game();g.player=player('marksman');const spot={id:7,ownerId:1,x:650,y:0,hp:10,__novaSpotter:true},enemy={id:9,cls:'enemy',x:1600,y:0,alive:true};g.drones=[spot];g.tanks=[g.player,enemy];g.player.__novaSpotterDroneId=7;g.player.__novaSpotterContactId=9;g.player.__novaSpotterContactUntil=9.9;const pts=c.window.__NOVA_TACTICAL_FRAMING_TEST__.tacticalPoints(g);assert.deepEqual(Array.from(pts,p=>p.kind),['spotter']);assert.ok(!pts.some(p=>p.entity===enemy));});
test('camera projection remains exactly invertible after pan and zoom',()=>{const {c}=load();const h=c.window.__NOVA_TACTICAL_FRAMING_TEST__;const cam={x:420,y:-110};const p={x:875,y:260};const z=.63,w=1000,hh=700;const screen=h.screenOf(cam,z,w,hh,p);const back=h.worldFromScreen(cam,z,w,hh,screen);assert.ok(Math.abs(back.x-p.x)<1e-9);assert.ok(Math.abs(back.y-p.y)<1e-9);});
test('precision compensation preserves native pixel tolerance but never enlarges world hitboxes',()=>{const {c}=load(),h=c.window.__NOVA_TACTICAL_FRAMING_TEST__;const native=h.precisionRadius(15,1,.5),same=h.precisionRadius(15,1,1);assert.equal(native,same);assert.ok(native>15*.5);assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.hitboxInflation,false);});
test('Game wrapper keeps render zoom and mouse conversion zoom synchronized',()=>{const {Game}=load(),g=new Game();g.player=player();g.player.__novaSwarm={active:true,nodeX:900,nodeY:0};g.update(.016);assert.equal(g.zoom,g.cam.zoom);assert.ok(g.zoom<1);});
test('Game wrapper is safe before a player exists',()=>{const {Game}=load(),g=new Game();assert.doesNotThrow(()=>g.update(.016));assert.ok(Number.isFinite(g.zoom));assert.ok(Number.isFinite(g.cam.zoom));assert.equal(g.zoom,g.cam.zoom);assert.equal(g.__novaTacticalCamera.active,false);assert.equal(g.__novaTacticalCamera.playerRef,null);});
test('stale stored spotter id cannot frame another owner and safely reacquires own Observer',()=>{const {c,Game}=load(),g=new Game();g.player=player('marksman');const foreign={id:7,ownerId:2,x:950,y:0,hp:10,__novaSpotter:true},own={id:8,ownerId:1,x:520,y:40,hp:10,__novaSpotter:true};g.drones=[foreign,own];g.player.__novaSpotterDroneId=7;g.player.__novaSpotterContactId=-1;g.player.__novaSpotterContactUntil=0;const pts=c.window.__NOVA_TACTICAL_FRAMING_TEST__.tacticalPoints(g);assert.equal(pts.length,1);assert.equal(pts[0].kind,'spotter');assert.equal(pts[0].entity,own);assert.equal(pts[0].x,520);});
test('player replacement clears stale tactical camera ownership before the next run',()=>{const {c,Game}=load(),g=new Game();const oldPlayer=player('carrier');oldPlayer.__novaSwarm={active:true,nodeX:900,nodeY:0};g.player=oldPlayer;g.tanks=[oldPlayer];g.update(.05);assert.equal(g.__novaTacticalCamera.active,true);const replacement=player('scout',{id:44,x:500,y:100});g.player=replacement;g.tanks=[replacement];g.cam.x=500;g.cam.y=100;g.cam.zoom=1;g.zoom=1;g.update(.016);const s=g.__novaTacticalCamera;assert.equal(s.playerRef,replacement);assert.equal(s.active,false);assert.deepEqual(Array.from(s.points),[]);assert.ok(Math.abs(g.cam.x-500)<1e-9);assert.ok(Math.abs(g.cam.y-100)<1e-9);assert.equal(g.zoom,1);assert.equal(g.cam.zoom,1);assert.equal(c.window.__NOVA_TACTICAL_FRAMING__.principles.lifecycleSafe,true);});
